### ISSUE TITLE
[Bill] Enhancement: subdivide "other" votes.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1153]
We have a problem in NH, where our Representatives are essentially unpaid.  Some of them don't show up for very many votes.  It would be nice to be able to accurately tell whether they were present - to differentiate, say, an "Abstain" from an "Absent - Unexcused".  This detail is in the state data that's scraped.  I've no idea which other states provide this kind of detail.

**Comment by jamesturk** [comment]
100% agree, 'other' was a mistake and in fact the new scraper system (pupa) will actually support differentiating vote types and disallow generic 'other', as we move states to the new scraper they'll gain this feature.  Going to close this one out here as it is a solved issue in pupa.
