### ISSUE TITLE
With Sunlight Foundation closing down, what now?

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1154]
[This is off-topic, but I don't know where else to post.  I tried and failed to get this posted on the Google Group.]

I've spent this week writing code to use OpenStates data, and was really pumped.  
The news that Sunlight Foundation is shutting down all operations is quite a blow.

I was very happy to see in [this Poynter article](http://www.poynter.org/2016/sunlight-foundation-will-lay-off-5-ahead-of-merger-push/431197/): 

> Several ex-Sunlight Foundation staffers are working to keep OpenStates, a project that scrapes every state bill on a daily basis, alive, according to a former employee.

Where/how should people interested in helping out (in whatever way) contact you "_ex-Sunlight Foundation staffers_"?

Are there any alternatives to the OpenStates API that also track individual legislator votes on bills, and aren't dependent on OpenStates?  In particular, is Vote Smart a viable plan B?

**Comment by jamesturk** [comment]
Hi Ed.

I'm the former labs director and former project lead. We'll have more to
say soon but I'm feeling pretty confident right now that we'll be able to
maintain much of what openstates has been thus far.

The project means a lot to me and those that had worked on it since 2009,
we've also been reassured by the community outreach that there is indeed
still a demand for what OpenStates provides.

We were a bit taken by surprise ourselves but in coming days I'll have more
to share.

**Comment by loandy** [comment]
Hi, for the time being, you may contact @jamesturk at [jamespturk@gmail.com](jamespturk@gmail.com) if you're interested in lending a hand on Open States.  We'll all be meeting soon to see what could be done for the future of Open States.

If you're looking for an alternative API at the current moment, you could give [LegiScan](https://legiscan.com/) a try.

**Comment by jalbertbowden** [comment]
@jamesturk thanks for taking the lead here.

**Comment by bradyswenson** [comment]
@jamesturk Thanks for your work on this. We've been using OpenStates extensively for our Legislative Tracker (https://rewire.news/legislative-tracker/) mostly for information on legislators and LegiScan, which is focused much more on the legislation itself, is certainly not a complete replacement for OpenStates. Anyway, we're pulling for you and the project!

**Comment by rolandobrown** [comment]
Hi @jamesturk,

I belong to a team that would love to help keep OpenStates alive.

Mind looping us into any conversations?

We recently developed this Ruby wrapper for the Sunlight OpenStates API (we use it inhouse): https://github.com/advocacyinstitute/openstates

And happy to be a part of the development community in the future.

-Grow
www.advocacy-institute.org

**Comment by jamesturk** [comment]
Sorry for being fairly quiet on this, we're waiting on a few decisions from
within Sunlight but will definitely bring people in ASAP

**Comment by rolandobrown** [comment]
Thanks James.
 





On Mon, Oct 17, 2016 9:37 AM, James Turk notifications@github.com
wrote:
Sorry for being fairly quiet on this, we're waiting on a few decisions from
within Sunlight but will definitely bring people in ASAP

On Tue, Oct 11, 2016 at 11:29 AM, Rolando Brown <notifications@github.com>
wrote:

> Hi @jamesturk <https://github.com/jamesturk>,
>
> I belong to a team that would love to help keep OpenStates alive.
>
> Mind looping us into any conversations?
>
> We recently developed this Ruby wrapper for the Sunlight OpenStates API
> (we use it inhouse): https://github.com/advocacyinstitute/openstates
>
> And happy to be a part of the development community in the future.
>
> -Grow
> www.advocacy-institute.org
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
>
<https://github.com/sunlightlabs/openstates/issues/1154#issuecomment-252952075>,

**Comment by pmkane** [comment]
Also interested in direction, since we were planning on switching to open states legislative data for 2017 @ http://www.actionkit.com/.  Happy to contribute either engineer time or money, particularly if it is in concert with other like minded groups.

**Comment by laurenquoraishee** [comment]
Hi,

We have also been using OpenStates as well as the Congress API for our app. Please keep us updated on what is going to happen as your APIs provide a vital component of the app we have spent the past few months developing.

**Comment by jlev** [comment]
I'm also very interested in an alternative, hopefully maintaining API compatibility. I use OpenStates and other Sunlight data for open source campaign call tools at https://callpower.org

**Comment by netclift** [comment]
Say the update on the Sunlight blog. As E-Democracy.org is committed to local and state digital participation, IF you need a nonprofit fiscal agent, let me know.

We'd need volunteers to spearhead grant writing, but we can lend our experience on fundraising through pledge drives. We support our main tech and help desk costs exclusively through participant donations. This enables our volunteers to continue to facilitate on our forums.

It might be that you need a sponsorship model and some funding to do the core work of converting the main beneficiaries of your system into paying contributors. If closure is the alternative, people/orgs are more easily persuaded.

We are also the fiscal agent for Open Twin Cities, so we get how to do it.

**Comment by jamesturk** [comment]
Hi All- 

Hopefully by now you've seen our announcement: http://blog.openstates.org/post/adopting-open-states/

We're in the process of switching things over now, feel free to report any weirdness you see but please bare with us as we're ramping back up and doing so essentially in our free time.

Definitely appreciate all offers of help, it'd be great if those of you that have offered could fill out the volunteer survey at the above link, we're trying to organize those offers in one place.

& @netclift thanks for the offer of fiscal sponsorship, I think we're going to be all set (news soon) on that but still really appreciate the offer
