### ISSUE TITLE
wipe out & rescrape VA photo urls

### ISSUE THREAD

**Issue by jalbertbowden** [openstates/openstates#1155]
correct url: http://apps.lis.virginia.gov/senatepics/newbiopics/Lewis.jpg  
this came in through supportbee, making this api call:
http://openstates.org/api/v1//legislators/?state=va&active=true&first_name=Lynwood&last_name=Lewis&apikey=

**Comment by jamesturk** [comment]
VA's photos are all sorts of crazy, need to wipe them and rescrape w/o photo_url in locked_fields
