### ISSUE TITLE
TX: Democrats Page 404

### ISSUE THREAD

**Issue by klr** [openstates/openstates#1156]
The `http://www.txdemocrats.org/party/candidates` page returns a 404. This page is used for determining the party of legislators in https://github.com/sunlightlabs/openstates/blob/ca44014dbf91c803961e073a7530d84b09e86af7/openstates/tx/legislators.py#L256

**Comment by mileswwatkins** [comment]
Hear that, thanks @klr. We're in conversations with the TX Dems webmaster about getting that page back up. Will close this issue once resolved.

**Comment by mileswwatkins** [comment]
Closed by using a different source for party identity, in https://github.com/openstates/openstates/pull/1176
