### ISSUE TITLE
[boundary] Many records missing from boundary API

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1157]
I scraped all the boundary records from the API last night (throttling to 500ms/call, of course), and ran into several problems, some of which I can describe.

1. It looks like maybe all floterial districts in NH are missing with "500" errors.
2. I think PR and DC are missing; they time out (using 5 seconds).
3. Several other individual boundary records time out, e.g.: 
- ocd-division/country:us/state:ma/sldl:6th_worcester
- ocd-division/country:us/state:mo/sldl:30

Suggestions, FWIW: 

- It might make sense to leave the boundary_id blank in district records where there is no boundary record.
- Consider adding a test to check for missing boundary records.

If I did Python, I'd lend a hand.

I also have some bigger-picture suggestions re boundaries that I'll post as a separate issue.

**Comment by jamesturk** [comment]
Hi,

The boundary API is one of many pieces in need of an overhaul.  It is high on our list of things to look at, and I believe you're correct about DC & PR and I wouldn't be surprised if a few others had issues too.

Most likely the existing semi-broken data will have to continue status quo for a bit while we work on more vital pieces of infrastructure, but wanted to let you know this is definitely on our list of things to address.

**Comment by jpmckinney** [comment]
@jamesturk Let me know if there's anything to do on https://github.com/opennorth/represent-boundaries/

**Comment by jamesturk** [comment]
Thanks @jpmckinney- I think it is mostly on our end w/ some messed up data.

As an update on this ticket, the machine was way over-taxed, I bumped it up a size and it is now running about 10x faster and not returning timeouts.  There's still the issue of missing/bad district data, which we'll look at more in coming weeks.

**Comment by jamesturk** [comment]
These timeouts are now resolved, we need to do a sweep to make sure they're up to date, but timeout issue is fixed server-side, #1218 is the rest of this ticket
