### ISSUE TITLE
VT: missing boundary_id for Grand Isle district

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1159]
The district with id `vt-lower-Grand Isle-Chittenden` has an empty boundary_id.

AFAICT, it should be `ocd-division/country:us/state:vt/sldl:grand_isle-chittenden`

**Comment by estaub** [comment]
@jamesturk Recommend reopening.  The boundary_id is null still, or again; I don't recall if I verified the fix in November.

**Comment by jamesturk** [comment]
whoops, there now, had to re-run loaddistricts after editing the metadata
