### ISSUE TITLE
MA: needs a vote scraper

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1162]
As of mid-September 2016, there are no votes on bills for the Massachusetts 2015-2016 session.
There are votes for the prior session.

**Comment by mileswwatkins** [comment]
Looks like the vote scraper got turned off; tweaking the title to reflect this.

**Comment by jamesturk** [comment]
@estaub do you happen to have a good example of a bill w/ votes on the MA legislature site?  I'm digging around but not having a ton of luck at the moment

**Comment by jamesturk** [comment]
after much searching, here's a bill with a vote: https://malegislature.gov/Bills/190/H58

**Comment by jamesturk** [comment]
#1643 is another approach to this

**Comment by jamesturk** [comment]
votes!: https://openstates.org/ma/bills/190th/H58/
