### ISSUE TITLE
Missing IL State Representatives Email Addresses

### ISSUE THREAD

**Issue by gitsaxe** [openstates/openstates#1167]
@mileswwatkins 
`[
 {
   "ILL000060":"eacevedoed@ilga.gov"
 },
 {
   "ILL000985":"Assistance@StateRepCarolAmmons.com"
 },
 {
   "ILL000997":"steve@staterep65.com"
 },
 {
   "ILL000971":"info@staterep40.com"
 },
 {
   "ILL000061":"RepDistrict3@gmail.com"
 },
 {
   "ILL001000": "batinick@ilhousegop.org"
 },
 {
   "ILL000063":"dvbeiser@sbcglobal.net"
 },
 {
   "ILL000064":"rep@pbellock.com"
 },
 {
   "ILL000988":"bennett@ilhousegop.org"
 },
 {
   "ILL001003":"bourne@ilhousegop.org"
 },
 {
   "ILL000068":"repjohnbradley@mychoice.net"
 },
 {
   "ILL000069":"dan@rep-danbrady.com"
 },
 {
   "ILL000987":"peter@reppeterbreen.org"
 },
 {
   "ILL000071":"staterepbrown@gmail.com"
 },
 {
   "ILL000991":"staterepterribryant@gmail.com"
 },
 {
   "ILL000072":"burkedj@ilga.gov"
 },
 {
   "ILL000073":"kellyb@ilga.gov"
 },
 {
   "ILL001004":"butler@ilhousegop.org"
 },
 {
   "ILL000075":"Repcassidy@gmail.com"
 },
 {
   "ILL000076":"john@johncavaletto.com"
 },
 {
   "ILL000077":"lchapalavia@ilga.gov"
 },
 {
   "ILL000862":"staterepcloonen79@att.net"
 },
 {
   "ILL000863":"repdebconroy@gmail.com"
 },
 {
   "ILL000082":"staterepcostello@gmail.com"
 },
 {
   "ILL000083":"fred@fredcrespo.com"
 },
 {
   "ILL000086":"repcurrie@sbcglobal.net"
 },
 {
   "ILL000087":"john_damico@sbcglobal.net"
 },
 {
   "ILL000865":"repcddavidsmeyer@gmail.com"
 },
 {
   "ILL000088":"mdavis@ilga.gov"
 },
 {
   "ILL000089":"wdavis@ilga.gov"
 },
 {
   "ILL000090":"repdeluca@sbcglobal.net"
 },
 {
   "ILL000093":"info@repkendunkin.com"
 },
 {
   "ILL000094":"repdurkin@hotmail.com"
 },
 {
   "ILL000535":"Repevans33@gmail.com"
 },
 {
   "ILL000098":"sara@staterepsara.com"
 },
 {
   "ILL000100":"repford@lashawnford.com"
 },
 {
   "ILL000101":"mike.fortner@sbcglobal.net"
 },
 {
   "ILL000109":"greg@gregharris.org"
 },
 {
   "ILL000111":"chad@rephays.com"
 },
 {
   "ILL000112":"repehernandez@yahoo.com"
 },
 {
   "ILL000287":"Jay@JayHoffman.com"
 },
 {
   "ILL000875":"repfranhurley@gmail.com"
 },
 {
   "ILL000115":"eljackson34@gmail.com"
 },
 {
   "ILL001010":"Sjimenez@ilhousegop.org"
 },
 {
   "ILL000118":"repjones.jones@gmail.com"
 },
 {
   "ILL000119":"dwightkay112@gmail.com"
 },
 {
   "ILL000122": "repdavidleitch@gmail.com"
 },
 {
   "ILL000123":"statereplilly@yahoo.com"
 },
 {
   "ILL000880":"repmartwick@gmail.com"
 },
 {
   "ILL000129":"60thdistrict@gmail.com"
 },
 {
   "ILL000130":"repemily@gmail.com"
 },
 {
   "ILL000131":"mmcauliffe20@yahoo.com"
 },
 {
   "ILL000884":"mitchelldistrict26@att.net "
 },
 {
   "ILL000137":"moffitt@midwest.net"
 },
 {
   "ILL000990":"staterepphillips@gmail.com"
 },
 {
   "ILL000153":"robertbobrita@aol.com"
 },
 {
   "ILL000541":"Repsims34@gmail.com"
 },
 {
   "ILL001012":"Repskoog@gmail.com"
 },
 {
   "ILL000164":"repsosnowski@gmail.com"
 },
 {
   "ILL000165":"4repsoto@gmail.com "
 },
 {
   "ILL000898":"rep.tabares@gmail.com"
 },
 {
   "ILL000167":"illinois32district@gmail.com"
 },
 {
   "ILL000169":"Mike@miketryon.com"
 },
 {
   "ILL000170":"arthurt@ilga.gov"
 },
 {
   "ILL000983":"Litesa@StateRepWallace.com"
 },
 {
   "ILL000989":"office@repkeithwheeler.org"
 },
 {
   "ILL000996":"winger@ilhousegop.org"
 },
 {
   "ILL000177":"michaelz@ilga.gov"
 }
]`

**Comment by cliftonmcintosh** [comment]
Any idea if this list is accurate and current? I've sent an email to the organization asking if the list is current.
http://kidsroe.org/kids/representatives.cfm

**Comment by jamesturk** [comment]
see #1166
