### ISSUE TITLE
TX: Add 85th Session

### ISSUE THREAD

**Issue by jefe42** [openstates/openstates#1168]
I'm not sure how this works, but I thought I'd let y'all know that prefilling has started and information is available for the session that starts in January 2017.

**Comment by mileswwatkins** [comment]
Thanks @jefe42! We've got TX on our radar, and are preparing 2017-session updates for all states.

Do you have any interest in taking on the TX scraper update? It looks like not much has changed since last year. If not, no worries!

**Comment by jefe42** [comment]
Unfortunately, I'm just a consumer of the Open States API and noticed the new data wasn't there yet. I do have some coding skills, but it's more in the php and Node.JS realm. Was never able to wrap my mind around python.

I'll definitely keep an eye on the Texas data though and report anything odd I notice once session starts.

**Comment by mileswwatkins** [comment]
Absolutely, thanks for keeping an eye on the data quality! I'll keep this ticket open until we have a PR to update Texas.

**Comment by mileswwatkins** [comment]
closed by https://github.com/openstates/openstates/issues/1168

**Comment by mileswwatkins** [comment]
For reference, @jefe42, while the scraper code is now back up, the scraper infrastructure isn't running yet. @jamesturk and I will address this more in a blog post in the next week, but you can expect the Texas scraper to be running again in production soon.

**Comment by jefe42** [comment]
Thanks for the update!
