### ISSUE TITLE
CO upgraded its website

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1174]
Hello,

I noticed in the `openstates/co/bills.py`, the `base_url` is currently set to `http://www.leg.state.co.us` ([line 13](https://github.com/openstates/openstates/blob/master/openstates/co/bills.py#L13)).

They upgraded their site to `http://leg.colorado.gov/`, which is all fancy-pants. Plus, if I understand them correctly, they intend on using it in the future and will be jettisoning the older `www.leg.state.co.us` site.

So...the bills crawler (and ostensibly others) need to be rewritten to handle it.

Best,
Alex

**Comment by mshenfield** [comment]
I'm going to tackle the legislator page, and open a WIP PR for anyone who wants to pitch in.
