### ISSUE TITLE
AZ upgraded its site too

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1175]
Hello,

Apropos of my other issue #1174 ... it now seems that AZ has upgraded its site, and alas the bill crawler for AZ no longer works for previous sessions, and I would wager not for the upcoming 2017 session either.

Best,
Alex

**Comment by showerst** [comment]
I filed a pull request for a new bill scraper -- https://github.com/openstates/openstates/pull/1197 -- note that this still needs some work for prior sessions, but it pulls the 2017 prefiles if you need them.

**Comment by jamesturk** [comment]
AZ is merged, pending any hiccups it'll run tonight
