### ISSUE TITLE
PR: Session 2013-2016 Missing y/n/o_votes

### ISSUE THREAD

**Issue by Nosferican** [openstates/openstates#1178]
The fields `yes_votes`, `no_votes`, `other_votes` are missing for the 2013 - 2016 session. Looking at the source [OSLPR](http://www.oslpr.org/legislatura/tl2013/tl_busca_avanzada.asp) I noticed that they results format changed from the previous session 2009 - 2012 from .doc to pdf from scanned images. I was wondering if anyone could look into it or if anyone familiar with the process of requesting machine readable records or the likes.

**Comment by jamesturk** [comment]
Unfortunately so far our policy has been that scanned images aren't included in OS data b/c of the cost/benefit analysis of getting a reasonable OCR solution.  (Older KY data is one other that comes to mind)

We're more than open to someone helping out if it's of interest but I think trying to get them to release machine readable records is probably a better endeavor long-term.

I'd probably start simple, getting people in PR to call their representatives and explain the issue.  A call to the LIS department might also be helpful, they may already have the data and "not realize anyone cared" as we've been told before.

**Comment by Nosferican** [comment]
I will swing by next week and check with them if they can make available the machine readable versions.

**Comment by Nosferican** [comment]
Accordingly to the library of the legislature they only post the faxed images that are sent to them. However, they directed me to the House and Senate daily summaries which has the information as a pdf from which the text can be extracted and parsed. It would be just a matter of changing the scrapper to parse the pdf from each chamber.
