### ISSUE TITLE
NY: Billy misses internal IDs of many companion bills

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1201]
Eg, `WARNING billy: Unknown companion: upper 2015-2016 S 3554`

Even though I can go to both the JSONs _and_ Mongo and see that that companion _was_ scraped in that session:

```
> db.bills.findOne({'state': 'ny', 'bill_id': 'S 3554'})
{
	"_id" : "NYB00021324",
	"chamber" : "upper",
	"bill_id" : "S 3554"
	"companions" : [
		{
			"chamber" : "lower",
			"session" : "2015-2016",
			"bill_id" : "A 1000",
			"internal_id" : "NYB00000001"
		}
	],
        …
}
```

So, `S 3554` knows the Billy ID of `A 1000`, but `A 1000` can't be matched with the Billy ID of `S 3554`, seemingly.

**Comment by mileswwatkins** [comment]
Seeing a similar thing when I scrape NJ bills, eg `WARNING billy: Unknown companion: None 217 S 1114`. Chance my Billy install's imperfect, but might also be a bug.

**Comment by jamesturk** [comment]
this is a known limitation of billy, the import is single-pass so it misses companions that came later in the scrape.  when it run a second time the next day it'll match them up. just confirmed in the api these bills are correctly paired so going to close this one.

and  IIRC pupa does resolution at the very end, fixing this warning.
