### ISSUE TITLE
Consistent way to handle prefiles

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1205]
(Maybe this is an Pupa policy issue? Let me know if i should move it to pupa) 

It would be good to have a consistent approach to states with prefile-specific pages, particularly those where we only want to scrape prefiles _before_ the session starts. 

I've been using the approach of setting a prefile start date in the session metadata, and if the current date is between the prefile start and the session start, scrape prefiles. This seems good for states like KY, TN, and TX that need prefile specific logic, so we don't miss prefiles but we don't scrape those pages all the time. 

It feels a bit messy though since it's not strictly idempotent.

As discussed in person, I've only been scraping prefiles in states where there's an identifier (bill id) that lets us link the bill up later after session start. This ignores MT and IA which show requests and sometimes versions but not bill ids, but works for the majority of states.

**Comment by jamesturk** [comment]
I can think of two good ways to handle this in pupa, I think we should pick one and document our choice.

1- Pupa scrapers can take any arbitrary arguments.  Even parameters like 'session' are only going to be convention, not strictly enforced.  We could add a 'include_prefiles' or something similar, and have bill scrapers optionally accept that (default to False probably)

2- You can define multiple scrapers for a given type.  ```pupa update prefiles``` would run the scraper defined as prefiles in the __init__.py, which could yield Bill objects.  Code reuse would be a bit trickier here.

**Comment by showerst** [comment]
I'd vote for 1. -- Very few states need different code for prefiles (off the top of my head just IA and SD), so it's usually easier to write a function that just appends to the "bills to scrape" list.

**Comment by jamesturk** [comment]
added this to openstates/meta#27
