### ISSUE TITLE
NJ: Committees not scraped

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1211]
It looks like only one committee is scraping when I run New Jersey. Maybe we're reading from the wrong part of their database dump? There are definitely many more listed on the web GUI.

**Comment by mshenfield** [comment]
It looks like the issue is [here](https://github.com/openstates/openstates/blob/6e8ccffc9c5b9387ea48ba7128e948840dc15b31/openstates/nj/committees.py#L51) - `save_committees` is only being called once, with the last `comm_name` from the members loop.
