### ISSUE TITLE
Make sure legislative district boundaries are current

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1218]
Once we finish updating the scrapers for 2017 sessions, let's make sure that all of the boundaries are up-to-date, and that there wasn't any redistricting that we missed. For example, FL, NC, and VA all had their _Congressional_ districts redistricted between the 2014 and 2016 elections, so they'd be worth looking into to start.

Tangential, if anyone sees this and is aware of SLDL or SLDU boundary changes in the last couple years, let us know in this ticket!

**Comment by cfwillis** [comment]
Yes, Florida seems to be in special session since November elections (general session starts March), and the state reps claim to be using the new district boundaries.  Openstates seems to be returning older districts as of Jan 18 2017

**Comment by mileswwatkins** [comment]
Districts updated to the most recent vintage 💪

http://geo.openstates.org/divisions/?fields=id&lat=27.65&lon=-81.28, for example, now returns Florida upper district 26, rather than Florida upper district 21 (which was wrong).
