### ISSUE TITLE
Add and enforce style via linter config

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1224]
As we discussed, improve the general readability of our scrapers by adding a linter config and enforcing it for PRs. What's the go-to nowadays, @jamesturk, `flake8`?

Regardless, definitely need this in place before we transition to OCD/Pupa.

**Comment by jamesturk** [comment]
Yes, flake8 w/ maybe one or two exceptions in the config file TBD.  I'd probably vote for only running this on pupa'd scrapers to save the effort of cleaning up a non-pupa'd one.

**Comment by mileswwatkins** [comment]
Agreed. So, maybe if we continue with the repo split, we can impose via a CI or Coveralls as we create each repo.

**Comment by jamesturk** [comment]
added as a step in https://github.com/openstates/meta/issues/15
