### ISSUE TITLE
NY has blank parties, causing an issue w/  BILLY_PARTY_DETAILS lookup

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1228]
we'll need to either hard-code their party (which we've done before using ballotpedia data) or add some sort of entry for them

**Comment by jamesturk** [comment]
tagging @mileswwatkins - if you get a chance to take a look

**Comment by mileswwatkins** [comment]
@jamesturk and I talked, and decided that we might have to do a CSV-hardcode of all Assembly party values, if they aren't released soon. In the meantime, we'll hope that [the (only) official source of Assembly party affiliation](http://www.elections.ny.gov:8080/reports/rwservlet?cmdkey=nysboe_incumbnt) is updated when NY comes back into session on Wednesday.

**Comment by jamesturk** [comment]
@mileswwatkins this looks fixed?

**Comment by mileswwatkins** [comment]
Yes!
