### ISSUE TITLE
ME needs merged/retirement of old legislators

### ISSUE THREAD

**Issue by tomdionesotes** [openstates/openstates#1234]
WY is listed as one of the states that has a working scraper in the progress chart - https://github.com/openstates/planning/issues/11.

The API, however, is currently returning old data, one example being [former Senator Tony Ross](https://openstates.org/api/v1/legislators/?state=wy)

WY's member list looks up to date on their [official site](http://legisweb.state.wy.us/LegislatorSummary/LegislatorList.aspx) - S04 is listed as [Senator Nethercrott](https://gyazo.com/57ac6073dc754ca4ed90f5cb7a61bf98).

WY's session started yesterday, so it's possible their official site was only updated today.

Could someone take a look? Thanks!

EDIT: looks like ME is in the same situation

**Comment by tomdionesotes** [comment]
Thanks!

**Comment by jamesturk** [comment]
fixed for WY, changing this to ME-only

**Comment by tomdionesotes** [comment]
Thanks James. From what I can tell, Maine lower is working but Maine upper is not.

**Comment by jamesturk** [comment]
new legislators for ME upper are in, we need to manually retire some too
