### ISSUE TITLE
NC Scraped Keywords missing on Bills from Special Sessions 1, 3-5

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1235]
Audited some of the data from the 1/4/2017 18:50 UTC update. Looks like scraped keywords are showing up on special session 2.

**Comment by jamesturk** [comment]
fix for this is in place, will scrape later tonight & should be updated by tomorrow

**Comment by jamesturk** [comment]
@asentner this and #1237 should be OK now, let me know if they look reasonable to you

**Comment by asentner** [comment]
@jamesturk This one is working now too!!
