### ISSUE TITLE
NC Replacements in the 2015-2016 term are not showing

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1236]
The replacements to Tom Apodaca and Rick Catlin are not showing up for the 2015-2016 term. 

The replacements are Chuck Edwards for Tom Apodaca and Holly Grange for Rick Catlin. Both are in 2016-2017 term but do not have roles for 2015-2016 term.

I'll see if I can get a complete list of seat replacements for that term as the above are some example I have to verify data integrity.

Everything else is looking good so far from the scrape on 1/4/2016.

Thanks

**Comment by jamesturk** [comment]
to be clear, Apodaca & Caitlin were special elections in 2015-2016?

because NC doesn't make historical terms for legislators easily avaialble we'll probably need to do this as a one-off if so.

**Comment by asentner** [comment]
It looks like Apodaca and Catlin were initially in the term from the beginning and Grange and Edwards replaced them mid term. Hope that helps!!

**Comment by jamesturk** [comment]
added these two manually
