### ISSUE TITLE
NC Sponsors missing for all NC special sessions in the 2015-2016 term

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1237]
NC Sponsors missing for all NC special sessions in the 2015-2016 term. This is as of the last update on 1/4/2016.

**Comment by jamesturk** [comment]
fix for this is in place, will scrape later tonight & should be updated by tomorrow

**Comment by asentner** [comment]
Hey @jamesturk, just ran update and everything came in! This looks to be working now. Thanks!
