### ISSUE TITLE
TX: need to manually retire some legislators

### ISSUE THREAD

**Issue by grgcombs** [openstates/openstates#1241]
(Unfortunately, at least for me, this is semi-urgent issue)

The OpenStates legislators list are from the previous session (84), regardless of whether you search specifically for those in term "85" via the API. Bills come up fine for the 85th session, but the legislators list is old.

For example, 
 [House District 146](http://www.house.state.tx.us/members/member-page/?district=146) is freshman Representative Thierry Shawn.  However, OpenStates still lists ***Senator*** Boris Miles in his previous position for that district...

```bash
curl -X "GET" "https://openstates.org/api/v1/legislators/?state=tx&term=85"
```

**Comment by jamesturk** [comment]
It looks like both are actually in the list.  We'll need to manually retire the old ones.

**Comment by jamesturk** [comment]
took a first pass at this clean up, need to check after a scrape to see if we missed any

**Comment by jamesturk** [comment]
this appears to be fixed, feel free to reopen if something isn't right, but now there are the correct #

**Comment by grgcombs** [comment]
You're absolutely correct. Honestly I don't know what I was looking at before but it's all good. Thank you for indulging my wild goose chase ;-)

**Comment by grgcombs** [comment]
Oops, spoke too soon.  Looks like the House list is still lacking at least one new guy... What's the source URL that the scraper is using?  Maybe it's just out of date at the legislature.

## Texas House District 64
- Should resolve to: Lynn Stucky - http://www.house.state.tx.us/members/member-page/?district=64
- But instead resolves to his predecessor, Myra Crownover (TXL000241) ...

```bash
curl -X "GET" "https://openstates.org/api/v1/legislators/?state=tx&term=85&active=true&district=64&chamber=lower"
```

**Comment by jamesturk** [comment]
Looks like last scrape this probably wasn't updated on the site yet, I
think next run it'll be updated.
