### ISSUE TITLE
Update this scraper for the new Montana legislature

### ISSUE THREAD

**Issue by Deskimo** [openstates/openstates#1242]
The scrapers need to be tested and updated against the latest updates to the Montana legislature which may include a new site structure.

**Comment by jamesturk** [comment]
@Deskimo did you have any progress on this?  if not we'll start investigating what this will take

**Comment by Deskimo** [comment]
Not yet James, we were hoping to have more time but we're down a man due to illness and Congress YAMLs are keeping us busy as well.

**Comment by jamesturk** [comment]
OK, no worries- I'm giving it a run now to see what the current status is.

**Comment by Deskimo** [comment]
awesome - thanks for headsup James.

**Comment by Deskimo** [comment]
James checking in on your findings here - need any help with this?

**Comment by jamesturk** [comment]
MT was scraped successfully last night, we should be good to go, let us know if you notice any hiccups as they get started

**Comment by Deskimo** [comment]
Looking good our end James - thank you! legends.
