### ISSUE TITLE
PR: Update committee PDF parsing

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1243]
PR committee parsing fails currently. Although their PDFs also aren't up to date for the current session.

Eg, scraping fails for http://senado.pr.gov/comisiones/Pages/ComposicionComisionesPermanentes.aspx

**Comment by Nosferican** [comment]
I can swing by the legislature next week and pass along any concerns if need it.

**Comment by mileswwatkins** [comment]
@Nosferican, it's possible that the PR legislature hasn't yet assigned standing committee membership for this session. However, I'd say it _is_ likely that committees have been assigned, but just not posted online. A lot of state legislatures don't have put high priority on having good committee data.

So, maybe poke around a bit before filing concern? I'm not sure where the info would be if not on the LIS itself. But it'd be great to get that data back up for PR. Thanks!

**Comment by Nosferican** [comment]
I talked to them today... apparently the change is due to them posting the faxed images that the chambers send the library. However, each chamber's website has a pdf daily summary which can be parsed to get the relevant data. I would be down to update the scrapper. I developing the scrapper in R good or is there any other standard for the project? I don't know the specifics of the server running the scripts.

**Comment by mileswwatkins** [comment]
Thanks for the info, @Nosferican! What would one of those daily URLs be, out of curiosity? I didn't see one when I looked before.

As far as building out the scraper, our infrastructure only uses Python, so focus on that. Here's the file that you'd build out: https://github.com/openstates/openstates/blob/master/openstates/pr/committees.py

Check out [the quickstart documentation](https://github.com/openstates/openstates#getting-started), and if you have issues, hop on [the Open State Slack](http://openstates-slack.herokuapp.com/) and ask!

**Comment by jamesturk** [comment]
If you have a source for this @Nosferican I'd be glad to take a look, if not I think we might have to disable committees for PR semi-permanently pending PR posting them again

**Comment by jamesturk** [comment]
found http://senado.pr.gov/Pages/ComisionesPermanentes.aspx

**Comment by Nosferican** [comment]
For the lower house: http://www.tucamarapr.org/dnncamara/ActividadLegislativa/ComisionesyProyectosEspeciales.aspx
