### ISSUE TITLE
NH: needs committees & photos

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1248]
disabled these for 2017

**Comment by jmcarp** [comment]
Is the idea to pull from http://gencourt.state.nh.us/dynamicdatafiles/ instead of whatever lives at 216.177.20.245?

**Comment by showerst** [comment]
Yes, I think we're treating that SQL database as deprecated.

**Comment by jamesturk** [comment]
confirmed comms look good in DB, waiting on #1374
