### ISSUE TITLE
TX Upper + MO Upper scrapers not working

### ISSUE THREAD

**Issue by tomdionesotes** [openstates/openstates#1252]
Hey there,

TX + MO are both states that have already started their legislative session and have a working scraper per the [status page](https://github.com/openstates/planning/issues/11).

For both of those states, the API has the new legislator information for the lower chamber, but not for the upper chamber.

Could you take a look?

Thanks!

Tom

**Comment by jamesturk** [comment]
TX is #1262

**Comment by jamesturk** [comment]
looking into MO too
