### ISSUE TITLE
MA: API and website not returning all legislators

### ISSUE THREAD

**Issue by sdondley** [openstates/openstates#1258]
Only Senate members are returned, no one from the house.

**Comment by jamesturk** [comment]
to be clear, this is on geo API calls correct?

**Comment by sdondley** [comment]
Yes.

**Comment by jamesturk** [comment]
Looks like issue is switch of district  names from 'Second' to '2nd'

we should use same rules we do in the senate to switch them back, will require merges if we don't coordinate w/ a DB update, so probably best to do a one-off DB update then re-run scraper

**Comment by jamesturk** [comment]
see #1388 for more clear examples
