### ISSUE TITLE
KS Committee Members not updated

### ISSUE THREAD

**Issue by Wizofgoz** [openstates/openstates#1260]
Example:
https://openstates.org/api/v1//committees/KSC000054/?apikey=2a5533919c9743b4b15ae0168b36906a

vs

http://kslegislature.org/li/b2017_18/committees/ctte_h_electns_1/

related to #1253

**Comment by Wizofgoz** [comment]
Any update on this? We have some clients asking.

**Comment by jamesturk** [comment]
investigated & KS comm. scraper needs at least a partial rewrite

**Comment by Wizofgoz** [comment]
@jamesturk any more updates on this?

**Comment by jamesturk** [comment]
not yet- @erinspace is investigating this now so we might have an update soon
