### ISSUE TITLE
TX: needs old legislators merged/retired

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1262]
it worked once or twice, but now the old legislator roster pages are gone, will need a rewrite of TX legislators

**Comment by jamesturk** [comment]
TX fix is in place, will need verification after tonight's run

**Comment by tomdionesotes** [comment]
Looks like the API is still returning the old TX upper folks after last night's run.

**Comment by jamesturk** [comment]
they're in now but need to dedupe/merge legislators
