### ISSUE TITLE
MO: Retire 98th-session senators

### ISSUE THREAD

**Issue by Wizofgoz** [openstates/openstates#1269]
Example:
Paul LeVota is shown in the list:
https://openstates.org/api/v1//legislators/?state=mo&active=true&apikey=*******

and not in this list
http://www.senate.mo.gov/2017-senator-listing-2/

**Comment by ladonkey7** [comment]
We checked in and heard that the MO upper chamber was up to date, but we're still seeing discrepancies in several districts – 4, 15, 19, 21, 23. For example, Eigel is now the senator for district 23 and Dempsey is still returned

**Comment by jamesturk** [comment]
Confirmed that MO changed their Senator listing but left the old page up, we'll need to change the scraper to use the above http://www.senate.mo.gov/2017-senator-listing-2/

**Comment by mshenfield** [comment]
This should be easier - http://www.senate.mo.gov/senators-listing/. It doesn't include Paul LeVota, and Eigel is 23, so I think it is up to date.

**Comment by mileswwatkins** [comment]
The PR has been merged, only thing left is to remove the incorrect senators from the production database.
