### ISSUE TITLE
WA: Clean whitespace from email addresses

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#1279]
For example - https://openstates.org/api/v1/legislators/WAL000173/ - this legislator's email address is present in the office block but not in the legislator data.  Secondarily, it's also surrounded by whitespace and newlines.

**Comment by mileswwatkins** [comment]
Thanks for the catch on the whitespace, @samtregar. Email addresses are actually supposed to be tied to offices, especially in cases like this where it's a state-legislature-provided `.gov` email address. (Although, as I'm sure you've seen, on rare occasions `email` is a top-level property.)

@jamesturk, am I misremembering?

**Comment by samtregar** [comment]
I find that a bit surprising - doesn't it make more sense for a legislator's email address to be assigned to them rather than one of their offices?  In the case of WA state reps around 50% had it attached to the person.

**Comment by samtregar** [comment]
Here's an example of a rep with an email address assigned directly to the person:

https://openstates.org/api/v1/legislators/WAL000170/

**Comment by mileswwatkins** [comment]
Consider the case of a legislator who has a personal ("district") email, as well as a state-assigned `.gov` email, such as http://legislature.vermont.gov/people/single/2018/14587

I believe that we moved email to a office-level property so that we could store both.

**Comment by samtregar** [comment]
Very interesting!  I'd say his work email is associated with his job rather than a particular office.  What office would you pick for his home email address in this case?

**Comment by mileswwatkins** [comment]
Home email addresses are often what the legislator uses for district/re-election work, so that's how we categorize them. Frankly, "district offices" in many less-professionalized states are often just that person's home.

**Comment by samtregar** [comment]
Interesting and good to know!
