### ISSUE TITLE
ALL: API Flag to return data in camelCase

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1283]
First off, this api is excellent, and after trying to build my own scraper initially, I really appreciate all the work that's gone into this and all the edge cases that this covers.

This feature request might seem a bit pedantic, but it would be great if we could provide a flag when making api requests to get the fields back in camelCase instead of lowercase_with_underscores. I realize that Python and even MongoDB often prefer lowercase, but JavaScript apps (which consume this data) often prefer camelCase and even have linters to enforce those rules, and it would be nice if we could follow our internal code standards while using this api.

Currently, I have an import script which remaps all the fields to camelCase after calling the api so I can keep my codebase consistent. My concern is that if these field names ever change at the api level, my import/remapping code may break. Perhaps this is an unnecessary concern, but it would still be nice to be able to move the remapping code to a centralized place where others could potentially benefit as well.

I'm happy to provide the remapping code (in JavaScript) if it would help. I have a limited grasp of Python, so I'm not sure I could be much help with a pull request.

**Comment by paultag** [comment]
Thanks for the idea!

I don't think this is something we'd want to implement. It's a lot of complexity for not a ton of gain (style, at most). Maybe writing a JavaScript library to talk to the API translating it into something idiomatic, allowing client code to continue to be idiomatic would be a good approach!

Documenting client bindings is a good next step - let me know if you publish one in JavaScript, I'll likely start rounding those up soon.

**Comment by richardm** [comment]
I actually just stumbled upon this JavaScript library, which will walk the objects and convert the keys to camelCase or whatever else is desired. This is what I'll likely use to avoid having to manually remap the fields, which was my primary concern:
https://github.com/domchristie/humps
