### ISSUE TITLE
TX: Bills filed in upper chamber missing leg_id for most (now just a couple) sponsors

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1284]
Bills filed in the lower chamber have the leg_id populated, but it's missing for most bills filed in the upper chamber.

Broken: (only Campbell and Perry have leg_id populated)
https://openstates.org/api/v1/bills/?state=tx&search_window=session&chamber=upper&updated_since=2017-01-21&fields=bill_id,sponsors

Working:
https://openstates.org/api/v1/bills/?state=tx&search_window=session&chamber=lower&updated_since=2017-01-21&fields=bill_id,sponsors

The xml format / data appears to be the same for both upper and lower chamber. Example:
ftp://ftp.legis.state.tx.us/bills/85R/billhistory/senate_bills/SB00500_SB00599/SB%20568.xml
ftp://ftp.legis.state.tx.us/bills/85R/billhistory/house_bills/HB01200_HB01299/HB%201203.xml

**Comment by richardm** [comment]
Excellent - this is fixed for most people. It appears to still be broken for at least one senator. From the "broken" link above, if you load in a browser and search for "leg_id": null, you'll see a few that are still coming back null. It appears to just be Senator Rodriguez:
{"leg_id": null, "official_type": "author", "type": "primary", "name": "Rodrguez", "committee_id": null}

At first glance, this is appears to be related to the utf-8 encoding issue mentioned here affecting his name: https://github.com/openstates/openstates/issues/1294

**Comment by jamesturk** [comment]
it looks like TX is spelling his name "Rodrguez" or at least that's what we're picking up, will probably need a manual resolution

**Comment by jamesturk** [comment]
fixed, was dropping unicode chars in bill scrape
