### ISSUE TITLE
ALL: API is not sending a Content-Encoding header

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1285]
The response size seemed a bit large for a few requests, and I noticed there's no Content-Encoding header being sent back, even though I'm providing Accept-Encoding: gzip, deflate, br. It appears that basic gzip / compression is not enabled for the api, and I can't think of a reason why an api would not have that enabled. It should improve performance both on your servers and for those calling the api.

**Comment by jamesturk** [comment]
openstates/openstates.org#41

**Comment by jamesturk** [comment]
thanks for the suggestion - going to close this in favor of openstates/openstates.org#41
