### ISSUE TITLE
MS: Legislator ID not matched when last name is not unique

### ISSUE THREAD

**Issue by redNixon** [openstates/openstates#1286]
State: MS

There are several issues appearing in the MS data due to the naming convention that MS is using when legislators that are members of the same chamber share a last name.

For example of this issue, these two representatives show what this can cause [Donnie Bell](https://openstates.org/ms/legislators/MSL000097/donnie-bell/) and [Christopher Bell](https://openstates.org/ms/legislators/MSL000263/christopher-bell/).  

Their [votes](http://billstatus.ls.state.ms.us/2017/pdf/votes/house/0170003.pdf) are listed as "Bell (district #)" on the vote roll calls.  Due to this, their full names are not listed on the [full roll call](https://openstates.org/ms/votes/MSV00020278/) and their profiles are not linked as well.

[Bills sponsored](http://billstatus.ls.state.ms.us/documents/2016/pdf/HB/1500-1599/HB1581SG.pdf) by either member will appear as "Bell (district #)" as well.  This causes the [sponsorship history](https://openstates.org/ms/bills/?sponsor__leg_id=MSL000097) to not include the bill.

These issues result in the situation where C. Bell who has served starting in the 2016 session has no history at all on his [page](https://openstates.org/ms/legislators/MSL000263/christopher-bell/) and D. Bell who has served since 2005 has his [page's](https://openstates.org/ms/legislators/MSL000097/donnie-bell/#committees) history cut off at the 2015 session.

NameMatcher._learn does not have a form that references district number, I am not sure if any other state is using this naming convention though.  If an audit of incomplete name matches in other states shows a widespread problem, a fallback method to attempt an intelligent match might be the better solution to handle one-offs than adding more name forms to matcher or manual intervention.

**Comment by jamesturk** [comment]
Thanks for the heads up, we'll take a look and I think we can resolve these
cases with our existing tools.

Fortunately, have the ability to add aliases manually, we prefer this over
trying to get too smart because of the high probability of inaccurate data
that is hard to undo if we match incorrectly/overzealously.

**Comment by jamesturk** [comment]
rolling into #3102
