### ISSUE TITLE
Florida is not yet available for 2017

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1290]
State: FL

Florida's session starts on 3/7, we'll monitor the situation and resume scraping ASAP

**Comment by king-tuts** [comment]
While the Florida Session does not start until March, I understand that the Florida legislature hears many bills in committee in January and February. As far as I know, almost half of all bill hearings happen before the Session actually begins in March. 

Is there anyway to begin the scraping in February?

**Comment by showerst** [comment]
@jamesturk i'm running the Florida bills scraper from master right now and it's fine. (it has the 2017 session, though looks like it needs a new term which i'll PR shortly). Haven't checked to see if legs and committees are updated though.
