### ISSUE TITLE
ID: district values should not include the word 'district'

### ISSUE THREAD

**Issue by tomdionesotes** [openstates/openstates#1295]
State: ID
Chamber: both upper and lower
Example: https://openstates.org/api/v1/legislators/IDL000233/
`district": "District 26"`

Compare to CA: https://openstates.org/api/v1/legislators/CAL000338/ 
`district": "72"`

**Comment by jamesturk** [comment]
to avoid having to merge these we'll need to do an update in the DB and then merge jpt/id-district-fix branch
