### ISSUE TITLE
NH Bill text points to wrong document.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1296]
State: NH

Many or all bill texts for NH's 2017 session are wrong.  Use the openstates.org website to look at a few.
In case the problem isn't as obvious as I think, here's one:

NH's `HB 544` (OpenStates `NHB00006021`) is a bill titled: 

> relative to earned time credits for prisoners participating in rehabilitative or educational programming.

A single version is listed in the bill detail API response, with a URL of 
http://www.gencourt.state.nh.us/bill_status/billText.aspx?sy=2017&id=0761&txtFormat=html

The document at that URL is a fiscal note on an unrelated bill, `HB 407`.

I have not tried to determine if this affects earlier sessions.

**Comment by estaub** [comment]
The problem seems to be an off-by-one error in the `id` query parameter in the document URL.

In the case above, where the API returns
http://www.gencourt.state.nh.us/bill_status/billText.aspx?sy=2017&id=0761&txtFormat=html
it should actually be returning
http://www.gencourt.state.nh.us/bill_status/billText.aspx?sy=2017&id=760&txtFormat=html

where the only difference is the id being 761 and 760, respectively.

**Comment by showerst** [comment]
I suspect it's more complicated that an off-by-one error most of the time. 80% of the time the bill's NH internal ID (LSR) works in that slot, but then if there was another doc published  around the same time, sometimes the ID gets off.

I'm going to look at this tonight, but in case anyone beats me to it we just need to find the mapping between the LSR and the &id= to drop into billText.aspx. 

If someone can check the text files http://gencourt.state.nh.us/dynamicdatafiles/ for any row that maps either the bill number HB 544 or LSR 761 to "760" that should do it.

**Comment by showerst** [comment]
N.B. - The mapping is in http://gencourt.state.nh.us/dynamicdatafiles/LsrsOnly.txt?x=20170124121048 

I'll put in a pull request tonight for this.
