### ISSUE TITLE
UT:  Bill parser throwing exception

### ISSUE THREAD

**Issue by jonConerly** [openstates/openstates#1310]
The UT bill scraper is throwing an exception due to a new website/display for some of the votes(committee and legislature).  The new website is causing a couple of things to not get accurately scraped  like the description and votes.  The actual exception is done by a raise warning that the data is wrong, so that part is not a bug.

The new page is actually very similar to the old html display(believe it is just loading it in), so the current xpath code *pretty much* matches.  I believe one of the main reasons why some of the old parser is failing is due to malformed HTML rather than actual code changes to the website; code like `<b><center>content</b>` is messing up the some of the xpath code since things like //center/b would no longer apply to it.  I have a hacky workaround for the time being that will detect the xpath failures and use the new xpaths.  I'll submit it after running through the 2016 data(appears website change is randomly retroactive) to get a better test depth on it.    I'm hesitant to do a real permanent fix to support bugged HTML that might/should be changed in the future.

**Comment by jamesturk** [comment]
fixed!
