### ISSUE TITLE
VA: Remove broken bill version URLs from the database

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1314]
State: VA

Due to a scraper bug (pull request incoming), VA bill versions hosted on sites other than the main legislative site have broken URLs. We added the legislative site base url to the front of the string, even though they already had http://. [Example](https://openstates.org/va/bills/2017/HB1500/). 

Find bills in VA with two occurrences 'http' and delete them.

**Comment by jamesturk** [comment]
this looks to be fixed too
