### ISSUE TITLE
NC: Committee assignments are not yet listed in Openstates API

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1317]
State: NC

Committee assignments are out but I am not seeing them an the API yet.

**Comment by jonConerly** [comment]
The membership seem to be scraping fine, locally at least.  Based on the update time, https://openstates.org/api/v1/committees/NCC000167/,  it looks like the scraper just needs to be ran again to get the members instead of only the chair.

**Comment by jamesturk** [comment]
I'll take a look, might just  need to switch NC comms back on.

**Comment by jamesturk** [comment]
this should run tonight, we'll check tomorrow

**Comment by asentner** [comment]
Definitely got some data this morning. Looks full. I'll let you know if I notice any problems.
