### ISSUE TITLE
GA: Not scraping this session's committee assignments

### ISSUE THREAD

**Issue by nitrag** [openstates/openstates#1318]
State: GA

As of today, the Committee assignments are from last session.

Official:
http://www.house.ga.gov/Committees/en-US/committee.aspx?Committee=88&Session=24
OpenStates:
https://openstates.org/ga/committees/GAC000032/appropriations/

You can see from the official source that Chad Nimmer is no longer the vice-chairman.

RE: https://github.com/openstates/planning/issues/11

**Comment by jamesturk** [comment]
thanks for filing! there are def. committee scrapers that need attention, we'll see what the situation is

**Comment by jamesturk** [comment]
should run next time
