### ISSUE TITLE
TX: Missing calendar events for upcoming committee meetings

### ISSUE THREAD

**Issue by grgcombs** [openstates/openstates#1324]
State: TX

Looks like the scraper for events (upcoming committee meetings) isn't collecting anything.  The House chamber still hasn't posted any meeting notices, but the Senate definitely has posted upcoming meetings. From what I can see, the legislature is posting the committee meeting event information in the same manner as they have in the past -- HTML & RSS

- I grabbed the following RSS feeds from here: http://www.capitol.state.tx.us/MyTLO/RSS/RSSFeeds.aspx
- Senate Upcoming Committee Meetings  
  - RSS: http://www.legis.state.tx.us/MyTLO/RSS/RSS.aspx?Type=upcomingmeetingssenate
  - HTML: http://www.legis.state.tx.us/Committees/MeetingsUpcoming.aspx?Chamber=S
- House Upcoming Meetings
  - RSS: http://www.legis.state.tx.us/MyTLO/RSS/RSS.aspx?Type=upcomingmeetingshouse
  - HTML: http://www.legis.state.tx.us/Committees/MeetingsUpcoming.aspx?Chamber=H

**Comment by jamesturk** [comment]
turned on TX event scrapers again

**Comment by jamesturk** [comment]
scraping tonight, let's see if it works
