### ISSUE TITLE
CO committee memberships out of date

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1326]
State: CO (Colorado)

It doesn't appear CO committee memberships are up-to-date.

For example, in the [House Agriculture, Livestock, & Natural Resources committee](https://openstates.org/co/committees/COC000131/agriculture-livestock-natural-resources/) the former state representative [Timothy Dore](https://openstates.org/co/legislators/COL000119/timothy-dore/) appears as a current member of the committee...which is clearly incorrect.

**Comment by jamesturk** [comment]
CO comms scraper needs some love, isn't running properly at the moment

**Comment by jonConerly** [comment]
Webpage is correct because that site is no longer being maintained.  Looks like Colorado got a new website.  http://leg.colorado.gov/node/927946/ and http://leg.colorado.gov/committees/agriculture-livestock-natural-resources/2017-regular-session shows the new membership.

**Comment by jamesturk** [comment]
:+1: needs verification after next run
