### ISSUE TITLE
WA Needs Retirement/Merging of Old Legislators

### ISSUE THREAD

**Issue by jaboi** [openstates/openstates#1327]
State: WA

Similar to Issue #1234, the API is returning old legislators for Washington state, although it is listed as having scrapers running.

Could someone look into the data for WA like was done for ME and WY?

Current WA House members (lower chamber) are here: http://leg.wa.gov/House/Representatives/Pages/default.aspx

Current WA Senate members (upper chamber) are here: http://leg.wa.gov/Senate/Senators/Pages/default.aspx

Thank you!

**Comment by jamesturk** [comment]
on this now

**Comment by jaboi** [comment]
Thanks for the prompt action!
