### ISSUE TITLE
TX: No chamber for TXL000202

### ISSUE THREAD

**Issue by ronisaacson** [openstates/openstates#1331]
State: TX

The record for TXL000202 is missing the chamber field. The website identifies this member as the Lt. Governor, but also puts him in the Senate, which seems confusing. (Maybe it's a courtesy listing because he has some Senate responsibilities as Lt. Governor?)

Of all 7544 active legislators, this is the only one without a chamber.

**Comment by mileswwatkins** [comment]
This is correct; the Texas lt gov has more of a role in the legislature than any other member of the executive branch in any state, including voting privileges IIRC. He is not a senator, though, so is not assigned a chamber.
