### ISSUE TITLE
Automated QA

### ISSUE THREAD

**Issue by jmcarp** [openstates/openstates#1337]
I'm wondering whether we can automatically detect some categories of openstates bugs, without waiting for users to report them. For example, we should be able to detect dead or broken links, as well as missing data. WDYT about adding some kind of automated QA, at scrape time and/or periodically afterwards? Is this already happening?

**Comment by jamesturk** [comment]
There's a decent amount of automated QA (check out /admin if you run a local copy of openstates.org) but we definitely need to add more, including making use of the filters idea we added late in the process but never fully adopted.

As we move to new infrastructure we should consider the biggest pain points and work on automating detection and fixers.

**Comment by jamesturk** [comment]
reticketing this to openstates/meta#26
