### ISSUE TITLE
AL lower: malformed 3 digit district fields

### ISSUE THREAD

**Issue by tomdionesotes** [openstates/openstates#1339]
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B100
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B101
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B102
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B103
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B104
https://openstates.org/api/v1/legislators/?state=al&district=%26nbsp%3B105

**Comment by jamesturk** [comment]
committed fix in 32f9419, needs run
