### ISSUE TITLE
NC - Committee assignments missing for a house member

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1342]
State: NC

There may be more, I just happen to find this today. Jay Adams is missing committee assignments. The API does not show any in roles. 

https://openstates.org/api/v1/legislators/NCL000338/

The NCGA site shows committee assignments here: http://www.ncleg.net/gascripts/members/reports/committeeAssignments.pl?nUserid=697&Chamber=H

There may be something broken and it may affect more members in NC.

I have assignments for others. Have not determined what is different between Adams and the others

**Comment by asentner** [comment]
Also, just noticed the API is open now? I clicked the link and was able to see the data without a key.

**Comment by jamesturk** [comment]
thanks for this report, I'll look into it

(& API is indeed open at the moment, without Sunlight's old API key infrastructure we decided to wait and prioritize data quality)

**Comment by asentner** [comment]
Hey @jamesturk any luck with this?

**Comment by ebmshenfield** [comment]
Taking a look tonight

**Comment by mshenfield** [comment]
Taking a look
