### ISSUE TITLE
WA: cache has stale erroneous entries

### ISSUE THREAD

**Issue by MikeStall** [openstates/openstates#1345]
State: WA  (be sure to include in ticket title)

I noticed there were duplicated bills.  For example, HB 1001 shows up twice:
https://openstates.org/api/v1/bills/WAB00011858/
https://openstates.org/api/v1/bills/WAB00011846/

Both entries have the same number, title, etc. Although one has more activity than the other. 
I’m getting these numbers from doing a bill search ( https://openstates.org/api/v1/bills/?state=wa&search_window=session ) 

I dug a bit deeper and it looks like for each pair of duplicates, one of them had an error (chamber was set wrong).   And then the scraper was re-run to fix it, but the old value still stayed in the cache and was being served up by the search. 

Can you clear the old entries from the cache?

**Comment by jamesturk** [comment]
fixed

**Comment by MikeStall** [comment]
Thanks! I confirmed and it looks good.
