### ISSUE TITLE
DE: legislators scrape is failing

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1348]
State: DE

Delaware has been failing for about a week, looks like a change in the Legislators scraper.

**Comment by jonConerly** [comment]
I've fixed most of this, District 10 is vacant though.  Would you rather district be skipped or create a "vacant" legislator?

It looks like the special election is on Feb 25th though: https://ballotpedia.org/Delaware_State_Senate_District_10

**Comment by jamesturk** [comment]
replied in slack too but for posterity- you can skip vacant districts
