### ISSUE TITLE
[All States?] Exchange legislators' nimsp_candidate_id value for an entity ID from FollowTheMoney.org

### ISSUE THREAD

**Issue by grgcombs** [openstates/openstates#1355]
This enhancement request may apply to legislators in all states?  

It looks like the OpenStates legislator's nimsp_id value has been deprecated at Follow The Money.  Instead of the "unique candidate" ID, their API now expects an "entity" ID.  Currently, this entity ID isn't available in the Open States legislator details.  But through an HTTP redirection, it's possible to obtain the entity ID if you know the legislator's unique candidate ID (nimsp_id) ... 
    
    GET  http://www.followthemoney.org/database/uniquecandidate.phtml?uc=7061

redirects to ....

    http://www.followthemoney.org/entity-details?eid=6453425

So can we just save this new entity ID into the legislator's nimsp_candidate_id or just replace the value of the nimsp_id with this entity ID? With the entity ID, we'll be able to query the FollowTheMoney API for the legislator's contributions:

    http://api.followthemoney.org/?APIKey=<NIMSP_API_KEY_HERE>&f-fc=2&mode=json&sod=0&gro=y%2Cc-r-ot&so=y&c-t-eid=6453425

**Comment by jamesturk** [comment]
We're going to need to revisit if we have a way to get these going forward, it was a huge amount of manual work in the past so most legislators don't have them.  If we're able to keep them this seems like a good way to update our existing set.  I've opened https://github.com/openstates/meta/issues/16 to track this, and I'll reach out to NIMSP to see if there's interest in working together on this.

**Comment by grgcombs** [comment]
They have a giant CSV file on GitHub (I can refresh my memory with specifics tomorrow). It maps between their candidate ID and other open projects (I think I remember seeing an Open States ID in one column). But it when I saw it, it was very out of date. I might have submitted a pull request with update to it a few weeks ago, but it saw no action either. But maybe they're maintaining something else internally. 

G

**Comment by jamesturk** [comment]
closing this one in favor of the meta issue
