### ISSUE TITLE
TX: Companion bills field is not being populated

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1362]
Note that this bill has a companion listed in the source file:
ftp://ftp.legis.state.tx.us/bills/85R/billhistory/senate_bills/SB00001_SB00099/SB%2014.xml

It's not being returned by the api:
https://openstates.org/api/v1/bills/TXB00049963/

I haven't found any bills where the companion field is being populated.

**Comment by jmcarp** [comment]
Done in #1378.
