### ISSUE TITLE
TX: Votes not being populated for current session

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1363]
As an example, SB 14 passed the Texas Senate last week with a lot of media coverage. The votes field is not being populated by the api:
https://openstates.org/api/v1/bills/TXB00049963/

**Comment by jmcarp** [comment]
I took a look at this, and the current vote scraper seems pretty brittle--some of the [regular expressions](https://github.com/openstates/openstates/blob/master/openstates/tx/votes.py#L115-L120) we're using fail to detect lots of votes in the current session. I'll try reworking those checks over the weekend, unless somebody else does it first. Also happy to pair on this if folks are interested.
