### ISSUE TITLE
MA: scraper is failing to pick up bill cosponsors

### ISSUE THREAD

**Issue by aholachek** [openstates/openstates#1366]
From what I understand of the MA scraper, [it relies on a "petitioners" link on the page for each bill to determine whether to visit the bill's cosponsors page.](https://github.com/openstates/openstates/blob/master/openstates/ma/bills.py#L142)

However, it appears that for whatever reason right now the petitioners link is missing on pages with bills that have cosponsors. 

As an example, check out [this page for bill S.D. 719](https://malegislature.gov/Bills/190/SD719): It has no petitioners link, but nevertheless [the cosponsors page](https://malegislature.gov/Bills/190/SD719/Cosponsor) has a long list of cosponsors.

I noticed this discrepancy when I was browsing the openstates.org search interface and noticed that it didn't show my state senator as co-sponsoring any bills for the current legislative session.

Thank you for maintaining this great service and sorry if this issue isn't helpful!

**Comment by jonConerly** [comment]
Taking a look, looks to be a bug on the 190th session pages causing this
