### ISSUE TITLE
AR: needs manual retirements

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1368]
State: AR

We got a report that AR needs retirements.

Example:
For AR - DISTRICT 32 You have listed:
Will Bond             32           Democratic         Senate (THIS IS CORRECT)
David Johnson   32           Democratic         Senate (THIS IS WRONG / OLD)
James J. Sorvillo                32           Republican          House (THIS IS CORRECT)
 
David Johnson is not in office.
 
Here is the current list:
http://www.arkleg.state.ar.us/assembly/2017/2017R/Pages/LegislatorSearchResults.aspx?member=&committee=All&chamber=

**Comment by jainamritanshu** [comment]
@jamesturk I would like to work on this issue. Can you help me proceed?

**Comment by jamesturk** [comment]
Issues w/ the 'manual' tag require admin access right now, it'd be better
to take a look at fixing a scraper.

a few decent issues:
https://github.com/openstates/openstates/issues/1380
https://github.com/openstates/openstates/issues/1344
https://github.com/openstates/openstates/issues/1438

**Comment by samtregar** [comment]
I've been thinking about doing some scripting to go through current scrapes and pull lists of people that aren't there but are coming back from the live API.  Then I'd go through that list and check that they're actually defeated / retired / in a better place.  Does that sound useful?  If so, what format would be most useful to get that info in?

**Comment by samtregar** [comment]
Here's a file of inactive legislators in AR.  I've written a script that compares the data returned by a scrape run with the data returned from the live API and flags mismatches.  I've spot-checked these and they all look correct to me.  Let me know if this is usable and I'll run it for more states.  If you want more/less/different data let me know. 
[inactive_ar.txt](https://github.com/openstates/openstates/files/823065/inactive_ar.txt)

**Comment by jamesturk** [comment]
thanks! I did a quick spot check & was able to bulk retire this set
