### ISSUE TITLE
NY: Not getting roll calls

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1384]
State: NY  (be sure to include in ticket title)

The NY Senate site has some floor vote breakdowns that we're not collecting - IE [S981](https://www.nysenate.gov/legislation/bills/2017/S981) - [Scraper output ](https://openstates.org/api/v1/bills/ny/2017-2018/S%20981/)

TODO: Does the API offer these for the house side?

**Comment by jmcarp** [comment]
Do you mean the floor vote at https://www.nysenate.gov/legislation/bills/2017/S981? I don't see it on http://legislation.nysenate.gov/api/3/bills/2017/S981. Should we file a ticket at https://github.com/nysenate/OpenLegislation? Grab the floor vote from the html?
