### ISSUE TITLE
MO: Vote action chamber resolution edge case

### ISSUE THREAD

**Issue by loandy** [openstates/openstates#1387]
Scraping vote actions within the bill scraper mostly resolves the correct chamber that originated the action, but sometimes the action listed will not explicitly state the chamber and the default chamber decided upon will be wrong.

For example, for [HCR 4](http://www.house.mo.gov/BillContent.aspx?bill=HCR4&year=2017&code=R&style=new), there are two action descriptions that don't identify the corresponding chamber:

```
- S 191 | Taken Up
- S 193 | Truly Agreed To and Finally Passed - AYES: 25 NOES: 2 PRESENT: 6
``` 

As such, when the scraper attempts to process these actions and can't find a specified chamber, it defaults to the House, as this is a House resolution. I've already begun modifications, but I wanted to pass the idea around: Are there improvements or caveats to falling back upon looking at the chamber of the journal as a second source before finally settling on a default? Should we even have a default when attempting to determine the chamber that originated an action?

**Comment by jamesturk** [comment]
This comes up in a few places IIRC... if there isn't a chamber we don't have much of a choice but to guess right now.  I think using the journal makes sense here, as for defaults, either the chamber of origination or do what I've seen some scrapers do & assume that an action w/o a chamber is in the same chamber as the preceding action, which makes some sense too.

**Comment by jamesturk** [comment]
@loandy is this still something that needs to be fixed?
