### ISSUE TITLE
MA: district names for lower house formatted differently in legislator, district

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1388]
The legislator API does not return OpenStates district IDs - it only provides district names.  So if one wants to associate the legislator with a district from the district API, one must use the state+chamber+name to match them up.

In the MA lower house, the legislator API provides district fields named using digits, e.g.:
```
3rd Hampden
14th Worcester
16th Middlesex
6th Worcester
12th Norfolk
9th Essex
7th Plymouth

```
but the district API has the digits spelled out, e.g.:
```
Eighteenth Suffolk
Eighteenth Worcester
Eighth Bristol
Eighth Essex
Eighth Hampden
Eighth Middlesex

```
making them very difficult to associate.

**Comment by jamesturk** [comment]
this is the same issue as #1258 - which definitely needs some attention
