### ISSUE TITLE
[AL,IN,MD,MS,MT,NJ,VA,WA] Legislators voted in current term, but are not returned by leg API search for current term

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1396]
These legislators are listed as having voted on bills in the current term, but aren't returned by the legislator search API when filtered for the current term.  All of the ones I've checked exist, but are inactive.  IMHO, they shouldn't be filtered out automatically.

|State|Legislators|
|-----|-----------|
|al	|ALL000078, ALL000082, ALL000132, ALL000136|
|in	|INL000064|
|md	|MDL000331, MDL000392, MDL000649, MDL000414, MDL000355, MDL000380|
|ms	|MSL000137, MSL000068, MSL000108, MSL000158, MSL000071, MSL000187|
|mt	|MTL000118, MTL000048, MTL000023|
|nj	|NJL000056, NJL000088|
|va	|VAL000165, VAL000124, VAL000084, VAL000048, VAL000180, VAL000236, VAL000184, VAL000231, VAL000186, VAL000176, VAL000123, VAL000131, VAL000003, VAL000015, VAL000019, VAL000232, VAL000018, VAL000233, VAL000027, VAL000032, VAL000033, VAL000039|
|wa	|WAL000134, WAL000166|

**Comment by jamesturk** [comment]
These legislator IDs have been merged, if you look at all_ids you'll see them.

The IDs remain valid as aliases, e.g..

https://openstates.org/api/v1/legislators/ALL000078/

**Comment by estaub** [comment]
@jamesturk Ah, sorry, thanks!

Would it make sense to change IDs to the merge target on votes and other references to the dead IDs at merge time?

**Comment by jamesturk** [comment]
In the new infrastructure I believe we do this since it is just a couple of SQL update statmeents, in the existing infrastructure it is fairly expensive so we don't.

**Comment by estaub** [comment]
This probably should be reopened.  Applying aliases accounted for only one of the 46 problem legislators above (one in Virginia).  To be specific, the API url 

https://openstates.org/api/v1/legislators/ALL000078/ (mentioned in James' response above)

has all_ids:  `[
    "ALL000078",
    "ALL000424",
    "ALL000209",
    "ALL000495"
  ]`.

But none of these are returned by the query:
https://openstates.org/api/v1/legislators/?state=al&term=2015-2018

I suspect something's filtering out inactives.  

Is [the documentation's definition of active](http://docs.openstates.org/en/latest/api/legislators.html#legislator-fields) correct?

> **active**  Boolean value indicating whether or not the legislator is currently in office.

In the case where there are multiple all_ids, what indicates which is the current one - the one that should be referenced?  Is "active" doing double duty for this purpose, and failing when the legislator becomes truly inactive?
