### ISSUE TITLE
Null legislator IDs in some votes in most states in the current term

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1397]
The following named legislators have no leg_id in at least some votes in the current term:

|State|Count|List|
|-----|-----|-----|
|al|5|Williams (JD), Williams (JW), Coleman-Evans, Coleman, Coleman-Madison|
|ar|5|Drown, M. Gray, Warren, Mr. Speaker, M.J. Gray|
|ca|2|Gonzalez, Gonzalez Fletcher|
|co|29|Humenik, Neville T., President, Williams A., Williams D., Becker J., Coram, Donovan, Fenberg, Fields, Garcia, Jones, Marble, Scott, Baumgardner, Sonnenberg, Cooke, Bush, Winkle, Neville P., Tharp, Becker K., Michaelson, Speaker, Jahn, Kerr, Priola, Smallwood, Tate|
|ct|10|Y, KEVIN KELLY, MARILYN MOORE, PAUL DOYLE, GARY WINFIELD, LEONARD FASANO, HEATHER BOND, TIM LARSON, GAYLE SLOSSBERG, N|
|dc|3|Vincent Gray, Trayon White, Robert White|
|ga|236|ALBERS, 56TH, ANDERSON, 24TH, BEACH, 21ST, BLACK, 8TH, BRASS, 28TH, BURKE, 11TH, COWSERT, 46TH, DUGAN, 30TH, GINN, 47TH, GOOCH, 51ST, HARBIN, 16TH, HARPER, 7TH, HEATH, 31ST, HILL, 4TH, HILL, 6TH, HILL, 32ND, HUFSTETLER, 52ND, JEFFARES, 17TH, JONES, 25TH, KENNEDY, 18TH, KIRK, 13TH, LIGON, JR., 3RD, MARTIN IV, 9TH, MCKOON, 29TH, MILLAR, 40TH, MILLER, 49TH, MULLIS, 53RD, SHAFER, 48TH, STONE, 23RD, THOMPSON, 14TH, TILLERY, 19TH, TIPPINS, 37TH, UNTERMAN, 45TH, WALKER III, 20TH, WATSON, 1ST, WILKINSON, 50TH, WILLIAMS, 27TH, ANDERSON, 43RD, BUTLER, 55TH, DAVENPORT, 44TH, FORT, 39TH, HARBISON, 15TH, HENSON, 41ST, JACKSON, 2ND, JAMES, 35TH, JONES, 10TH, JONES II, 22ND, LUCAS, 26TH, ORROCK, 36TH, PARENT, 42ND, RHETT, 33RD, SEAY, 34TH, SIMS, 12TH, TATE, 38TH, THOMPSON, 5TH, VACANT, ABRAMS, 89TH, ALEXANDER, 66TH, BALLINGER, 23RD, BARR, 103RD, BATTLES, 15TH, BAZEMORE, 63RD, BEASLEY-TEAGUE, 65TH, BELTON, 112TH, BENNETT, 94TH, BENTLEY, 139TH, BENTON, 31ST, BESKIN, 54TH, BEVERLY, 143RD, BLACKMON, 146TH, BODDIE, 62ND, BONNER, 72ND, BROADRICK, 4TH, BROCKWAY, 102ND, BRUCE, 61ST, BUCKNER, 137TH, BURNOUGH, 77TH, BURNS, 159TH, CALDWELL, 20TH, CALDWELL, JR., 131ST, CANNON, 58TH, CANTRELL, 22ND, CARSON, 46TH, CARTER, 92ND, CARTER, 175TH, CASAS, 107TH, CHANDLER, 105TH, CLARK, 98TH, CLARK, 147TH, COLEMAN, 97TH, COLLINS, 68TH, COOMER, 14TH, COOPER, 43RD, CORBETT, 174TH, COX, 108TH, DEFFENBAUGH, 1ST, DEMPSEY, 13TH, DICKERSON, 113TH, DICKEY, 140TH, DOLLAR, 45TH, DOUGLAS, 78TH, DRENNER, 85TH, DREYER, 59TH, DUBNIK, 29TH, DUKES, 154TH, DUNAHOO, 30TH, DUNCAN, 26TH, EALUM, 153RD, EFSTRATION, 104TH, EHRHART, 36TH, ENGLAND, 116TH, EPPS, 144TH, EVANS, 42ND, FLEMING, 121ST, FRAZIER, 126TH, FRYE, 118TH, GARDNER, 57TH, GASAWAY, 28TH, GILLIARD, 162ND, GILLIGAN, 24TH, GLANTON, 75TH, GOLICK, 40TH, GORDON, 163RD, GRAVLEY, 67TH, GREENE, 151ST, HANSON, 80TH, HARDEN, 148TH, HARRELL, 106TH, HATCHETT, 150TH, HAWKINS, 27TH, HENSON, 86TH, HILL, 3RD, HILTON, 95TH, HITCHENS, 161ST, HOGAN, 179TH, HOLCOMB, 81ST, HOLMES, 129TH, HOUSTON, 170TH, HOWARD, 124TH, HUGLEY, 136TH, JACKSON, 64TH, JACKSON, 128TH, JASPERSE, 11TH, JONES, 47TH, JONES, 53RD, JONES, 91ST, JONES, 167TH, KELLEY, 16TH, KENDRICK, 93RD, KIRBY, 114TH, KNIGHT, 130TH, LARICCIA, 169TH, LOPEZ, 99TH, LOTT, 122ND, LUMSDEN, 12TH, MARIN, 96TH, MARTIN, 49TH, MATHIAK, 73RD, MAXWELL, 17TH, MCCALL, 33RD, MCCLAIN, 100TH, MCGOWAN, 138TH, MEADOWS, 5TH, METZE, 55TH, MITCHELL, 88TH, MORRIS, 156TH, NELSON, 125TH, NEWTON, 123RD, NIMMER, 178TH, NIX, 69TH, OLIVER, 82ND, PARIS, 142ND, PARK, 101ST, PARRISH, 158TH, PARSONS, 44TH, PEAKE, 141ST, PETREA, 166TH, PEZOLD, 133RD, PIRKLE, 155TH, POWELL, 32ND, POWELL, 171ST, PRICE, 48TH, PRINCE, 127TH, PRUETT, 149TH, QUICK, 117TH, RAFFENSPERGER, 50TH, RAKESTRAW, 19TH, REEVES, 34TH, RHODES, 120TH, RIDLEY, 6TH, ROGERS, 10TH, RUTLEDGE, 109TH, RYNDERS, 152ND, SCOTT, 76TH, SETZLER, 35TH, SHANNON, 84TH, SHARPER, 177TH, SHAW, 176TH, SILCOX, 52ND, SMITH, 41ST, SMITH, 70TH, SMITH, 134TH, SMYRE, 135TH, SPENCER, 180TH, STEPHENS, 164TH, STEPHENS, 165TH, STOVALL, 74TH, STRICKLAND, 111TH, TANKERSLEY, 160TH, TANNER, 9TH, TARVIN, 2ND, TAYLOR, 79TH, TAYLOR, 173RD, THOMAS, 39TH, THOMAS, 56TH, TRAMMELL, 132ND, TURNER, 21ST, WAITES, 60TH, WATSON, 172ND, WELCH, 110TH, WERKHEISER, 157TH, WILKERSON, 38TH, WILLARD, 51ST, WILLIAMS, 87TH, WILLIAMS, 119TH, WILLIAMS, 145TH, WILLIAMS, 168TH, WILLIAMSON, 115TH, GURTLER, 8TH, COOKE, 18TH, MOSBY, 83RD, RALSTON, 7TH, STEPHENSON, 90TH, STOVER, 71ST, TEASLEY, 37TH, PAYNE , 54TH|
|hi|23|San Buenaventura, Dela Cruz,  Ward; , Ruderman ; ,  Matsumoto; ,  Thielen; ,  Kong; , Gates; ,  Onishi; , Wakai ; ,  Tupola; , Tupola; , Kidani ; , San Buenaventura; , K. Rhoads ; ,  LoPresti; ,  San Buenaventura; ,  Creagan; , Taniguchi ; , Riviere ; ,  Kobayashi; , Thielen; , LoPresti; |
|ia|1|Speaker|
|id|29|– Agenbroad, Den Hartog, – None, – Amador, Mendive(Mendive), Smith(Nye), Vander Woude, – Cheatham, Bock(Burgoyne), – Buckner-Webb, – Siddoway, – Foreman, Rubel(Green), – Barbieri, – DeMordaunt, – Heider, – Chew, – Malek, – Hagedorn, – Armstrong, – Anthon, Horman(Reed), – Davis, – Boyle, – Chaney, – Giddings, – Shepherd, Smith(Lacey), – Gestrin|
|il|12|Cullerton, Davis,William, Burke,Kelly, Harris,Gregory, Mitchell,Christian, Conyears, Burke,Daniel, Harris,David, Mitchell,Bill, Wheeler,Barbara, Wheeler,Keith, Clayborne Jr., James F|
|in|1|Mr. Speaker|
|la|110|Mr. President, Total -- 35, Total -- 0, Total -- 4, Total -- 34, Total -- 5, Amedee, Morris, Jim, Morris, Jay, Total -- 19, Mr. Speaker, Total -- 78, Total -- 8, Total -- 49, Total -- 46, Total -- 10, Total -- 37, Total -- 2, Total -- 32, Total -- 7, Total -- 31, Total -- 65, Total -- 9, Total -- 38, Total -- 1, Total -- 98, Total -- 60, Total -- 14, Total -- 85, Total -- 6, Total -- 79, Total -- 18, Total -- 80, Total -- 39, Total -- 27, Total -- 12, Total -- 96, Total -- 102, Total -- 3, Total -- 55, Total -- 43, Total -- 48, Total -- 11, Total -- 13, Total -- 40, Total -- 67, Total -- 28, Total -- 99, Total -- 103, Total -- 95, Total -- 92, Total -- 16, Total -- 22, Total -- 17, Total -- 29, Total -- 97, Total -- 30, Total -- 33, Total -- 23, Total -- 94, Total -- 51, Total -- 15, Total -- 24, Total -- 69, Total -- 44, Total -- 58, Total -- 74, Total -- 26, Total -- 101, Total -- 36, Total -- 90, Total -- 54, Total -- 47, Total -- 57, Total -- 41, Total -- 100, Total -- 82, Total -- 87, Total -- 91, Total -- 75, Total -- 62, Total -- 45, Total -- 81, Total -- 61, Total -- 72, Total -- 73, Total -- 76, Total -- 25, Total -- 53, Total -- 86, Total -- 66, Total -- 56, Total -- 83, Total -- 89, Total -- 68, Total -- 84, Total -- 21, Total -- 93, Total -- 59, Total -- 70, Total -- 20, Total -- 88, Total -- 50, Total -- 71, Total -- 42, Total -- 63, Total -- 77, Total -- 64, Total -- 52, Jordan|
|md|128|Mr. President, Manno, Speaker Busch, Proctor, Fisher*, Saab*, Glass*, Malone*, Kittleman*, Metzgar*, Atterbeary*, Ebersole*, Pendergrass*, Reilly*, McMillan*, Gutierrez*, Frush*, Mautz*, Howard, S.*, McConkey*, Healey*, Long*, Walker*, Jackson*, Rey*, Wivell*, Grammer*, Hornberger*, Sydnor*, Kelly*, Parrott*, Krebs*, Adams*, Simonaire*, Carey*, McKay*, Folden*, Carozza*, Morhaim*, McComas*, Hill*, Arentz*, Jalisi*, Aumann*, Flanagan*, West*, Cluster*, Kipke*, Afzali*, O'Donnell*, Rose*, Ciliberti*, Bromwell*, Miele*, Frick*, Luedtke*, Miller, W.*, Lafferty*, McDonough*, Beidle*, Ghrist*, Szeliga*, Vogt*, Barve*, Rosenberg*, Sophocleus*, Waldstreicher*, Kaiser*, Jacobs*, Cassilly*, Morgan*, Shoemaker*, Wilson, B.*, Impallaria*, Beitzel*, Washington, M.*, Morales*, Smith*, Barron*, Robinson, S.*, Turner*, Washington, A.*, Knotts*, Conaway*, Chang*, Gilchrist*, Lisanti*, Vallario*, Fennell*, Buckel*, Anderton*, Sample-Hughes*, Speaker Busch*, Cullison*, Davis*, McIntosh*, Jones*, Barnes, B.*, Miller, A.*, Stein*, Korman*, Krimm*, Lam*, Hammen*, Lierman*, Pena-Melnyk*, Hayes*, Platt*, Carr*, Haynes*, Hettleman*, Reznik*, Young, K.*, Robinson, B.*, Young, P.*, Carter*, Zucker, Howard, C.*, Valentino-Smith*, Tarlau*, Moon*, Branch*, Brooks*, Patterson*, Angel*, McCray*, Cluster, Robinson|
|me|186|ACKLEY of Monmouth, ALLEY of Beals, AUSTIN of Skowhegan, BABBIDGE of Kennebunk, BAILEY of Saco, BATES of Westbrook, BATTLE of South Portland, BEEBE-CENTER of Rockland, BERRY of Bowdoinham, BICKFORD of Auburn, BLACK of Wilton, BLUME of York, BROOKS of Lewiston, BRYANT of Windham, CARDONE of Bangor, CASÁS of Rockport, CHACE of Durham, CHAPMAN of Brooksville, COLLINGS of Portland, COOPER of Yarmouth, DAUGHTRY of Brunswick, DeCHANT of Bath, DENNO of Cumberland, DEVIN of Newcastle, DILLINGHAM of Oxford, DOORE of Augusta, DUCHESNE of Hudson, DUNPHY of Old Town, FARNSWORTH of Portland, FARRIN of Norridgewock, FAY of Raymond, FECTEAU of Biddeford, FOLEY of Wells, FREDETTE of Newport, FREY of Bangor, FULLER of Lewiston, GATTINE of Westbrook, GERRISH of Lebanon, GIDEON of Freeport, GILLWAY of Searsport, GOLDEN of Lewiston, GRIGNON of Athens, HAMANN of South Portland, HANDY of Lewiston, HANINGTON of Lincoln, HARLOW of Portland, HARRINGTON of Sanford, HARVELL of Farmington, HEAD of Bethel, HERBIG of Belfast, HERRICK of Paris, HICKMAN of Winthrop, HIGGINS of Dover-Foxcroft, HOGAN of Old Orchard Beach, HUBBELL of Bar Harbor, HYMANSON of York, JORGENSEN of Portland, KINNEY of Limington, KINNEY of Knox, KORNFIELD of Bangor, KUMIEGA of Deer Isle, LAWRENCE of South Berwick, LONGSTAFF of Waterville, LUCHINI of Ellsworth, MADIGAN of Waterville, MADIGAN of Rumford, MALABY of Hancock, MAREAN of Hollis, MARTIN of Sinclair, MASTRACCIO of Sanford, McCREA of Fort Fairfield, McCREIGHT of Harpswell, McLEAN of Gorham, MELARAGNO of Auburn, MONAGHAN of Cape Elizabeth, MOONEN of Portland, NADEAU of Winslow, O'NEIL of Saco, ORDWAY of Standish, PARKER of South Berwick, PERKINS of Oakland, PERRY of Calais, PICKETT of Dixfield, PIERCE of Falmouth, PRESCOTT of Waterboro, RECKITT of South Portland, RILEY of Jay, RYKERSON of Kittery, SAMPSON of Alfred, SANBORN of Portland, SANDERSON of Chelsea, SCHNECK of Bangor, SEAVEY of Kennebunkport, SHEATS of Auburn, SIROCKI of Scarborough, SPEAR of South Thomaston, STANLEY of Medway, STEARNS of Guilford, STETKIS of Canaan, STROM of Pittsfield, SUTTON of Warren, SYLVESTER of Portland, TALBOT ROSS of Portland, TEPLER of Topsham, TERRY of Gorham, THERIAULT of China, TIMBERLAKE of Turner, TIPPING of Orono, TUCKER of Brunswick, TUELL of East Machias, WARREN of Hallowell, WHITE of Washburn, WINSOR of Norway, ZEIGLER of Montville, AUSTIN of Gray, BRADSTREET of Vassalboro, CAMPBELL of Orrington, CEBRA of Naples, COREY of Windham, CRAIG of Brewer, GINZLER of Bridgton, HANLEY of Pittston, HILLIARD of Belgrade, JOHANSEN of Monticello, LOCKMAN of Amherst, LYFORD of Eddington, MASON of Lisbon, McELWEE of Caribou, O'CONNOR of Berwick, PARRY of Arundel, PICCHIOTTI of Fairfield, PIERCE of Dresden, POULIOT of Augusta, SHERMAN of Hodgdon, SIMMONS of Waldoboro, SKOLFIELD of Weld, TURNER of Burlington, VACHON of Scarborough, WADSWORTH of Hiram, WALLACE of Dexter, WARD of Dedham, WOOD of Greene, ESPLING of New Gloucester, GRANT of Gardiner, GROHMAN of Biddeford, GUERIN of Glenburn, HAGGAN of Hampden, HAWKE of Boothbay Harbor, MARTIN of Eagle Lake, REED of Carmel, STEWART of Presque Isle, BELLOWS of Kennebec, BREEN of Cumberland, CARPENTER of Aroostook, CARSON of Cumberland, CHENETTE of York, CHIPMAN of Cumberland, COLLINS of York, CUSHING of Penobscot, CYRWAY of Kennebec, DAVIS of Piscataquis, DESCHAMBAULT of York, DIAMOND of Cumberland, DILL of Penobscot, DOW of Lincoln, GRATWICK of Penobscot, HAMPER of Oxford, HILL of York, JACKSON of Aroostook, KATZ of Kennebec, KEIM of Oxford, LANGLEY of Hancock, LIBBY of Androscoggin, MAKER of Washington, MASON of Androscoggin, MILLETT of Cumberland, MIRAMANT of Knox, ROSEN of Hancock, SAVIELLO of Franklin, THIBODEAU of Waldo, VITELLI of Sagadahoc, VOLK of Cumberland, WHITTEMORE of Somerset, WOODSOME of York, BRAKEY of Androscoggin, DION of Cumberland|
|mi|1|O’Brien|
|mn|1|Maye Quade|
|ms|24|Bell (65th), Bell (21st), Evans (91st), Evans (45th), Huddleston (15th), Huddleston (30th), Johnson (87th), Johnson (94th), Rogers (14th), Rogers (61st), Mr. Speaker, Jackson G. (15th), Jackson R. (11th), Jackson S. (32nd), Simmons D. T. (12th), Simmons W. (13th), DeBar, Williams- Barnes, Simmons D, T. (12th), __________       Blackwell, Gibbs (72nd), Gibbs (36th), Turner- Ford|
|mt|23|Moore, Frederick (Eric), Tempel, Russel (Russ), Kary, Douglas (Doug), MacDonald, Margaret  (Margie), McClafferty, Edith (Edie), Moe, Mary, Salomon, Daniel R., Hamlett, Bradley, Hill Smith, Ellie, Eck, Jennifer, Fitzgerald, Ross H., MacDonald, Margaret (Margie), Loge, Denley M., Lenz, Dennis R., Shaw, Ray L., Welborn, Jeffrey W., Sesso, Jon C., Morigeau, Shane A., Kipp, George G., Small, Jason D., Holmlund, Kenneth L., Jones, Donald W., Knokey, Jon A.|
|nc|1|Brenden Jones|
|nd|6|Jones, Roers Jones, Schreiber- Beck, Speaker Bellew, Davison SB 2061, SB 2062, SB 2063, SB 2064, SB 2065, SB 2066, SB 2067, SB 2068, SB 2069, SB 2070, SB 2071, SB 2072, SB 2073, SB 2074, SB 2075, SB 2076, SB 2077, SB 2078,, Trottier HB 1061, HB 1062, HB 1063, HB 1064, HB 1065, HB 1066, HB 1067, HB 1068, HB 1069, HB 1070, HB 1071, HB 1072, HB 1073, HB 1074, HB 1075, HB 1076, HB 1077, HB 1078,|
|nj|1|Diegnan, Patrick J.|
|ny|5|Fredrick J Akshar II, Thomas Croci, Terrence P. Murphy, Robert Ortt, Susan Serino|
|or|34|Manning Jr, Baertschiger Jr, Monnes Anderson, Steiner Hayward, Alonso Leon, Smith Warner, Speaker Kotek, Smith D, Smith G, Beyer, Burdick, DeBoer, Dembrow, Devlin, Ferrioli, Frederick, Gelser, Girod, Hansell, Hass, Knopp, Kruse, Linthicum, Monroe, Prozanski, Riley, Roblan, Taylor, Thatcher, Winters, President Courtney, Boquist, Olsen, Thomsen|
|pa|3|CULVER, EVANS, KRUEGER|
|ri|74|Mr. Speaker, Ranglin-Vassell, Abney, Ackerman, Ajello, Amore, Barros, Bennett, Blazejewski, Canario, Carson, Casey, Casimiro, Chippendale, Costantino, Coughlin, Craven, Cunha, Donovan, Edwards, Fellela, Filippi, Giarrusso, Handy, Hearn, Hull, Jacquard, Johnston, Kazarian, Keable, Kennedy, Knight, Lima, Maldonado, Marshall, Marszalkowski, McEntee, McKiernan, McLaughlin, McNamara, Mendonca, Messier, Morin, Nardolillo, Newberry, Nunes, O'Brien, O'Grady, Perez, Quattrocchi, Ruggiero, Serpa, Shanley, Shekarchi, Slater, Solomon, Tanzi, Tobon, Ucci, Vella-Wilkinson, Walsh, Williams, Winfield, Azzinaro, Corvese, Phillips, Price, Roberts, Almeida, Diaz, Lancia, Regunberg, Miller, Madam President|
|sc|43|Campbell, Paul G., Jr., Campsen, George E., III, Leatherman, Hugh K., Sr., Peeler, Harvey S., Jr., Verdin, Daniel B., III, Young, Tom, Jr., Matthews, John W., Jr., McElveen, J. Thomas, III, Scott, John L., Jr., Atkinson, Frank, Bales, Jimmy C., Ed.D., Bennett, Linda, Bradley, Jeffrey A., Burns, James Mikell, Caskey, Micajah P., IV, Cogswell, William Scott, Jr., Cole, J. Derham, Jr., Duckworth, Gregory D., Finlay, Kirkman, III, Forrest, Cally R., Henegan, Patricia Moore, Jefferson, Joseph H., Jr., Jordan, Wallace H., Jr., Mack, David J., III, McCoy, Peter M., Jr., Ridgeway, Robert L., III, Rivers, Samuel, Jr., Sandifer, William E., III, Smith, James E., Jr., Tallon, Edward R., Sr., West, John Taliaferro, IV, Wheeler, William W., III, Yow, Richard L., Arrington, Katherine E., Johnson, Jeffrey E., Martin, Richard, Rivers, Michael F., Sr., Delleney, F. Gregory, Jr., Govan, Jerry N., Jr., McCravy, John R., III, Mitchell, Harold, Jr., Murphy, Chris, Smith, G. Murrell, Jr.|
|sd|1|Jensen (Kevin)|
|ut|82|Adams, J. S., Buxton, D. G., Cutler, B. R., Maloy, A.C., Moss, C., Webb, R. C., Hemmert, D., Ipson, D., Mayne, K., Millner, A., Dunnigan, J., Froerer, G., Gardiner, A., Hawkes, T., McKell, M., Peterson, J., Roberts, M., Schultz, M., Stanard, J., Wheatley, M., Wilson, B., Dayton, M., Hinkins, D., Iwamoto, J., Shiozawa, B., Vickers, E., Christofferson, K., Fawson, J., Hemingway, L., Kennedy, M., Kwan, K., Moss, J., Potter, V., Westwood, J., Chavez-Houck, R., Daw, B., Hall, C., Hollins, S., Miles, K., Ray, P., Redd, E., Spendlove, R., Thurston, N., Hutchings, E., Perry, L., Romero, A., Weight, E., Winder, M., Escamilla, L., Thatcher, D., Knotwell, J., Knudson, P., Okerlund, R., Weiler, T., Dabakis, J., Fillmore, L., Coleman, K., Gibson, F., Last, B., McCay, D., Owens, D., Peterson, V., Poulson, M., Harper, W., Henderson, D., Stephenson, H., Duckworth, S., Eliason, S., Ward, R., Briscoe, J., Chew, S., Handy, S., Sagers, D., Sandall, S., Stratton, K., Watkins, C., Wilde, L., Arent, P., Brooks, W., Nelson, M., Sanpei, D., Stevenson, J.|
|va|7|Miller, Marshall, R.G., Marshall, D.W., Mr. Speaker, Howell, A.T., Lewis, Northam|
|vt|5|Christie, Hooper, Smith, Sullivan, Troiano|
|wa|1|Steele|
|wi|1|SPEAKER|
|wy|5|Bebout Pres, Bourchard, Zwonitzer, Brown, Landen B|

This is a superset of https://github.com/openstates/openstates/issues/1360 .

In case you're wondering... I intend to continue to drop off first copies of reports on various data issues as issues here.  Going forward, I hope to set up an online monitor on issues that continue to show up.

**Comment by jamesturk** [comment]
Null legislator IDs indicate that we haven't been able to reconcile a vote's text name with legislators yet.  As you can see, some of these indicate bugs (and can be filed as such, see ND, MD, LA) and some are simply names that we haven't yet been able to match due to formatting differences (see SC, ME).

Appreciate you trying to bring these to the forefront, if you could give me a list of the other checkers you intend to write so I can let you know if they're duplicative of our existing data quality tools.

**Comment by estaub** [comment]
@jamesturk Sorry, I don't have a list.  I'm not planning this ahead, just writing validators in the process of writing other code using the API.  I wrote one sandbox version a few months ago, using MongoDB, and had so many discovered-too-late data integrity problems that I restarted, using Postgres, with one schema for raw API input and another for cleaned data.  So I need to write these checkers regardless to know what I can trust where, and to patch things up locally where appropriate.  I'll be sharing this stuff (Typescript on Node) on Github when it's a bit more well-done.

**Comment by mshenfield** [comment]
The referencing pull request tackles a few basic data quality issues with vote name scraping.  There are some others that can likely be tackled with one or two line fixes to state scraper:

- [ ] _id_ - leading "–". Note this is a unicode character, not the ascii dash
- [ ] _id_ - trailing "(\<name\>)"
- [ ] _il_ - "\<last_name\>,\<first_name\>" separator is [expected to be ", "](http://github.com/openstates/billy/blob/63d4311dac7545cd8e258a966212e803ce7dbbbe/billy/importers/names.py#L56).
- [ ] _md_ - trailing "*"
- [ ] _me_ - trailing "of \<district\>"
- [ ] _ms_ - trailing "(\<district\>)"
- [ ] _mt_ - trailing "(\<name\>)"
- [ ] nd - saving districts as names

This list skips any state where the vote name might require a manual update to match, or that look like they might require a change to the billy `NameMatcher`.

**Comment by mshenfield** [comment]
Added issues for all the one-off fixes.
