### ISSUE TITLE
CA representatives data is old

### ISSUE THREAD

**Issue by mhedblom** [openstates/openstates#1398]
I notice some of the representative data no longer matches what is on the ca.gov websites. Specifically, some of the representative's links to photos are incorrect.

When and how often is the representative information rescraped?

**Comment by jamesturk** [comment]
data is rescraped nightly, but sometimes we manually override photos/etc. when the source isn't reliable, can you point out some examples and we'll look at what needs to be done?

**Comment by mhedblom** [comment]
The one I noticed (because it is a broken link) is the 'photo_url' from this representative:

https://openstates.org/api/v1/legislators/?state=ca&chamber=upper&district=12

"photo_url": "http://cssrc.us/lib/uploads/12/Canella_7221.jpg",

When I look at this official site:

http://senate.ca.gov/senators

I can see this image.

http://senate.ca.gov/sites/senate.ca.gov/files/senator_photos/cannella-anthony.jpg

I'm guessing the scrapper is looking at his "official home page" for the image, which is on 'cssrc.us', not 'senate.ca.gov'.

**Comment by mshenfield** [comment]
The scraper is getting the correct `photo_url` for legislators. For example, here is the scraped `photo_url` for Cannella running locally:

_http://senate.ca.gov/sites/senate.ca.gov/files/senator_photos/cannella-anthony.jpg_
![Anthony Cannella](http://senate.ca.gov/sites/senate.ca.gov/files/senator_photos/cannella-anthony.jpg)

The most likely explanation is that the `photo_url` field for this and other CA legislators have been locked, and will need [to be unlocked](http://github.com/openstates/openstates/blob/4c468f032928414c16f9b0ffaa4cbeda737c3e28/scripts/unlock_bad_photos.py) in production for these legislators. (@jamesturk)
