### ISSUE TITLE
[Feature Request] Email Subscriptions

### ISSUE THREAD

**Issue by johnnyman727** [openstates/openstates#1401]
Hi OpenStates developers! I love what you guys have built so far. Very useful.

I was wondering if email subscriptions were on the roadmap or if that's a possibility. I've looked over the website and done a cursery search through the issues and didn't see any relevant existing conversation about this. I use govtrack.us to send me email digests of all new bills and like to request further updates on bills that matter to me. I would like to be able to do the same for state legislation.

I'd love to learn more and even contribute if it's a feasible feature.

**Comment by jamesturk** [comment]
Hey,

This is definitely on our roadmap (you can read more here: https://blog.openstates.org/post/whats-next-2017/)

I've opened an issue for it here just now, feel free to provide feedback here: https://github.com/openstates/meta/issues/18  

(going to close this one as we try to keep this repo to data quality issues)
