### ISSUE TITLE
VT upper + lower: missing legislator phone numbers

### ISSUE THREAD

**Issue by tomdionesotes** [openstates/openstates#1403]
Contact info for members from both chambers can be found here: http://www.leg.state.vt.us/legdir/memberdatatable.cfm?session=2018

**Comment by mshenfield** [comment]
Hey! In this case the phone numbers are included in the "District Office" entry instead of "Capitol Office". Search for "phone" in https://openstates.org/api/v1/legislators/VTL000034/.

Relevant snippet (2nd entry in "offices"):
```
{"fax": null, "name": "District Office", "phone": "802-223-5350", "address": "P.O. Box 123\nCalais, VT 05648", "type": "district", "email": "janetancel@gmail.com"}
```

**Comment by tomdionesotes** [comment]
Oops, looks like on our end we were overwriting valid district office phone numbers with the null capitol office phone numbers: https://gyazo.com/f5f1a1e338c9f06e55135dfffa43ff65

Closing.
