### ISSUE TITLE
Document testing strategy

### ISSUE THREAD

**Issue by jmcarp** [openstates/openstates#1405]
I just had a helpful conversation with @jamesturk @mileswwatkins @showerst in slack around https://openstates.slack.com/archives/general/p1487719625000661, but for wider visibility we should probably document when (if at all) to write tests for scrapers, and what (if anything) to do when existing tests fail.

**Comment by jamesturk** [comment]
I wrote up a draft of what our historical thinking has been here: http://docs.openstates.org/en/latest/policies/testing.html, definitely open to take suggested edits and use this as a jumping-off point to have further discussion.

**Comment by jmcarp** [comment]
Thanks!
