### ISSUE TITLE
TX: No bills updated since Feb 8th

### ISSUE THREAD

**Issue by richardm** [openstates/openstates#1412]
If I get bills updated since Feb 8th, I get a bunch:
https://openstates.org/api/v1/bills/?state=tx&search_window=session&fields=bill_id&updated_since=2017-02-08

If I do Feb 9th or any date after, I get none:
https://openstates.org/api/v1/bills/?state=tx&search_window=session&fields=bill_id&updated_since=2017-02-09

The ftp date modified time shows files updated as recently as today:
ftp://ftp.legis.state.tx.us/bills/85R/billhistory/house_bills/

Is the crawler still running?

**Comment by richardm** [comment]
This is a pretty big issue not being able to get any bill updates for over 2 weeks. Any progress?

**Comment by jamesturk** [comment]
there was a hiccup w/ some badly broken HTML, I just pushed a workaround and I'll be kicking off a run tonight, hopefully (if nothing else is broken) we'll have a complete run again by tomorrow

**Comment by grgcombs** [comment]
It's alive!  Bills (and events) are working for me now. Thanks!

**Comment by richardm** [comment]
Awesome! Thanks!
