### ISSUE TITLE
MO: Some Bills missing

### ISSUE THREAD

**Issue by Wizofgoz** [openstates/openstates#1427]
I noticed that at least HB 1 - HB 25 are missing from the response:

https://openstates.org/api/v1//bills/?state=mo&apikey=xxxxxxxx&search_window=term

vs

http://house.missouri.gov/Bill.aspx?bill=HB1&year=2017&code=R

**Comment by jamesturk** [comment]
it looks like the scraper is skipping bills w/ blank titles... which seems to be bills 1-18, any idea what is up w/ these?  I think pre-session we assumed they'd be fixed, but we might just have to scrape them w/ 'blank title' or something ugly set

**Comment by jamesturk** [comment]
looks like these are some sort of placeholder appropriations bill 

http://house.mo.gov/budget.aspx

I'll probably special case these so that we collect them w/ 'Appropriations Bill' instead of skipping them
