### ISSUE TITLE
MT: committee scraper needs update for 2017

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1451]
State: MT

might be an easy one, needs committee URL updated & to be tested w/ new page

**Comment by jamesthechamp** [comment]
hey, 
for 2017 url for committees i found were 
house
http://leg.mt.gov/content/Committees/Session/2017-house-committees.pdf
senate
http://leg.mt.gov/content/Committees/Session/2017-senate-committees.pdf
i had send pr https://github.com/openstates/openstates/pull/1465 with this urls.
please have a look at it

**Comment by pmathur5k10** [comment]
Is this issue closed or shall I look into this ??
