### ISSUE TITLE
TX: Merging of Two Legislators Names

### ISSUE THREAD

**Issue by bsalinas** [openstates/openstates#1463]
It seems that, on the production app, the names of Senator Eddie Lucio Jr and Representative Eddie Lucio III are getting merged somehow.

This is for Sen. Eddie Lucio Jr. His `full_name` is showing up as `Eddie Lucio III`
From: openstates.org/api/v1/legislators/TXL000198
(Note I cut out a lot of information from the response to shorten it)
```
{
  "last_name": "Lucio",
  "updated_at": "2017-03-05 07:18:28",
  "sources": [
    {
      "url": "http://www.senate.texas.gov/directory.php"
    },
    {
      "url": "http://www.senate.texas.gov/member.php?d=27"
    }
  ],
  "nimsp_candidate_id": "112009",
  "full_name": "Eddie Lucio III",
  "district": "27",
  "id": "TXL000198",
  "state": "tx",
  "votesmart_id": "56543",
  "party": "Democrat",
  "first_name": "Eduardo A. (Eddie)",
  "all_ids": [
    "TXL000198",
    "TXL000016",
    "TXL000303",
    "TXL000121",
    "TXL000546",
    "TXL000700"
  ],
  "leg_id": "TXL000198",
  "suffixes": "Jr."
}
```

For Rep. Eddie Lucio III, his `full_name` is showing up correctly as `Lucio III, Eddie`
`openstates.org/api/v1/legislators/TXL000717`
```{
  "last_name": "Lucio",
  "updated_at": "2017-03-05 07:18:28",
  "sources": [
    {
      "url": "http://www.house.state.tx.us/members/member-page/?district=38"
    }
  ],
  "full_name": "Lucio III, Eddie",
  "id": "TXL000717",
  "first_name": "Eddie",
  "middle_name": "",
  "district": "38",
  "state": "tx",
  "party": "Democratic",
  "all_ids": [
    "TXL000717"
  ],
  "leg_id": "TXL000717",
  "active": true,
  "photo_url": "http://www.house.state.tx.us/photos/members/3610.jpg",
  "roles": [
    {
      "term": "85",
      "end_date": null,
      "district": "38",
      "chamber": "lower",
      "state": "tx",
      "party": "Democratic",
      "type": "member",
      "start_date": null
    }
  ],
  "url": "http://www.house.state.tx.us/members/member-page/?district=38",
  "created_at": "2017-01-30 05:42:49",
  "chamber": "lower",
  "offices": [
    {
      "fax": "512-463-0660",
      "name": "Capitol Address",
      "phone": "512-463-0606",
      "address": "Room GN.8\nP.O. Box 2910\nAustin, TX 78768",
      "type": "capitol",
      "email": null
    },
    {
      "fax": "956-542-2889",
      "name": "District Address",
      "phone": "956-542-2800",
      "address": "1805 E Ruben M Torres Blvd. Ste. B-27\nBrownsville, TX 78521",
      "type": "district",
      "email": null
    }
  ],
  "suffixes": "III"
}
```

I pulled the latest version of the repo and ran the scraper for the TX Legislators and got the correct results (Sen Eddie Lucio, Jr shows `first_name` of `Eduardo A. (Eddie) Lucio, Jr.`) when I look in the `data/tx/legislators` folder.
I also checked in my local mongodb and the correct information made it into the database.

I'm new here, so I'm not sure if this is expected (and will fix itself when the scrapers run again) or if something needs to be done to fix it.

**Comment by jamesturk** [comment]
oops, yeah these father/son pairs can cause some trouble

I believe I've corrected their full names, let me know if it looks good now

**Comment by bsalinas** [comment]
It looks like the name issue is fixed. Thank you!

Possibly related, it seems that committees for Sen. Eddie Lucio Jr are not getting associated correctly.

[https://openstates.org/tx/legislators/TXL000198/eddie-lucio-jr/](https://openstates.org/tx/legislators/TXL000198/eddie-lucio-jr/) reports 0 committees.
<img width="484" alt="screen shot 2017-03-07 at 8 20 19 am" src="https://cloud.githubusercontent.com/assets/2040141/23660441/0f71bb8c-030f-11e7-8944-b8a219ea4450.png">

But, on the Committee page [https://openstates.org/tx/committees/?chamber=upper](https://openstates.org/tx/committees/?chamber=upper) it lists him as a member of several committees. 
<img width="952" alt="screen shot 2017-03-07 at 8 20 04 am" src="https://cloud.githubusercontent.com/assets/2040141/23660484/32f4abfa-030f-11e7-945d-a0e0526faea3.png">

Note that his name on the the committees page is not a link, which makes me suspect that it isn't making the association between the committee and the legislator correctly.

Let me know if you'd rather I open a different ticket for this.

**Comment by jamesturk** [comment]
let's see if this gets fixed next time TX comms run, we'll keep this ticket open to monitor it

**Comment by jamesturk** [comment]
fixed!
