### ISSUE TITLE
RI: "Dictrict Office" typo

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1474]
State: Rhode Island

The legislator District Office is mispelled "Dictrict Office".

[Example](https://openstates.org/ri/legislators/RIL000139/marvin-l-abney):

<img width="265" alt="screen shot 2017-03-07 at 11 48 11 pm" src="https://cloud.githubusercontent.com/assets/4812055/23691886/fc3f8800-0390-11e7-8266-68e11e8d983f.png">

**Comment by pmathur5k10** [comment]
@mshenfield Sir I would like o work on this error. Can you explain this to me in brief as I am new to this org. Thanks !
