### ISSUE TITLE
Add Git hook to wipe PYC files on-checkout

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1478]
To avoid confusing issues for all devs, we should wipe PYC files whenever a new branch is checked out, so that there isn't persistent behavior despite having different PY files.

Via https://git-scm.com/docs/githooks#_post_checkout

**Comment by jamesturk** [comment]
https://stackoverflow.com/questions/12222186/are-git-hooks-pushed-to-the-remote-when-i-git-push  I think this isn't possible?

**Comment by mileswwatkins** [comment]
Ah, damn!

We _could_ add it as a step in our Dockerfiles, since they `ADD` the whole of the project; since we're switching to a Dockerized system, and that's what our docs suggest, this seems like a solid solution.

A step right after the `ADD` that's, like, `RUN find ${PROJECT_PATH} -name '*.pyc' -delete`?

**Comment by jamesturk** [comment]
SGTM 👍

**Comment by jamesturk** [comment]
actually right after merging this I realized, this only gets when the docker image is created... I'm not 100% sure this will fix the problem

**Comment by jamesturk** [comment]
reopened on purpose?

**Comment by mileswwatkins** [comment]
Yup, I agree that the problem isn't fixed.

**Comment by jamesturk** [comment]
Maybe we set PYTHONDONTWRITEBYTECODE if this is still causing problems?

**Comment by jamesturk** [comment]
let's run w/ this for now
