### ISSUE TITLE
VA: Manual data (with TODO/question)

### ISSUE THREAD

**Issue by rshorey** [openstates/openstates#1486]
* upper-22: Retired Tom Garrett who was elected to US house
* upper-5: Retired Kenneth Alexander who was elected mayor of Norfolk
* lower-85: Retired Scott Taylor who was elected to US house
* lower-93: Retired T. Montgomery "Monty" Mason who was elected to the VA senate
* lower-77: Retired Lionell Spruill who was elected to the VA senate
* lower-71: Retired Jennifer McClellan who was elected to the VA senate

TODO:
* upper-9: Donald McEachin was elected to the US House. But we've got 2 copies of him. I was going to merge then retire, but if I do that, we lose the committees he was a member of upon his retirement which feels bad. Can we manually re-add those committees? I did not do anything and he remains both duplicated and superfluous.

**Comment by jamesturk** [comment]
historical committee info is pretty weak across the board, we lose it @ session turnover too because memberships in billy don't have start/end dates but are tied to our psuedo-terms

I don't think there's a great option, we may just have to accept losing it

**Comment by rshorey** [comment]
Ok, McEachin merged and retired, closing this issue.
