### ISSUE TITLE
OR: Pupa conversion should switch to API

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1505]
State: OR

Oregon now has an OData api. The new PUPA scraper should attempt to use it to avoid being banned due to site load.

https://www.oregonlegislature.gov/citizen_engagement/Pages/data.aspx

**Comment by giantryansaul** [comment]
I was working on a pupa conversion for OR last night, so I can look into this.

**Comment by showerst** [comment]
FWIW I did a little googling earlier and found this, which looks nice: https://github.com/tuomur/python-odata

**Comment by giantryansaul** [comment]
Requested access for development. 

@jamesturk: Are there instances of other states that require authentication? It looks like this will need some sort of key to access the data through the API, just wondering if there is a precent for this type of thing.

**Comment by showerst** [comment]
Indiana and New York require API keys as well; we pass them in via env vars. I'll request access too, we can see how strict their acceptance policy is.

**Comment by giantryansaul** [comment]
@showerst Have you had luck connecting to their API yet? I was given credentials, but no connection URL. I can't find any info about how to connect to their API beyond a PDF of the odata model.

**Comment by showerst** [comment]
@giantryansaul I guessed the URL; it's https://olis.leg.state.or.us/odata/ -- use http basic auth for your credentials. Haven't poked around yet but hope to this weekend!

**Comment by giantryansaul** [comment]
Awesome, thank you!

**Comment by giantryansaul** [comment]
I did a conversion of `people` to the OData API if you want to take a look, will begin transferring the other objects.

**Comment by jamesturk** [comment]
this is merged 👍
