### ISSUE TITLE
ID: Vote names saved with a trailing "(name")

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1511]
The [ID bill scraper](http://github.com/openstates/openstates/blob/63ede9983ff6b8b26aeb2c29ad715f017c940746/openstates/id/bills.py#L331) is saving names with a trailing "(name)", e.g. "(Lacey)"

Some examples:
Mendive(Mendive), Smith(Nye), Bock(Burgoyne), Rubel(Green), Horman(Reed), Smith(Lacey)

This is causing the vote to come back with a null leg_id, since the name cannot be matched back to a known legislator.

**Comment by jamesturk** [comment]
@jamesthechamp could we convert

**Comment by jamesturk** [comment]
pending run

**Comment by jamesthechamp** [comment]
@jamesturk could you elaborate what we need to convert

**Comment by jamesturk** [comment]
sorry about that, was a stray comment that I didn't realize I posted

**Comment by jamesturk** [comment]
@mshenfield can you verify this looks OK in the data now?

**Comment by mshenfield** [comment]
Running locally, verified that the examples provided are no longer present in the the votes
```
db.votes.find({"state": "id", $or: [{"yes_votes": { $elemMatch: {"name": "Mendive(Mendive)"}}}, {"other_votes": { $elemMatch: {"name": "Mendive(Mendive)"}}}, {"no_votes": { $elemMatch: {"name": "Mendive(Mendive)"}}}]})
```
and that corresponding "Mendive" votes _are_ present:

```
db.votes.find({"state": "id", $or: [{"yes_votes": { $elemMatch: {"name": "Mendive"}}}, {"other_votes": { $elemMatch: {"name": "Mendive"}}}, {"no_votes": { $elemMatch: {"name": "Mendive"}}}]})
```
