### ISSUE TITLE
ME: Vote names saved with trailing "of <district>"

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1513]
The [ME bill scraper](http://github.com/openstates/openstates/blob/63ede9983ff6b8b26aeb2c29ad715f017c940746/openstates/me/bills.py#L293) is saving vote names with a trailing "of DISTRICT".

Some examples:
MASTRACCIO of Sanford, McCREA of Fort Fairfield, McCREIGHT of Harpswell, McLEAN of Gorham, MELARAGNO of Auburn, MONAGHAN of Cape Elizabeth, MOONEN of Portland, NADEAU of Winslow, O'NEIL of Saco, ORDWAY of Standish

This is causing the vote to come back with a null leg_id, since the name cannot be matched back to a known legislator.

**Comment by mshenfield** [comment]
Similar to #1514 - district is kept to help distinguish between identical voter names.  This used to be handled but was ["un"-handled](https://github.com/openstates/openstates/commit/a1057761adc5932133293b6330d57218e65832c2) about 5 years ago.

For this scrape the url of the [data is saved](https://github.com/openstates/openstates/blob/921a3dde13f5db5c14b2017cb52a04036bb20328/openstates/me/bills.py#L289).  It would require going to the url to see the full name w/ district to correctly disambiguate any names.

This term there 12 ambiguous names:

```
AUSTIN of Gray
AUSTIN of Skowhegan
KINNEY of Knox
KINNEY of Limington
MADIGAN of Rumford
MADIGAN of Waterville
MARTIN of Eagle Lake
MARTIN of Sinclair
MASON of Androscoggin
MASON of Lisbon
PIERCE of Dresden
PIERCE of Falmouth
```

and 186 total names which have to be manually matched right now.  Does automating most of them by removing the " of " seems like a good tradeoff?

**Comment by jamesturk** [comment]
I'm not entirely clear what you mean by "could be disambiguated by going to the source URL"

the way name resolution works is on a per-name basis, not a per-vote basis, so if 
PIERCE of Dresden
PIERCE of Falmouth
both become PIERCE, we don't have a way to disambiguate them later

I think to fix these we have two options:
- add these as alternate names manually (one time cost per legislator)
- try to detect which names are duplicated (this seems potentially error prone, but might be quicker)

**Comment by mshenfield** [comment]
I was modeling a "per-vote" scenario without realizing it.

* try to detect which...

We could use an instance of `NameMatcher` for the state/chamber to determine if a raw name could be matched without complicating the script too much.

This would have to be removed when porting to pupa, which doesn't have the concept of a name matcher, so seems better to leave as is.
