### ISSUE TITLE
MS: Vote names saved with trailing "(<district>)"

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1514]
The [MS bill scraper](http://github.com/openstates/openstates/blob/63ede9983ff6b8b26aeb2c29ad715f017c940746/openstates/ms/bills.py#L261) is saving vote names with a trailing "(district)".

Some examples:
Bell (65th), Bell (21st), Evans (91st), Evans (45th), Huddleston (15th), Huddleston (30th).

This is causing the vote to come back with a null `leg_id`, since the name cannot be matched back to a known legislator.

**Comment by jamesturk** [comment]
These are useful for reconciling the person when all we get is their last
name & district.  We tend to keep these as written so we can do manual
reconciliation later as tossing it out gives us unresolvable names.

**Comment by mshenfield** [comment]
That makes sense. Closing since not actually a bug.
