### ISSUE TITLE
IL: Vote names saved as "Last,First" without a comma after space don't match leg_id

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1517]
The [IL bill scraper](http://github.com/openstates/openstates/blob/63ede9983ff6b8b26aeb2c29ad715f017c940746/openstates/il/bills.py#L392) is saving some names of voters as "Last,First" without a space between the comma.

Some examples:
Davis,William, Burke,Kelly, Harris,Gregory, Mitchell,Christian

This seems to be confusing the `billy` [`NameMatcher`](http://github.com/openstates/billy/blob/63d4311dac7545cd8e258a966212e803ce7dbbbe/billy/importers/names.py#L44), and causing it to fail to match the name to a legislator.

**Comment by hiteshgarg14** [comment]
I will look into this issue.
Converting "Davis,William" to  "Davis, William".

**Comment by jamesturk** [comment]
@mshenfield if you have a chance & could verify this one that'd be great :)

**Comment by mshenfield** [comment]
Verifying

**Comment by mshenfield** [comment]
Scraping the bills for this and #1511 to confirm there aren't any more votes still hitting these issues.

**Comment by mshenfield** [comment]
Running locally, verified that the examples provided are no longer present in the the votes

```
db.votes.find({"state": "il", $or: [{"yes_votes": { $elemMatch: {"name": "Davis,William"}}}, {"other_votes": { $elemMatch: {"name": "Davis,William"}}}, {"no_votes": { $elemMatch: {"name": "Davis,William"}}}]})
```

and that corresponding "Davis, William" votes are present:

```
db.votes.find({"state": "il", $or: [{"yes_votes": { $elemMatch: {"name": "Davis, William"}}}, {"other_votes": { $elemMatch: {"name": "Davis, William"}}}, {"no_votes": { $elemMatch: {"name": "Davis, William"}}}]})
```
