### ISSUE TITLE
HI: Vote names saved with a trailling "; "

### ISSUE THREAD

**Issue by mshenfield** [openstates/openstates#1528]
The [HI bill scraper](http://github.com/openstates/openstates/blob/d9369ddda8be727f6085c81dcacd53afd75d91f6/openstates/hi/bills.py#L132) is saving vote names with a trailing "; ".

Some examples:
Ward; , Ruderman ; , Matsumoto; , Thielen;

This is causing the vote to come back with a null leg_id, since the name cannot be matched back to a known legislator.

**Comment by In-vincible** [comment]
@mshenfield I want to take this issue.

**Comment by mshenfield** [comment]
Hey @In-vincible, this issue has already been fixed in #1529

**Comment by In-vincible** [comment]
Ohh, no problem. thanks for informing :)
