### ISSUE TITLE
[AZ, KS, KY, MA, NH, NY, TN] No votes in current term.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1540]
UPDATE Status as of 19-Mar-2017:

- AZ - https://github.com/openstates/openstates/issues/1541
- KS - needs investigation, might have been a hiccup, check after next KS run - awaiting run
- KY - https://github.com/openstates/openstates/issues/1542
- MA - WIP, https://github.com/openstates/openstates/issues/1162
- NH - Fixed
- NY - False report, ignore - working correctly
- TN - https://github.com/openstates/openstates/issues/1559

----

As of 17-Mar-2017:

These states all have no votes in the current term.  
It's possible that this is legitimate in some cases, but most are at least suspect, IMHO.

**AZ, KS, KY, MA, NH, NY, TN**

NY also has no bills.

My personal hot button is New Hampshire.

**Comment by jamesturk** [comment]
Where are you seeing NY not having bills?  https://openstates.org/ny/bills/
 -- has bills

I'll go through the rest and create tickets as needed.

**Comment by jamesturk** [comment]
* AZ - #1541 
* KS - needs investigation, might have been a hiccup, check after next KS run
* KY - #1542
* MA - WIP, #1162 
* NH - TBD
* NY - TBD
* TN - TBD

**Comment by estaub** [comment]
@jamesturk 

Yes, I confirm: NY has bills for this term.  Sorry, was getting back 

`BadRequestrequesttoolarge, trynarrowingyoursearchbyaddingmorefilters.`

from

`https://openstates.org/api/v1/bills/?state=ny&search_window=term:2017-2018`

but I missed it somehow.  I need to start using paging!

**Comment by estaub** [comment]
Confirmed: NH is fixed!

**Comment by mshenfield** [comment]
Confirmed that TN is missing votes - see the OpenStates page for [HB 16](https://openstates.org/tn/bills/110/HB16/) vs the **Votes** section for [the bill on the legislature website](http://wapp.capitol.tn.gov/apps/BillInfo/default.aspx?BillNumber=HB0016&GA=110). There was a roll call vote _Ayes 84, Nays 9, PNV 1_.

**Comment by mshenfield** [comment]
Created an issue for TN #1559

**Comment by estaub** [comment]
The last state before this can be closed (with spinoff issues for specific states) is **Kansas**.  It hasn't updated in a week - since March 13th.  The legislature has been in session.  It shows as "operational" on https://openstates.github.io/status/ .

**Comment by jamesturk** [comment]
KS ran on the 18th, 19th, and 20th, where were you seeing the lack of updates?

**Comment by estaub** [comment]
Sorry, seems to be a problem on my end of some kind.  I'll try to be a little more careful in double-checking before reporting!

**Comment by estaub** [comment]
All states have been either spun off as separate issues or otherwise resolved.
