### ISSUE TITLE
MA: first name legislator search currently requires middle initials with punctuation

### ISSUE THREAD

**Issue by aholachek** [openstates/openstates#1566]
I made the following query to /legislators:
 ?state=ma&last_name=cabral&first_name=antonio&chamber=lower

which returned 0 results. From the Open States UI I saw that Antonio Cabral has the middle initials F D so I amended my search:
first_name=antonio+f+d

but that also returned 0 results. Not until I included the periods did it return:
first_name=antonio+f.+d.

For the project I'm working on, being able to just search last_name="cabral" and first_name="antonio" would be helpful.

**Comment by jamesturk** [comment]
Two ways for us to look at this:

* make fuzzy name search logic available via API
* clean these names up a bit more, properly splitting first/middle for MA

**Comment by aholachek** [comment]
Splitting first and middle would be adequate for my use case, since while some legislators do have alternate versions of their name (e.g. MA State Senator "Vinny deMacedo" vs "Viratio deMacedo"), it happens rarely enough that it's not a big deal, at least for my project.

Thank you for looking into this!

**Comment by jamesturk** [comment]
sorry for the delay- just ran this and it looks like they're split properly, hope this didn't block you

```
ma_legs = list(db.legislators.find({'state': 'ma', 'active': True}))
for l in ma_legs:
    match = re.match('^(.*?)([A-Z]\.)$', l['first_name'])
    if match:
        print(l['first_name'], match.groups())
        l['first_name'], l['middle_name'] = match.groups()
        l['first_name'] = l['first_name'].strip()
        if '_locked_fields' not in l:
        l['_locked_fields'] = []
        l['_locked_fields'] += ['first_name', 'last_name']
        db.legislators.save(l)
```
