### ISSUE TITLE
Very frequent 502 (bad gateway) errors on district boundary lookups

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1570]
I'm very frequently seeing 502 (bad gateway) errors on district boundary lookups.  

This problem appears to not be specific to any state, and is at least somewhat random.  But it's highly reproducible.  In my usage, roughly one-third of requests fail.

**Comment by estaub** [comment]
The behavior is very odd.  

If my code retries after any length of time up to a minute, it never succeeds by itself.
However, if I set a breakpoint on the initial failure, grab the URL from the code, and make the request in the browser, it usually succeeds the first time, and when it fails, it always succeeds after a few retries.  If I then allow the code to proceed, the code's retry then succeeds.  The effect does not persist; going back and requesting the same boundary a few minutes later may fail.  

In case it's specific to some districts, here are a few:

http://openStates.org/api/v1/districts/boundary/ocd-division/country:us/state:ak/sldl:34
http://openStates.org/api/v1/districts/boundary/ocd-division/country:us/state:ak/sldl:36
http://openStates.org/api/v1/districts/boundary/ocd-division/country:us/state:ak/sldl:37

**Comment by jamesturk** [comment]
It looks like we're seeing elevated error rates on certain geo endpoints
due to some heavy usage... caching might explain why you're seeing the
behavior you are.

Are you including your API key or email address in requests?  How quickly
are you hitting these endpoints?

**Comment by estaub** [comment]
@jamesturk 
I'm using a minimum of 500 msec between requests, with larger delays between retries.

I was using an API key, but thought for a while that I saw better behavior without it, so I'm currently not using it.  At this point I don't think it has an effect.
Should I put it back on?

**Comment by jamesturk** [comment]
Hm OK, I'll take a look at what is causing this as soon as I get a chance,
we're seeing an overall 3% error rate which is certainly elevated.

API keys won't have any effect, putting one on lets us more easily analyze
traffic from different sources.

**Comment by estaub** [comment]
@jamesturk Let me know if/when you want me to hit it again.  
I've put the API key back on - starts with `7472`.

**Comment by asentner** [comment]
I'm seeing this too and it is very frequent as of right now. I got one to load about 10 minutes ago.

**Comment by jamesturk** [comment]
@asentner are you hitting the district API as well?

**Comment by jamesturk** [comment]
Just so folks know, it seems like there's at least one overzealous API user that is hitting this particular endpoint quite aggressively.  I've notified them and will take actions to block their key if they aren't able to limit their usage in the next day or so.

**Comment by asentner** [comment]
@jamesturk I'm not hitting it regularly. Was just going to do a one time download until the boundaries change.

**Comment by estaub** [comment]
@asentner Just curious... how do you know when they change?  (Motivation: https://github.com/openstates/meta/issues/25)

**Comment by jamesturk** [comment]
It's once every ~10 years for most states, a few have had to redistrict
more b/c of lawsuits.

**Comment by estaub** [comment]
> It's once every ~10 years for most states, a few have had to redistrict
> more b/c of lawsuits.

Sure, but that leaves the problem of knowing when the new census-driven boundaries are scraped for each state, when lawsuit-driven changes are made and scraped, and when errors are fixed.  I was just wondering if @asentner had some approach to that, that I hadn't thought of, that would support killing the enhancement request.
