### ISSUE TITLE
[enhancement] Add boundary-last-updated date-time field to district search data.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1572]
There's currently no way to tell when a district boundary has been updated, which probably results in a lot of needless refetching.  Returning a boundary-last-updated date-time field to district search would allow users to only refetch when there is change.

Similarly, but less importantly, adding a last-updated parameter to district search would allow much less expensive incremental updating of district search data.

**Comment by jamesturk** [comment]
reticketed https://github.com/openstates/meta/issues/25
