### ISSUE TITLE
FL: Bills scraper is indexing using Senate website which doesn't list all bills (2017)

### ISSUE THREAD

**Issue by vvpjack** [openstates/openstates#1573]
State: FL
Session: 2017
Framework: Pupa

The Senate website has a search grid that is used by the scraper for indexing. This grid is configured and claims to list all bills from house and senate but is missing house bills from the range of 2000-6000 (non-inclusive). 

FL Senate search page where list breaks from 1788 -> 6001: [here](http://flsenate.gov/Session/Bills/2017?Chamber=both&SearchOnlyCurrentVersion=False&IsIncludeAmendments=False&IsFirstReference=False&CitationType=FL%20Statutes&ParameterDescription=Searching%3A%202017%2C%20Senate%20and%20House%20Bills&HasInputError=False&PageNumber=33&ExpandedView=False). 
FL House page showing bills starting in the range Senate website is omitting: [here](http://www.myfloridahouse.gov/Sections/Bills/bills.aspx?Chamber=B&SessionId=83&BillSponsorIndex=-1&BillReferredIndex=-1&BillTypeIndex=-1&BillListIndex=-1&PagingInfo=1762:2071).

Unless there is some legislative procedural reason I don't know about, this is a malfunction in the Senate website, right? Is this something that the FL Senate team needs notification about?

**Comment by jamesturk** [comment]
this does sound like an issue w/ the Senate site... if you can try to contact them & find out what is happening that'd be great

**Comment by vvpjack** [comment]
I will reach out to them today. Thanks!

**Comment by vvpjack** [comment]
Response: 

> Dear Mr. Jackson,
>  
> The House introduced a new Bill Type known as the Appropriations Project bill type this year that corresponds to the bill range you referenced.  The Senate website updates to support the new type are currently scheduled to be live March 26th.    
>  
> Thank you,
> -Joe

**Comment by jamesturk** [comment]
Thanks for looking into this, let's check on March 26 and see if this is resolved then.

**Comment by vvpjack** [comment]
This appears to be live, and the scraper appears to be pulling the new bills.

**Comment by jamesturk** [comment]
👍
