### ISSUE TITLE
KS: Missing bill votes

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1580]
This is spun off from https://github.com/openstates/openstates/issues/1540 "[AZ, KS, KY, MA, NH, NY, TN] No votes in current term.".

Here's a case:  the Kansas site has this vote: [HB 2387 17 March](http://www.kslegislature.org/li/b2017_18/measures/vote_view/je_20170317112540_114947/)

but OpenStates shows no votes for that bill: https://openstates.org/api/v1/bills/KSB00005072/
and it has no aliases.

**Comment by jamesturk** [comment]
votes!
