### ISSUE TITLE
AL, CT, LA, NH, NY, OK, PA, SC, TX, UT, WY: remove retired/defeated state reps

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#1582]
State: AL, CT, LA, NH, NY, OK, PA, SC, TX, UT, WY

I've finished a run of my script to find vacancies and reps who are no longer in office.  Please find attached a list of reps to delete from the DB.  I've checked over all of these and they should all be correct but pleae let me know if you see problems.  Thanks!

[inactive.zip](https://github.com/openstates/openstates/files/859467/inactive.zip)

**Comment by 2p2ne5** [comment]
Is there an estimate for completion of the LA updates.

**Comment by jamesturk** [comment]
Sorry for the long delay on this, wanted to do some verification, thanks for the awesome work I'm in the process of retiring these now
