### ISSUE TITLE
VA - missing photo_url and all offices

### ISSUE THREAD

**Issue by Superjisan** [openstates/openstates#1590]
State: VA
Here's an example, notice the photo_url is empty and so is the offices. The dump data has these offices filled out though...
```
{ last_name: 'Hope',
    updated_at: '2017-03-22 07:10:19',
    sources: [ [Object], [Object] ],
    full_name: 'Patrick A Hope',
    old_roles:
     { '2009-2011': [Object],
       '2014-2015': [Object],
       '2012-2013': [Object] },
    id: 'VAL000077',
    first_name: 'Patrick',
    middle_name: 'A',
    district: '47',
    state: 'va',
    votesmart_id: '111176',
    boundary_id: 'ocd-division/country:us/state:va/sldl:47',
    email: '',
    all_ids: [ 'VAL000077' ],
    leg_id: 'VAL000077',
    party: 'Democratic',
    active: true,
    transparencydata_id: '14d3e0064f034211aa20bd7d49099a41',
    nickname: '',
    photo_url: '',
    roles: [ [Object], [Object] ],
    url: 'http://lis.virginia.gov/cgi-bin/legp604.exe?171+mbr+H219',
    country: 'us',
    created_at: '2010-12-02 07:04:38',
    level: 'state',
    chamber: 'lower',
    offices: [],
    suffixes: '' },
```

This repository is for issues with state data.

For feature requests, etc. please visit the contributor guide (see above message) to file the issue in the correct place.

**Comment by Superjisan** [comment]
@jamesturk https://openstates.org/api/v1/legislators/geo/?apikey=jzthegreat@gmail.com&lat=38.9323453%26&long=-77.2182121

that is the lat, long of VA address

**Comment by Superjisan** [comment]
![screen shot 2017-03-23 at 11 45 41 am](https://cloud.githubusercontent.com/assets/4501479/24256379/6bf149ca-0fbe-11e7-9d27-7c46e6fda2eb.png)

**Comment by Superjisan** [comment]
@jamesturk do you have a timeline for when this might be `fixed pending run` ?

**Comment by jamesturk** [comment]
looking at this today

**Comment by jamesturk** [comment]
looks to be fixed now :)
