### ISSUE TITLE
NY: reported contact issue

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1602]
Reported via email: 

On your site: https://openstates.org/ny/legislators/NYL000039/velmanette-montgomery/

DISTRICT OFFICE:
3845 Richmond Avenue
Suite 2A
Staten Island, NY 10312
Phone: 718-984-4073
Fax: 718-984-4455

On her site: https://www.nysenate.gov/senators/velmanette-montgomery/contact

DISTRICT OFFICE
30 Third Avenue, Suite 207
Brooklyn  ,  NY 11217
Phone: (718) 643-6140
Fax: (718) 237-4137

**Comment by hiteshgarg14** [comment]
Scraper is working fine:-
```
21:50:25 INFO scrapelib: GET - http://www.nysenate.gov/senators/velmanette-montgomery/contact
{'phone': '(718) 643-6140', 'fax': '(718) 237-4137', 'type': 'district', 'name': 'District Office', 'address': '30 Third Avenue, Suite 207\nBrooklyn, NY 11217'}
{'phone': '(518) 455-3451', 'fax': '(518) 426-6854', 'type': 'capitol', 'name': 'Capitol Office', 'address': '903 Legislative Office Building\nAlbany, NY 12247'}
21:50:25 INFO billy: Save person Velmanette Montgomery
```

On openstates.org it is showing district office details of [link](https://www.nysenate.gov/senators/andrew-j-lanza/contact)

**Comment by jamesturk** [comment]
unlocked NY offices
