### ISSUE TITLE
NC, FL: ImportError when running scrapers

### ISSUE THREAD

**Issue by leslie-huang** [openstates/openstates#1605]
State: NC  (be sure to include in ticket title)

I followed the instructions to run the scrapers at http://docs.openstates.org/en/latest/contributing/getting-started.html and used the example state, NC. At Step 7, when I run 

`docker-compose run openstates nc --legislators --fast`
or
`docker-compose run openstates nc --bills --fast`

I also tried this with FL and got the same ImportError.

I get the following error:
`ImportError: No module named pupa.scrape`

I don't get this error with other states that haven't been converted to pupa yet (e.g. MA, VT, RI). I just installed Docker and forked the openstates repo this week so everything on my machine is pretty up to date.

**Comment by jamesturk** [comment]
For pupa states change the 'run openstates' portion to 'run scrape'   --
sorry for the trouble

**Comment by leslie-huang** [comment]
Thanks for the reply! So now I'm running

`docker-compose run scrape nc --legislators --fast`

And I get:

exception "No module named 'opencivicdata.divisions'" prevented loading of pupa.cli.commands.init module
no pupa_settings on path, using defaults
14:30:19 CRITICAL pupa: no such scraper: module=nc scraper=--legislators

**Comment by jamesturk** [comment]
Ah, try changing it to

docker-compose run scrape nc people --fast

Definitely need some doc updates :)

**Comment by leslie-huang** [comment]
Got it, thanks!
