### ISSUE TITLE
LA - Too many legislators in json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1619]
The most recent json file available for Louisiana includes timestamps like 4/5 6:10.
A count of the ‘active’ entries in that json file shows:
json_state_house_seats = 108  The correct value = 105

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=la

Joseph Elfelt

**Comment by Jelfff** [comment]
Louisiana

I checked the state legislature website and have marked the names that are not currently in the legislature.

Lower district 29 should not have 2 people
https://openstates.org/api/v1/legislators/?state=la&chamber=lower&district=29
Edwards, Ronnie <== remove
Jordan, Edmond

Lower district 80 should not have 2 people
https://openstates.org/api/v1/legislators/?state=la&chamber=lower&district=80
Joseph P. Lopinto, III <== remove
Thomas, Polly

Lower district 85 should not have 2 people
https://openstates.org/api/v1/legislators/?state=la&chamber=lower&district=85
Bryan Adams <== remove
Marino, Joseph

**Comment by jamesturk** [comment]
fixed
