### ISSUE TITLE
MO - Districts missing from state json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1623]
The most recent json file available for Missouri includes timestamps like 4/5 7:27.
House district 50 is not in the json file.
Senate district 28 is not in the json file.

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=mo

Joseph Elfelt

**Comment by jamesturk** [comment]
Hi Joseph,

We appreciate these, but can you double check them against the state site and https://github.com/openstates/openstates/issues/1582?  

I think quite a few are addressed there, and some are issues on the state site (due to vacant seats/etc.)

**Comment by Jelfff** [comment]
James,
I am a new guy here so still feeling my way.
I opened the csv file from #1582.  My sense is that the 1582 script and mine are flagging different things.  All my script does is count the 'active' entries in the state json files that I downloaded and compares  those counts  to the number of seats in each chamber.  Those counts all match except for the issues I just posted.

The only pattern matching I see between the 1582 csv and my results are:
1. UT - There are 15 too many legislators in the json file
2. WY - There are 26 too many legislators in the json file

What do you mean by "state site"?

Joseph

**Comment by jamesturk** [comment]
No worries, always appreciate the help.

I just wanted to be sure that these weren't duplicates, and that these aren't reflecting empty seats on the official state website (as some vacancies will cause things like this).  If you've verified neither is the case by all means file away

**Comment by Jelfff** [comment]
The official state website for MO shows that the two seats described in my post are vacant.

Joseph
