### ISSUE TITLE
NH - Too many legislators in json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1624]
**Edit:  The title should say too *few*  legislators for NH**

The most recent json file available for New Hampshire includes timestamps like 4/5 5:23.
A count of the ‘active’ entries in that json file shows:
json_state_house_seats = 372  The correct value = 400

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=nh

Joseph Elfelt

**Comment by mileswwatkins** [comment]
Nah, you do mean that there're too many present.

`curl --silent https://openstates.org/api/v1/legislators/?state=nh | jq '.[] | select(.chamber=="lower") | .chamber' | wc -l`

returns 413 (400 seats total, including 5 vacancies at present)

**Comment by mileswwatkins** [comment]
Manually fixed in the database

**Comment by Jelfff** [comment]
Thanks Miles.
