### ISSUE TITLE
UT - Too many legislators in json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1625]
The most recent json file available for Utah includes timestamps like 4/3 9:38.
A count of the ‘active’ entries in that json file shows:
json_state_house_seats = 88  The correct value = 75
json_state_senate_seats = 31  The correct value = 29

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=ut

Joseph Elfelt

**Comment by jschiarizzi** [comment]
Uh oh! I will look into...

**Comment by Jelfff** [comment]
Utah

I checked the state legislature website and have marked the names that are not currently in the legislature.

Lower district 2 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=2
David E. Lifferth <== remove
Jefferson Moss

Lower district 3 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=3
Jack R Draxler <== remove
Val K. Potter

Lower district 6 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=6
Jacob L. Anderegg <== remove
A. Cory Maloy

Lower district 14 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=14
Curtis Oda <== remove
Karianne Lisonbee

Lower district 30 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=30
Fred C Cox <== remove
Mike Winder

Lower district 31 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=31
Sophia M. DiCaro <== remove
Elizabeth Weight

Lower district 34 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=34
Johnny Anderson <== remove
Karen Kwan

Lower district 43 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=43
Earl D. Tanner <== remove
Adam Gardiner

Lower district 50 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=50
Rich Cunningham <== remove
Susan Pulsipher

Lower district 53 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=53
Melvin R Brown <== remove
Logan Wilde

Lower district 54 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=54
Kraig Powell <== remove
Tim Quinn

Lower district 69 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=69
Brad King <== remove
Christine F Watkins

Lower district 70 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=lower&district=70
Kay L McIff <== remove
Carl R. Albrecht

**Upper** district 13 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=upper&district=13
Mark B Madsen <== remove
Jacob L. Anderegg

**Upper** district 20 should not have 2 people
https://openstates.org/api/v1/legislators/?state=ut&chamber=upper&district=20
Scott K Jenkins <== remove
D. Gregg Buxton

**Comment by jamesturk** [comment]
fixed

**Comment by Jelfff** [comment]
Thanks James
