### ISSUE TITLE
WY - Too many legislators in json file

### ISSUE THREAD

**Issue by Jelfff** [openstates/openstates#1626]
The most recent json file available for Wyoming includes timestamps like 4/5 8:14.
A count of the ‘active’ entries in that json file shows:
json_state_house_seats = 79  The correct value = 60
json_state_senate_seats = 37  The correct value = 30

I grabbed the json file with this API call:
https://openstates.org/api/v1/legislators/?state=wy

Joseph Elfelt

**Comment by hiteshgarg14** [comment]
For information, scraper is importing 90 legislators.

`11:39:58 INFO billy: Finished importing 90 legislator files.`

Problem is with API.

**Comment by Jelfff** [comment]
Wyoming

Perhaps the extra names are former legislators that are still shown as "active".

I checked the state legislature website and have marked the names that are not currently in the legislature.

Lower district 6 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=6
Richard Cannady <== remove
Aaron Clausen

Lower district 9 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=9
David Zwonitzer <== remove
Landon Brown

Lower district 11 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=11
Mary Throne <== remove
Jared Olsen

Lower district 14 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=14
Kermit Brown <== remove
Dan Furphy

Lower district 16 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=16
Ruth Petroff <== remove
Mike Gierau

Lower district 18 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=18
Fred Baldwin <== remove
Tom Crank


Lower district 19 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=19
Allen Jagg <== remove
Danny Eyre

Lower district 24 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=24
Samuel Krone <== remove
Scott Court

Lower district 26 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=26
Elaine Harvey <== remove
Jamie Flitner

Lower district 32 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=32
Norine Kasperik <== remove
Timothy Hallinan

Lower district 34 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=34
Rita Campbell <== remove
Tim Salazar

Lower district 35 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=35
Kendell Kroeker <== remove
Joe MacGuire

Lower district 36 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=36
Gerald Gay <== remove
Debbie Bovee

Lower district 41 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=41
Ken Esquibel <== remove
Bill Henderson

Lower district 46 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=46
Glenn Moniz <== remove
Bill Haley

Lower district 51 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=51
Rosie Berger <== remove
 Bo Biteman

Lower district 56 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=56
Tim Stubson <== remove
Jerry Obermueller

Lower district 57 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=57
Thomas Lockhart <== remove
Chuck Gray

Lower district 58 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=lower&district=58
Tom Reeder <== remove
Pat Sweeney

*Upper* district 4 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=4
Tony Ross <== remove
Tara Nethercott

*Upper* district 6 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=6
Wayne Johnson <== remove
Anthony Bouchard

*Upper* district 8 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=8
Floyd Esquibel <== remove
Affie Ellis

*Upper* district 10 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=10
Phil Nicholas
Glenn Moniz

*Upper* district 12 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=12
Bernadine Craft
Liisa Anselmi-Dalton


*Upper* district 14 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=14
Stan Coope
Fred Baldwin

*Upper* district 20 should not have 2 people
https://openstates.org/api/v1/legislators/?state=wy&chamber=upper&district=20
Gerald Geis
Wyatt Agar

**Comment by jamesturk** [comment]
fixed
