### ISSUE TITLE
PA: missing contacts urls

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1652]
State: PA

@samtregar-  missed this in review, but pa/people.py references utils.urls['contacts'] which doesn't exist, do you have that change locally?

**Comment by samtregar** [comment]
Well, huh, so it does.  I think I fumbled it in some git confusion.  Pull request coming up.

**Comment by samtregar** [comment]
https://github.com/openstates/openstates/pull/1654

**Comment by jmcarp** [comment]
Looks like the fix was merged. Good to close?

**Comment by jamesturk** [comment]
yep, thanks!
