### ISSUE TITLE
[NH, probably others] Motion and antimotion: the physics of NH voting; bills falsely "passed"

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1658]
I have no idea how much this applies to other states.  I doubt NH is unique.

For an example, take a look at this vote: https://openstates.org/nh/votes/NHV00002880/

There you see a vote on a motion of "ITL" that succeeded, with openstates inferring **BILL STATUS: PASSED**.  The inference is wrong.

When the NH legislature votes on a bill, they are actually voting on whether to accept the finding of the committee, which is typically either `Ought to Pass` (OTP) or its antimotion, `Inexpedient to Legislate` (ITL, as on this bill).  _A "yes" vote on an ITL is a vote to kill the bill._  

I'd suggest expanding the motion types to include "-bill-passage", "kill bill", or similar.

I don't know enough to accurately write up the relevant issues.  For instance, there's an undocumented field called "passed" on the vote that either means "the vote succeeded" (true) or that "this vote caused the bill to pass" (false).

There are two other scraping issues on this bill (NHB00005946) that I'll write up separately.

**Comment by jamesturk** [comment]
I think the solution here is to change that site text, that should really
stay 'Vote Status' instead. That's what the field means in the data, the UI
is misleading here.

**Comment by jamesturk** [comment]
reticketed as openstates/openstates.org#53

**Comment by estaub** [comment]
@jamesturk 

FWIW, the API "passed" field is misleading named as well.  

What about the motion type?  I don't know how far along they are; there aren't any on NH.

**Comment by jamesturk** [comment]
How so? That field is on the vote, the vote did pass.

**Comment by estaub** [comment]
> How so? That field is on the vote, the vote did pass.

Sorry, please nevermind... I'm being anal, I think.  I think of bills passing, and votes _succeeding_.

The motion type though, is important, if we're actually doing them.
