### ISSUE TITLE
[NH] Committee minority report recorded as separate action.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1659]
For bill NHB00005946, a single committee vote resulted in both of these actions:

    {
        "date": "2017-03-01 02:26:30", "type": ["committee:passed:unfavorable"], "actor": "lower",
        "action": "Majority Committee Report: Inexpedient to Legislate for 03/08/2017 (Vote 7-4; RC)",
        "related_entities": []
    }, {
        "date": "2017-03-01 02:26:31", "type": ["committee:passed:favorable"], "actor": "lower",
        "action": "Minority Committee Report: Ought to Pass", "related_entities": []
    }

To my mind, the minority report shouldn't be reported at all, or at least should be reported as a different type altogether, e.g. "committee:minority:favorable".

**Comment by jamesturk** [comment]
We get those actions from the state itself.

**Comment by estaub** [comment]
Yes, dropping the classification would be good.

**Comment by jamesturk** [comment]
@estaub if you want to make this change to the NH scraper I'm good w/ dropping classification on all Minority committee reports

**Comment by estaub** [comment]
@jamesturk Sorry, I don't do Python - wish I did!

**Comment by jamesturk** [comment]
we'll do this post-#1551, basically short circuit the action classifier if 'Minority Committee Report' is in action
