### ISSUE TITLE
[NH] Floor vote incorrectly recorded as committee vote

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1660]
For bill NHB00005946, this floor vote is incorrectly recorded as `"type": ["committee:passed:unfavorable"]`:

    {
        "date": "2017-03-09 03:42:22", "type": ["committee:passed:unfavorable"], "actor": "lower",
        "action": "Inexpedient to Legislate: MA RC 202-149 03/09/2017",
        "related_votes": ["NHV00002880"], "related_entities": []
    }

For some background on "Inexpedient to Legislate", see https://github.com/openstates/openstates/issues/1658

**Comment by jamesturk** [comment]
either as part of or post-#1551
