### ISSUE TITLE
Billy2Pupa: map Pupa `other_identifiers.identifier` to item in Billy `alternate_bill_ids` list

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1662]
Sound okay, @jamesturk? I'll make it happen if so.

**Comment by jamesturk** [comment]
Yeah that should be fine, forgot we had alternate_bill_ids

**Comment by jamesturk** [comment]
@mileswwatkins which scraper(s) were using this?

**Comment by jamesturk** [comment]
oh it looks like TN!
