### ISSUE TITLE
IL: Capture "Subject Matter" for `event`s

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1668]
IL events have a Subject Matter field on the legislature's website, which we should capture, probably as the `description` value for that `event` object.

For example, look at one of the hearings linked from [here](http://www.ilga.gov/senate/committees/hearing.asp?CommitteeID=1927), like this:

<img width="864" alt="screen shot 2017-04-23 at 00 19 37" src="https://cloud.githubusercontent.com/assets/4959135/25310740/bb6f24b8-27ba-11e7-96e3-9b102819581c.png">

cc @jonrogoff, @justgosh

**Comment by hiteshgarg14** [comment]
@mileswwatkins currently the `description` value for that `event` object is occupied. Should I move it to `**kwargs` and update the `description` value as `Subject Matter field`?

**Comment by jonrogoff** [comment]
It may be worth noting that hearings have either bills or `Subject Matter`.  It appears to be either one or the other.

**Comment by mileswwatkins** [comment]
@hiteshgarg14, it looks like right now the description and participant name are the same thing on all IL `event` items. For `description` you could append the two if you'd like, formatted something like `"{}, {}".format(meeting_name, subject_matter)`.

Also, it looks like the `participant` field sometimes has extraneous text, like `Hearing Notice For Appropriations I` instead of `Appropriations I`, which could be fixed while you're in there.
