### ISSUE TITLE
Votes from the future: scrape or no?

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1688]
I grabbed the Tennessee bill set yesterday (April 30th) from the API, and found votes in it that hadn't happened yet - they were scheduled for today, Mayday.  Here's one: https://openstates.org/tn/votes/TNV00048411/ .

I suspect it would be best to just ignore votes that are clearly in the future, or are from scrape day and have no outcome - no vote counts, no pass/fail status.  If folks disagree, maybe a "future" flag?

**Comment by jamesturk** [comment]
I think it probably adds unnecessary complexity to the scrapers to ignore valid data that is published for the future.

Clients are of course free to ignore it and can easily do so, but if the state is publishing it we'll trust it (another common example is future actions which are already scheduled)
