### ISSUE TITLE
MO: Senate Bills include co-sponsors, House Bills don't

### ISSUE THREAD

**Issue by brentajones** [openstates/openstates#1692]
State: MO

(not sure if this is the right place for this, apologies if not)

At least for 2016 and 2017, it appears that the Missouri Senate bills list their co-sponsors, while House Bills do not.

Example:

HB 27: [State site](http://www.house.mo.gov/Bill.aspx?bill=HB1&year=2017&code=R), [OpenStates](https://openstates.org/mo/bills/2017/HB28/)

SB 67: [State site](http://www.senate.mo.gov/17info/BTS_Web/CoSponsors.aspx?SessionType=R&BillID=57095406), [OpenStates](https://openstates.org/mo/bills/2017/SB67/)

**Comment by jmcarp** [comment]
This should be fixed in https://github.com/openstates/openstates/pull/1681/commits/f7f27f810e068bbd40e1fc5b3644f3bde1148ec4.

**Comment by jmcarp** [comment]
Now that #1681 is merged, both the openstates links from the issue have cosponsors. Should be good to close.
