### ISSUE TITLE
TX: representative missing - Lynn Stucky, TX-064

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#1707]
State: TX

Took office in Jan 10, 2017 according to Wikipedia.  On the TX house site here:

http://www.house.state.tx.us/members/member-page/?district=64

Doesn't appear here:

https://openstates.org/api/v1/legislators/?state=tx&chamber=lower

**Comment by samtregar** [comment]
Tried a run of the scraper and it produced a file for him that looks fine.  Maybe his district got blocked from loading when there was a previous vacancy?

**Comment by jamesturk** [comment]
thanks for this, I'll take a look

**Comment by jamesturk** [comment]
fixed
