### ISSUE TITLE
AL: committees are missing

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1713]
State: AL

Alabama committees are missing, it looks like there's code to scrape them so we'll just need to take a look at why they aren't coming through

**Comment by hiteshgarg14** [comment]
Trying to figure out. But not getting anything missing. 
can you show one example?

Thanks

**Comment by jamesturk** [comment]
interesting, this may be a bug elsewhere if they're coming through in the scraper

https://openstates.org/al/committees/ is showing no members on any committees

**Comment by hiteshgarg14** [comment]
Yeah! It may be a case. 
My approach: - I verified that there are `membership` objects getting created for legislators in related `organizations` with their correct `roles`.   

Please let me know if my approach is wrong. 

Thanks
