### ISSUE TITLE
Senator O'brien from Michigan

### ISSUE THREAD

**Issue by Tobin9130** [openstates/openstates#1716]
State: _MI__  (be sure to include in ticket title)

Senator O'Brien from Michigan returns 'None' for her Leg ID. This is a carryover from sunlight labs, as she is the only one it has been easy to account for. 

Not sure if the ID fails to match from legislator pull. I notice from pulling yes or no votes from Bill Detail

**Comment by jamesturk** [comment]
Can you give an example call we can check out?

Also it isn't entirely clear what you mean by carryover from Sunlight Labs.

**Comment by Tobin9130** [comment]
`votes =  pyopenstates.get_bill(uid = None, state = 'mi', term = session, bill_id= 'SB 130')`

If you pprint votes its pretty obvious.
 
`pprint(votes['votes'][1]['yes_votes'])`

The holdover thing is just me saying that it used to do the same thing with the sunlight labs, sorry for that confusion. I'm guessing it has to do with the ' in her name.

**Comment by Tobin9130** [comment]
Ah shoot session was set to '2017-2018'

**Comment by lavaturtle** [comment]
It's visible on this page, too: https://openstates.org/mi/votes/MIV00007850/

**Comment by jamesturk** [comment]
just added a manual match for her, after the next run of MI this might get fixed

right now MI is suffering from another issue though, we'll need to resolve #1738

**Comment by jamesturk** [comment]
fixed 👍  thanks for the report
