### ISSUE TITLE
CO: perpetual motions

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1731]
Vote motion scraping maybe should be worked on some to avoid this, e.g.:

https://openstates.org/co/votes/COV00020394/

> The amendment was declared passed by the following roll call vote: YES 53 NO 11 EXCUSED 1 ABSENT 0 Arndt N Foote Y Leonard Y Ransom N Becker J. Y Garnett Y Lewis Y Rosenthal N Becker K. Y Ginal Y Liston Y Saine N Beckman Y Gray Y Lontine Y Salazar Y Benavidez N Hamner Y Lundeen Y Sias Y Bridges Y Hansen Y McKean Y Singer Y Buck E Herod Y McLachlan Y Thurlow Y Buckner Y Hooton Y Melton Y Valdez Y Carver Y Humphrey N Michaelson Jenet Y Van Winkle N Catlin Y Jackson Y Mitsch Bush Y Weissman Y Coleman Y Kennedy Y Navarro Y Willett Y Covarrubias Y Kraft-Tharp N Neville P. Y Williams D. Y Danielson Y Landgraf N Nordberg Y Wilson Y Esgar Y Lawrence Y Pabon N Winter Y Everett Y Lebsock N Pettersen Y Wist Y Exum Y Lee Y Rankin Y Young Y Speaker Y The question being, "Shall the bill, as amended, pass?". A roll call vote was taken. As shown by the following recorded vote, a majority of those elected to the House voted in the affirmative, and the bill, as amended, was declared passed.

**Comment by jamesturk** [comment]
we should check if #1616 fixes this
