### ISSUE TITLE
Multiple states: Duplicate committees

### ISSUE THREAD

**Issue by jmcarp** [openstates/openstates#1744]
AZ:
<img width="827" alt="screen shot 2017-05-21 at 11 55 39 pm" src="https://cloud.githubusercontent.com/assets/1633460/26292061/0832f3c4-3e81-11e7-8b4f-57e7952e7dd6.png">

DE:
<img width="863" alt="screen shot 2017-05-21 at 11 56 18 pm" src="https://cloud.githubusercontent.com/assets/1633460/26292069/1defc8a4-3e81-11e7-8fe9-0997f07d7ca8.png">

FL:
<img width="906" alt="screen shot 2017-05-21 at 11 56 53 pm" src="https://cloud.githubusercontent.com/assets/1633460/26292079/36618706-3e81-11e7-8ec0-401cd5a7b001.png">

I haven't verified whether duplicate committees come from old scraper runs, bugs in scrapers, or both.

**Comment by hiteshgarg14** [comment]
AZ, DE, FL: Committee scrapers are fetching correct data.

**Comment by jmcarp** [comment]
Yep, I'm guessing at least some of these issues come from previously scraped data. By the way, I haven't checked all states for this kind of issue--just picked a few toward the beginning of the alphabet.

**Comment by jamesturk** [comment]
this will now be handled via openstates/people, there's still some stale data in billy but the postgres database is in much better shape so marking these as obsolete
