### ISSUE TITLE
No bulk json downloads since 2016 for most states.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1768]
See https://openstates.org/downloads/ 

Is json support being dropped?

I used to use them, but stopped when they stopped.

**Comment by jamesturk** [comment]
We'd sort of been waiting to see if people complained/noticed (that's when we turned on the CSV file generation again).

We can do them again, now that pretty much everything is moved to the new system we'll also start publishing some new format data dumps in the near future.

I'll aim to turn the JSON dump back on in the next few days

**Comment by estaub** [comment]
James, fwiw: getting better last-update fields on bills is a lot more important, at least for me.  As long as every bill in the current session appears to be updated every night, batch-loading the old ones won't avoid a lot of needless re-fetching.

**Comment by jamesturk** [comment]
Cool & good to know, that's a major feature of the new system actually- so
*soon* :+1:

**Comment by jamesturk** [comment]
a full JSON dump is running now- takes a few hours but I'll double check on it in the morning
