### ISSUE TITLE
CA vote with chamber=="committee"

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1772]
There's at least one vote, CAV00144071, in CA with a chamber of "committee".  I suspect this is a new issue; code of mine that's been in place for 6 months or so blew up on seeing it.  According to the docs (http://docs.openstates.org/en/latest/api/bills.html), it should be "upper", "lower", or "joint".

If this is correct, the docs need updating.

**Comment by estaub** [comment]
There are hundreds of these.

**Comment by jamesturk** [comment]
reticketing as https://github.com/openstates/documentation/issues/46
