### ISSUE TITLE
CA: some email addresses use suffix instead of last name

### ISSUE THREAD

**Issue by dnoble** [openstates/openstates#1784]
State: CA

In openstates/ca/people.py, _construct_email() is trying to build email addresses with the legislator's last name. In a few cases, the suffix (Sr., Jr., Ph.D.) is used instead of the last name. This happens for assemblymembers Choi, Salas, and Jones-Sawyer:

assemblymember.phd.@assembly.ca.gov <- incorrect data has this
assemblymember.choi@assembly.ca.gov <- should be this

assemblymember.jr.@assembly.ca.gov <- incorrect data has this
assemblymember.salas@assembly.ca.gov <- should be this

assemblymember.sr.@assembly.ca.gov <- incorrect data has this
assemblymember.jones-sawyer@assembly.ca.gov <- should be this

**Comment by PaulAnton** [comment]
for a list of suffix-reference: https://www.lehigh.edu/lewis/suffix.htm
hey I think if we replace line 250 of the code with the following we will be able to avoid that issue:

suffix=["Ph.D.","Ret.","Sr.","Jr.","Ed.D.","II","III","IV","V","B.V.M.","CFRE","CLU","CPA","C.S.C.","C.S.J.","D.C.","D.D.","D.D.S.","D.M.D.","D.O.","D.V.M.","Inc.","J.D.","LL.D.","Ltd.","M.D.","O.D.","O.S.B.","P.C.","P.E.","R.G.S","R.N.","R.N.C.","S.H.C.J.","S.J.","S.N.J.M.","S.S.M.O.","USA","USAF","USAFR","USAR","USCG","USMC","USMCR","USN","USNR"]
if any(check in name for check in suffix):
	last_name = re.split(r'\s+', name)[-2].lower()
else:
	last_name = re.split(r'\s+', name)[-1].lower()

**Comment by PaulAnton** [comment]
the indent went away! in the post,

**Comment by jamesturk** [comment]
to check tomorrow: https://openstates.org/ca/legislators/CAL000380/reginald-b-jones-sawyer-sr/
