### ISSUE TITLE
IL: use of committees in bills.py currently prevents import

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#1791]
State: IL

Right now I think there are two things blocking a pupa import (which we aren't doing yet since things go through pupa2billy)

- [ ] committees in bill_actions don't resolve (use sources__url)
- [ ] committees in vote events don't resolve either w/ ```pupa.exceptions.UnresolvedIdError: multiple objects returned for Organization pseudo id ~{"classification": "committee", "name": "Higher Education"}: {'ocd-organization/bfa1d330-8c3a-4ba2-9719-e68da0450536', 'ocd-organization/e754c0c7-305b-41d7-abd1-b104e140f4fb'}```

We may need to temporarily disable these to get a pupa import working, or add/fix these in pupa somehow.

 @fgregg wanted to get your thoughts whenever you have a chance

**Comment by jamesturk** [comment]
#1773 is related

**Comment by fgregg** [comment]
I've started working on these.

I think I have a complete fix for committees in bill_actions but the votes are.... difficult

https://github.com/openstates/openstates/compare/master...datamade:master (the first two commits should address the bill actions)

I probably won't have a time to pick this back up until next week. But, if someone wanted to pick this up, please do so.

**Comment by fgregg** [comment]
@jamesturk I think we need this https://github.com/opencivicdata/pupa/issues/288 to finish up the resolution of organizations in committee votes
