### ISSUE TITLE
CT House Votes Missing

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1803]
State: CT

No assembly votes appear to be pulled in for the current regular session.

**Addendum 1:** Senate votes are also affected.

**Addendum 2:** It seems in the `scrape_votes()` function, when [parsing the HTML table](https://github.com/openstates/openstates/blob/master/openstates/ct/bills.py#L187), the `xpath` logic is off. It scrapes the "Y", "N", "X" as the legislator name (it did this for [Vote for HB-7052 Roll Call Number 279](https://www.cga.ct.gov/2017/VOTE/h/2017HV-00279-R00HB07052-HV.htm), for example), and treats them all as "other" votes...

**Comment by hiteshgarg14** [comment]
On VoteEvent Details, Page votes count other than "yes' and "no" are displayed as `Those absent and not voting` and only sign "X" is used in the table (eg, [Link](https://www.cga.ct.gov/2017/VOTE/h/2017HV-00279-R00HB07052-HV.htm)) 
and in OCD `absent` and `not voting` are two vote option choices and here we can't differ between in these two choices. 
so I think it's ok for now to leave them as "other" votes.

**Comment by In-vincible** [comment]
Looking on this one.
