### ISSUE TITLE
GA votes need name matching

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1812]
The GA state senate is missing votes (e.g., [GAV00006507](https://openstates.org/ga/votes/GAV00006507/) doesn't have a single vote) **and** the state Assembly is missing votes (e.g., [GAV00006524](https://openstates.org/ga/votes/GAV00006524/) doesn't have a single vote). This appears quite widespread for the current term in GA, that votes seem to be missing on nearly every motion.

**Addendum.** The problem appears to be the clerks record votes as "LAST NAME, district number" which messes up the vote parsing. But if we simply remove the ", district number" part of the string, the votes are identified with the legislator correctly, which seems to fix the problem.

**Comment by estaub** [comment]
I believe this failure has become total; there are now no individual roll call votes for 2017.
