### ISSUE TITLE
RI Missing Senate Votes

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1813]
RI appears to be missing a lot of Senators' votes on various motions (see, e.g., [RIV00006771](https://openstates.org/ri/votes/RIV00006771/) which has only 3 Senators identified).

**Addendum:** It appears the crawler is throwing a lot of errors trying to import votes, with the logging info printing: `13:55:49 DEBUG billy: Failed to match vote upper 2017 SB 364` (and so on).

**Comment by pqnelson** [comment]
The problem seems to be that, in the process of the rewrite, the Rhode Island crawler now populates the vote json files with the proper `bill_id` (before it was only the numeric value(?), which required a [hack in billy](https://github.com/openstates/billy/blob/master/billy/importers/bills.py#L248) that's no longer needed).

If we remove the `_partial_vote_bill_id` in the [billy_metadata/ri.py](https://github.com/openstates/openstates/blob/ccc4d9db5aa9c3af40dace58d03009948b8df463/billy_metadata/ri.py#L105) file, the votes for Rhode Island are populated correctly again.

**Comment by jamesturk** [comment]
Ah nice catch- mind submitting a PR for this?

**Comment by pqnelson** [comment]
Sure thing, I'll push it in momentarily.

**Comment by estaub** [comment]
Is this fixed and closeable, or now even worse?  The vote referenced (https://openstates.org/ri/votes/RIV00006771/) is no longer in the system, which could be good or bad, depending.
