### ISSUE TITLE
NC Scraper failing with no such file or directory on master

### ISSUE THREAD

**Issue by asentner** [openstates/openstates#1815]
Having an issue running scrapers for NC locally.

Running to command:
```
docker-compose run scrape nc
```

Results in the following error on master
```
/opt/openstates/openstates/pupa-scrape.sh: line 14: /bin/pupa: No such file or directory
```

**Comment by jamesturk** [comment]
can you try updating your docker image?

NC has a special session issue due to missing data but that looks to be
related to an old docker image afaik

**Comment by asentner** [comment]
@jamesturk Thanks for your quick response! Trying a fresh image. Can you not reproduce?

**Comment by jamesturk** [comment]
I can't reproduce that one- let me know if that still happens w/ a fresh
openstates/openstates image

**Comment by jamesturk** [comment]
closing this out, feel free to comment or email me if you're still having an issue here but verified this isn't occurring w/ a fresh image

**Comment by asentner** [comment]
I figured it out, just wiped out all of my images. Think it was one without a label causing my problems.
