### ISSUE TITLE
Failing geocode lookups - AZ, MT (and I'm sure more)

### ISSUE THREAD

**Issue by dustingtaylor** [openstates/openstates#1817]
State: AZ, MT tested

Trying to search legislators by geocode and receiving error back.

error report:

Piston/0.2.3rc1 (Django 1.9.13) crash report: Traceback (most recent call last): File "/home/openstates/virt/local/lib/python2.7/site-packages/newrelic/hooks/component_piston.py", line 33, in __call__ return self._nr_wrapped(*args, **kwargs) File "/home/openstates/virt2017-06-23-04-21/src/billy/billy/web/api/handlers.py", line 88, in new_read obj = old_read(*args, **kwargs) File "/home/openstates/virt2017-06-23-04-21/src/billy/billy/web/api/handlers.py", line 396, in read resp = json.load(urllib2.urlopen(url, timeout=0.5)) File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen return opener.open(url, data, timeout) File "/home/openstates/virt/local/lib/python2.7/site-packages/newrelic/hooks/external_urllib2.py", line 31, in _nr_wrapper_opener_director_open_ return wrapped(*args, **kwargs) File "/usr/lib/python2.7/urllib2.py", line 429, in open response = self._open(req, data) File "/usr/lib/python2.7/urllib2.py", line 447, in _open '_open', req) File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain result = func(*args) File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open return self.do_open(httplib.HTTPConnection, req) File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open r = h.getresponse(buffering=True) File "/home/openstates/virt/local/lib/python2.7/site-packages/newrelic/hooks/external_httplib.py", line 74, in httplib_getresponse_wrapper response = wrapped(*args, **kwargs) File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse response.begin() File "/usr/lib/python2.7/httplib.py", line 453, in begin version, status, reason = self._read_status() File "/usr/lib/python2.7/httplib.py", line 417, in _read_status raise BadStatusLine(line) BadStatusLine: ''

**Comment by jlev** [comment]
Same

**Comment by jamesturk** [comment]
We believe this issue is now resolved, there was a hiccup w/ an EC2 instance upstream of the API
