### ISSUE TITLE
CA Votes already scrapped aren't updating to reflect proper chamber

### ISSUE THREAD

**Issue by pqnelson** [openstates/openstates#1852]
So, after fixing the Missing CA Assembly votes issue #1802, which accidentally had assembly votes assigned to the "default" chamber `legislature` (which was then, in turn, interpreted as the upper chamber), the CA assembly votes _already scrapped_ (like the [Third Reading on AB 213](https://openstates.org/ca/votes/CAV00148988/) in the Assembly) still has `upper` as its chamber.

These should be deleted (or updated to have the `chamber` set to `lower`) whenever the total number of votes is greater than 40 (the number of CA senators).

But it looks like the _new votes_ being scrapped for the CA Assembly has the correct `chamber` field set to `lower`.

**Comment by jamesturk** [comment]
Thanks, I'll take a look at this- I think they should be deleted
