### ISSUE TITLE
MS: poorly-formatted district addresses

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1872]
Mississippi legislator addresses (both chambers) appear correctly-formatted for the capitol. However, for district offices, many (or all) are in the format of:

```
${street address}

${city}
${ZIP code}
```

when it should naturally be

```
${street address}
${city}, MS ${ZIP code}
```

**Comment by narendra36** [comment]
Can I work on this ?

**Comment by mileswwatkins** [comment]
closed by https://github.com/openstates/openstates/pull/2160
