### ISSUE TITLE
CA: Some votes missing names for non-Yea categories

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#1889]
_c/o an individual via contact@openstates email_

At least one California vote has names for (8) Yea voters, but not for the (3) Nay or (2) Other voters: https://openstates.org/ca/votes/CAV00149446/

[The legislative website has them listed correctly](https://leginfo.legislature.ca.gov/faces/billVotesClient.xhtml?bill_id=201720180SB249), but this may be an issue with the DB dump we use?

**Comment by jamesturk** [comment]
seems to be resolved
