### ISSUE TITLE
[CT,GA,KY,ME,MN,MO,NY,PR,WI] All 2017 individual roll call votes missing for these chambers:

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1903]
Last update: November 10th.  Other chambers were not evaluated.  I only re-analyzed the ones that had no resolved 2017 roll calls on Sept 3 to provide more detail.  I will update individual issues shortly.

By my reckoning, these chambers currently have, _at best_, no individual roll call votes with leg_id's recorded in 2017.  Some manual work was involved in putting this together; there may be errors.  Relevant state-specific Github issues are listed where they exist.

| State  | Issues | upper | lower |
| --- | ------ | :-------------: | :--------------: |
| ct | #1803  |  | no leg_ids |
|ga | #1360, #1812|no leg_ids|no leg_ids|
|ky | #1542|needs scraper|needs scraper|
|me | #1865|no leg_ids|no leg_ids|
| mn | #1906, #1959  | no votes at all; votes are in the upstream calendar; see #1959 for possible cause |  |
|mo | #1907| | no *_votes; needs roll call scraper |
|ny | #1384, #1831, #1960| | no votes at all |
|pr | #1908|no *_votes; needs roll call scraper|no *_votes; probably unfeasible (without OCR)|
|wi | #1909|no *_votes; votes are visible upstream||

_Legend_
- "no *_votes" means that all votes read `yes_votes:[], no_votes:[], other_votes:[]`
- "no votes at all" means there aren't any 2017 bills with any votes in the chamber.
- "no leg_ids" means that for all votes on all 2017 bills, the members of the `yes_votes`, `no_votes`, and `other_votes` have no leg_id field.

There are several other states with partial failures in this area, like https://github.com/openstates/openstates/issues/1858 and https://github.com/openstates/openstates/issues/1853, that I haven't noted here.

I wrote up a similar issue, with mostly different states, in March: https://github.com/openstates/openstates/issues/1540

FWIW: I haven't kept metrics, but I believe there's been a drastic decrease in quality in roll calls over the last year.  I'm not finding fault with anyone, just observing; I know there are reasons!

@jamesturk If after a bit of verification, if you want me to spin off separate issues for `{ mn, mo, pr,  wi }`, as I did last time, let me know.

**Comment by jamesturk** [comment]
Thanks for this, leg_id matching is often a manual process and we haven't done any for these states as we move towards more automated solutions.  I'll look into what can be done, as some of these are relatively minor and could probably get some fixes.

**Comment by jamesturk** [comment]
new issues for the ones that don't already have issues filed would be best, thanks!

**Comment by estaub** [comment]
Updated original post to reference single-state issues for MN, MO, PR, WI.

**Comment by jamesturk** [comment]
thanks, closing this in favor of those

**Comment by jamesturk** [comment]
reopening since there are edits here.
we'll triage these in coming weeks

**Comment by estaub** [comment]
The list of 2018 states that are failing in both chambers in this way:
A brief (i.e., possibly wrong) analysis looks like these states are total fails on this:

- al
- de
- ga
- me
- mi
- mo
- nm
- oh
- pr
- tn
- ut
- va
- wi


Also, the Minnesota Senate and New York Assembly.

**Comment by jamesturk** [comment]
do you have a breakdown of which of these we have votes for (& are unmatched?) and which we're missing votes for?  I can run a query this afternoon to do that but if you have it handy that'd be great.

**Comment by estaub** [comment]
Closing; replaced by #2312.
