### ISSUE TITLE
CA: Bills not updating

### ISSUE THREAD

**Issue by mhedblom** [openstates/openstates#1905]
CA bills are not updating. For example, the last Action for AB81 in OpenStates is Jun 26, 2017.

https://openstates.org/ca/bills/20172018/AB81/

But the Calif leginfo site shows updates on Sep 1, 2017

http://leginfo.legislature.ca.gov/faces/billHistoryClient.xhtml?bill_id=201720180AB81

Today is Sep 5, so I should expect that this should have sync'd by now.

I'm looking at a few other bills and I see at least one whose action was Sep 1, and it is current in OpenStates, but I am finding others that are not

AB81 No Match -- CA last action Sep 1; OS Jun 26
AB699 No Match -- CA last action Sep 1; OS May 30
AB340 MATCH -- Last action Sep 1
AB424 MATCH -- Last action Aug 31

**Comment by jamesturk** [comment]
Thanks for letting us know, we'll have to look into if this is an issue w/ the upstream CA data or not, we are updating from CA nightly seemingly without error

**Comment by mhedblom** [comment]
I just pulled the daily update file from the CA leginfo download, and I see the updated data. For example, for AB81, I see these two records in the Friday night BILL_HISTORY_TBL.dat:

`201720180AB81` | 111189254 | **6/26/201**7 0:00 | `In committee:  Referred to   suspense file.` | `LEG_ESI` | 9/1/2017 19:20 | 13 | `300` | `Applied` | `Senate` | `Committee` | `CS61` | `In Committee Process`
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
`201720180AB81` | 111189256 | **9/1/2017** 0:00 | `Read second time and   amended.  Ordered returned to second   reading.` | `LEG_ESI` | 9/1/2017 19:20 | 14 | `22` | `Applied` | `Senate` | `Floor` | `Second Reading` | `In Floor Process`
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

But, when I look at OpenStates, the last action I see is the 6/26/event:

https://openstates.org/ca/bills/20172018/AB81/

Date | Chamber |  
-- | -- | --
Jun 26, 2017 | Senate | In committee: Referred to suspense file.

Or, from the API:
```
{"date": "2017-06-26 00:00:00", "action": "In committee: Referred to suspense file.", "type": ["committee:referred"], "related_entities": ...
```
So, if OpenStates uses the downloads, it appears to be an OpenStates problem.  If you all are still scraping, perhaps it is a timing issue.

**Comment by mhedblom** [comment]
Sorry to ask this, but what does the READY label mean? I cannot find a definition on this site for the labels.

This issue is now affecting all of the bills we have been tracking and is blocking us.

**Comment by jamesturk** [comment]
it means that it's ready for development- sorry to hear it is blocking you,
if someone on your team has spare cycles to investigate that'd be great,
otherwise we'll be on it as soon as possible
