### ISSUE TITLE
PR: All 2017 individual roll call votes are missing for both houses

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1908]
Both houses currently have no individual roll call votes recorded in 2017.

**Comment by estaub** [comment]
Both houses have no individual roll call votes at all for 2017, i.e. the `yes_votes`, `no_votes`, and `other_votes` arrays are always empty. The first comment is updated to reflect this.

**Comment by Nosferican** [comment]
The Senate has daily pdf which are parsable at http://senado.pr.gov/Pages/DiariodeSesiones.aspx. The House has a really unreliable system so not possible unless it can recognize the votes from images like http://www.oslpr.org/2017-2020/%7BDE3BF6AE-1BD4-4959-89F7-E2F0E206E066%7D.pdf.
