### ISSUE TITLE
not all states have active committees

### ISSUE THREAD

**Issue by jketch836** [openstates/openstates#1910]
State(s): [AK, FL, GA, IN, IA, KY, LA, ME, MD, MI, MT, NY, ND, PR, WV]

This repository is for issues with state data.

For feature requests, etc. please visit the contributor guide (see above message) to file the issue in the correct place.

**Comment by jamesturk** [comment]
can you elaborate on this one,?

**Comment by jketch836** [comment]
The legislators of the states listed above have an issue when it comes to their current roles. It lists their party affiliation, but that is about it, no other roles are listed, such as their committees. Also the states committees do not list any members.

**Comment by jamesturk** [comment]
the party role also includes their role in the chamber, for example one AL legislator (I checked random examples in a few states)

```
"id": "ALL000036",
    "roles": [
      {
        "term": "2015-2018",
        "end_date": null,
        "district": "66",
        "chamber": "lower",
        "state": "al",
        "party": "Republican",
        "type": "member",
        "start_date": null
      },
      {
        "term": "2015-2018",
        "committee_id": "ALC000003",
        "chamber": "lower",
        "state": "al",
        "subcommittee": null,
        "committee": "Technology and Research",
        "position": "Member",
        "type": "committee member"
      },
      {
        "term": "2015-2018",
        "committee_id": "ALC000016",
        "chamber": "lower",
        "state": "al",
        "subcommittee": null,
        "committee": "Ways and Means Education",
        "position": "Member",
        "type": "committee member"
      },
      {
        "term": "2015-2018",
        "committee_id": "ALC000037",
        "chamber": "lower",
        "state": "al",
        "subcommittee": null,
        "committee": "Baldwin County Legislation",
        "position": "Member",
        "type": "committee member"
      }
    ]
  },
```

**Comment by jamesturk** [comment]
and as for committees, it is likely that quite a few of these are inter-session which does weird things w/ committee memberships, i'm still unclear if that is the main issue that you're reporting though- more clarification would be helpful

**Comment by jamesturk** [comment]
can you give an example API call or something similar?  I just double checked a few of these states and all have roles

**Comment by jketch836** [comment]
This is one from FL. It has a role value, but only the party affiliation, not committees. 
 
{
    "id": "FLL000464",
    "roles": [
        {
            "term": "2017-2018",
            "end_date": null,
            "district": "81",
            "chamber": "lower",
            "state": "fl",
            "party": "Democratic",
            "type": "member",
            "start_date": null
        }
    ],
}

**Comment by jketch836** [comment]
this is the url that I am using. 
https://openstates.org/api/v1/legislators/?state=fl&active=true&apikey="api-key-here"

**Comment by jamesturk** [comment]
committee data can be added in openstates/people, closing this one in favor of those
