### ISSUE TITLE
NC - small phone/fax fix for a legislator

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1923]
State: NC  

https://openstates.org/api/v1/legislators/NCL000202/?apikey=<KEY>

NCL000202 has a phone and a fax in the phone field, and no fax -- {"fax": null, "name": "District Office", "phone": "(919) 715-8293; (919) 754-3296 (FAX)", "address": "16 West Jones Street, Room 1026, Raleigh, NC 27601-1096", "type": "district", "email": null}], "suffixes": ""}

**Comment by jamesturk** [comment]
this will now be handled via openstates/people, there's still some stale data in billy but the postgres database is in much better shape so marking these as obsolete
