### ISSUE TITLE
OH: legislator has incorrect phone number

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#1925]
State: OH

https://openstates.org/api/v1/legislators/OHL000380/?apikey=<KEY>

OHL000380 has a 'phone' set to '11th floor'

 "offices": [{"fax": "614-719-6955", "name": "Capitol Office", "phone": "11th Floor", "address": "77 S. High St\n11th Floor\nColumbus, OH 43215", "type": "capitol", "email": "rep52@ohiohouse.gov"}], "suffixes": ""}

**Comment by julianedwards** [comment]
This is a problem with George F. Lang's page on the OH house web page: http://www.ohiohouse.gov/house/george-f-lang

**Comment by jamesturk** [comment]
fixed
