### ISSUE TITLE
Bad link in ME committees.py

### ISSUE THREAD

**Issue by julianedwards** [openstates/openstates#1931]
State: ME  

Found a bad link in the committees.py file for ME:
http://www.maine.gov/legis/house/commlist.xls does not exist anymore.
<img width="456" alt="screen shot 2017-10-07 at 6 47 29 pm" src="https://user-images.githubusercontent.com/16562432/31312397-00c28f60-ab90-11e7-8ffd-a15f4079586b.png">

I can replace it with http://legislature.maine.gov/house/commlist.xlsx and make a pull request. The format is the same as the excel sheet in the previous link.

**Comment by jamesturk** [comment]
thanks, if you could make a PR that'd be great
