### ISSUE TITLE
TN: 106th legislative session bills duplicates 109th session?

### ISSUE THREAD

**Issue by alexander-poon** [openstates/openstates#1955]
First, thanks for putting together this great data source!

I'm working with Tennessee's data and I'm noticing that bills listed for the 106th legislative session are the same as those listed for the 109th. For instance, here are the two bills as HB 10 for the 106th and 109th, respectively:

https://openstates.org/tn/bills/?search_text=HB+10&session=106&sponsor__leg_id=&type=
https://openstates.org/tn/bills/?search_text=HB+10&session=109&sponsor__leg_id=&type=

As per the Tennessee general assembly's website, the listed bill is correct for the 109th session:

http://wapp.capitol.tn.gov/apps/Billinfo/default.aspx?BillNumber=HB0010&ga=109

This is the bill listed as HB 10 for the 106th:

http://wapp.capitol.tn.gov/apps/Billinfo/default.aspx?BillNumber=HB0010&ga=106

This duplication looks to be true for all of the 106th bills, e.g.:

<img width="776" alt="screen shot 2017-11-05 at 1 39 21 pm" src="https://user-images.githubusercontent.com/12886531/32418396-cba816fa-c22e-11e7-9b2b-3da347842dbc.png">

**Comment by jamesturk** [comment]
this is indeed odd, this was probably a mistake when we scraped 109

I guess this means we don't have data for the 106th, but if so we should purge that session from our data

**Comment by jamesturk** [comment]
deleted 106th
