### ISSUE TITLE
NY: No 2017 bills contain any Assembly votes

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1960]
There are separate issues (#1384 , #1831) about missing roll calls.  This is about there being no 2017 Assembly votes at all in any bills.  I presume the other issues will remain after this is fixed, hence the new issue.

**Comment by estaub** [comment]
Example:
https://openstates.org/ny/bills/2017-2018/A40001/#votes

Source vote:
http://nyassembly.gov/leg/?default_fld=&leg_video=&bn=A40001&term=&Summary=Y&Floor%26nbspVotes=Y

**Comment by jamesturk** [comment]
to clarify, how is this distinct from the two tickets you cited?

**Comment by estaub** [comment]
The other issues pre-existed, and are about individual legislator roll call yea/nay's being missing.  This issue is about there being no Assembly votes at all under any bills.  

I'm guessing that these have different causes, since this one started happening later.

**Comment by estaub** [comment]
AFAICT, there is no code for scraping Assembly votes.  The Billy code was not migrated to Pupa.  @jmcarp, do you recall whether there are issues with the NY source data that make Assembly vote scraping impossible or prohibitively difficult?  See [this commit](https://github.com/openstates/openstates/commit/c29e88790b3f462c854539de9bc7144928ed2517#diff-c0b833d744907b858a610c3983ecd2c8), file `models.py`,  to see the stripped code.

**Comment by jamesturk** [comment]
finally got a chance to look at this, NY Assembly bill scraping is definitely broken, we need to remove the whole ny/models.py thing that isn't working and add a new scraper

**Comment by schedutron** [comment]
Can I work on this issue?

**Comment by schedutron** [comment]
@jmcarp Why did you remove the `_build_*` methods from `models.py` in [this commit](https://github.com/openstates/openstates/commit/c29e88790b3f462c854539de9bc7144928ed2517#diff-c0b833d744907b858a610c3983ecd2c8L58)?

**Comment by In-vincible** [comment]
Looking at this one.
