### ISSUE TITLE
MO: Missing veto-day vote for HCB 3

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#1961]
I hesitate to post on a single missing vote, but fear it may be a member of a larger class.

This vote: http://www.house.mo.gov/billtracking/bills171/rollcalls/075.003.pdf

is missing from: https://openstates.org/mo/bills/2017/HCB3/#votes

This vote was a veto override on a veto day.  It wouldn't surprise me if maybe we tend to miss those.

**Comment by jamesturk** [comment]
#1907 addresses this more broadly
