### ISSUE TITLE
SC: running out of memory reading 93MB agenda PDF in "event" scrape.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2000]
As seen in [bobsled](http://bobsled.openstates.org/run-SC-2017-12-07.html).

The offending PDF is http://www.scstatehouse.gov/agendas/122j7473.pdf .
I don't understand the code well enough yet to be sure, but I suspect the pdf is being incorrectly assumed to be text and read as such; see the stack trace from bobsled, above.

@jamesturk Any thoughts on best approach here?  Some options:

- shut off events in SC
- skip PDFs
- skip this PDF only
- make it work

**Comment by jamesturk** [comment]
SC events are turned off now
