### ISSUE TITLE
MI: Some senator photo URLs not being scraped

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2008]
The Michigan Senate does host photos of senators, but they're not being correctly scraped right now. Looks like the scraper tries to put together photos using the Democrat and Republican caucus websites as its source, but it doesn't work.

See photos here: http://www.senate.michigan.gov/senatorinfo_complete.html

**Comment by mileswwatkins** [comment]
To clarify, OS.org does have manually-input photos for MI senators, but the scraper doesn't retrieve them now, and they are not available on the API.

**Comment by narendra36** [comment]
Can I work on this issue ? if yes In which file(committees/people) should I look into ? and Could you please tell me from where I can read about scraper which is used to scrape the data? @jamesturk

**Comment by narendra36** [comment]
How can I cross check whether I'm getting senator photo URLs or not ? @jamesturk

**Comment by mileswwatkins** [comment]
@narendra36, this is an issue with the `image` property of the `Person` object.

**Comment by narendra36** [comment]
Actually for scraping senator's photo url code is not written previously so had written code for this and I'm scraping senator's photo url from above url given by you. I have fixed it and made a pull request and recently reviewed by jamesturk.  @mileswwatkins
