### ISSUE TITLE
Florida Legislators that resigned show as active

### ISSUE THREAD

**Issue by nicholasrusso** [openstates/openstates#2013]
State: Florida

Hello,

I noticed that the Florida Senator Jose Diaz resigned but he is still listed as active. Is this intentional? 

This is the API call I used: https://openstates.org/api/v1/legislators/?state=fl&active=true&apikey=(API KEY)

Here is the Florida website showing legislators: http://www.myfloridahouse.gov/Sections/Representatives/representatives.aspx?LegislativeTermId=87

**Comment by jamesturk** [comment]
this is now fixed, sorry for the delay!
