### ISSUE TITLE
KS: failing reading committees

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2014]
This problem has existed since at least November 30.

Committee detail scrapes are http failing in a semi-reproducible way.
While the bobsled logs do not show this, when I ran this myself, I got several intermittent recovered failed requests, followed by a 429 "too many requests" error (NOT using --fastmode), which may be relevant.  Changing the request rate to 30/minute resulted in a clean run locally.  PR pending.

**Comment by estaub** [comment]
Sorry, this is a dupe of #1739.

**Comment by Amritpal363** [comment]
Good morning 🙏🌹 india punjabi city code 143604

![Image](https://github.com/user-attachments/assets/c9f16486-1e3a-4c1c-80db-1e124b32015f)
