### ISSUE TITLE
Florida committees are missing members.

### ISSUE THREAD

**Issue by nicholasrusso** [openstates/openstates#2016]
State: FL  

All committees (house, senate, and joint) have no members.

ex: https://openstates.org/api/v1/committees/FLC000162/?state=fl&apikey=XXXXXX
{
"members": [],
"created_at": "2017-02-24 03:14:27",
"updated_at": "2017-07-07 04:10:08",
"all_ids": [
"FLC000162"
],
"parent_id": "FLC000101",
"state": "fl",
"sources": [
{
"url": "http://www.flsenate.gov/Committees/Show/AFT/"
}
],
"subcommittee": "Subcommittee on Finance and Tax",
"committee": "Appropriations",
"chamber": "upper",
"id": "FLC000162"
}

**Comment by jamesturk** [comment]
people can now be added via openstates/people
