### ISSUE TITLE
Regex timeout

### ISSUE THREAD

**Issue by 2bdenny** [openstates/openstates#2020]
I test regexes in the project, and find out two of them may suffer from timeout.

https://github.com/openstates/openstates/blob/master/openstates/oh/events.py#L36
For this regex `\n((?:\w+\s?)+)\n`, a long sentence with punctuation in the first event would be time costly. Such as `\nJoint Committee on Agency Rule Review Presided over by Mrs.Smith\n1:30 pm, Room 121, Chair: Duffey\n\n`
The regex could be replaced by `\n(\w+|(?:\w+\s)+\w+)\n`, without any functionality loss.

https://github.com/openstates/openstates/blob/master/openstates/oh/events.py#L108
For this regex `\n\n((?:\w+\s?)+),\s`, a long sentence without any `,` at the end in the first event would be time costly. Such as `\n\nControlling Board, 1:30 PM, North Hearing Room\n\n\nDelicious cake and coffee are available\n\n`
The regex could be replaced by `\n\n(\w+|(?:\w+\s)+\w+),\s`, without any functionality loss.

**Comment by jamesturk** [comment]
we're actually in the process of deprecating all events scrapers- to be
clear though are you running into issues running these yourself?

**Comment by 2bdenny** [comment]
Such cases do exist in practice and may stuck the crawler, though rare in practice, and maybe not worthing fixing if it's deprecating.

BTW, since we don't know which regex may timeout on which pages, it'd nice to add a timeout to prevent openstates from stucking in case that many regexes are matched.
