### ISSUE TITLE
Kansas: Missing action code

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#2025]
State: KS

KS has added an action code to their API that isn't in the scraper, and isn't listed in their (documentation)[http://www.kslegislature.org/klois/includes/kliss_restian_interface_guide_v11.pdf].
```00:05:23 WARNING pupa: unknown action code on SB251: ref_rbc_311 Referred to```

I've emailed the legislature IT to get information on the code or new docs, I'll update the ticket and PR when they answer.

**Comment by jamesturk** [comment]
wanted to double check on this, did you hear back?

**Comment by showerst** [comment]
Nope, so feel free to close i guess?

**Comment by estaub** [comment]
Can you guess it out from the action history on example bills?  

I'm guessing that it means "referred to committee", probably only one of these two meanings:

- in initial bill processing, it's assigned to a committee
- after getting out of committee, the floor votes to assign it either back to the original committee or to another (often the fiscal committee)

(but you know all this already, I think, so I'm puzzled)

**Comment by showerst** [comment]
@estaub yeah thanks for the writeup though! I was just trying to keep it to the official source since they have everything else really nicely documented and we can use the official language.

I'll take a look tomorrow or the next day and try to guess it, shouldn't be a big deal.
