### ISSUE TITLE
KY, others: Classification for "Became law without governor's signature"

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#2027]
State: KY, others  (be sure to include in ticket title)

Some states (like [Kentucky](http://www.lrc.ky.gov/record/17RS/law.htm)) allow bills to become law without the governor signing them. What's the correct [action type classification](http://opencivicdata.readthedocs.io/en/latest/scrape/bills.html) there?

**Comment by estaub** [comment]
Looks like `veto-override-passage` to me.

**Comment by estaub** [comment]
[The governor must sign or veto legislation within 10 days of the day following transmittal (excluding Sunday), or it becomes law without his/her signature. ](http://www.statescape.com/resources/legislative/bill-signing-deadlines.aspx)

Seems like it needs a new action to me.

**Comment by jamesturk** [comment]
Hmm, yeah seems like a new one might be appropriate here. Any suggestions?

**Comment by estaub** [comment]
"become law without signature" and "pocket signature" seem common.

**Comment by showerst** [comment]
how about "executive:law-without-signature" ?

As long as i have you on the topic @jamesturk  -- if i wanted to add an action for the states that give public law citations, could I add something like "executive:became-law" or "executive:code-citation" ?

Should this be at the OCD level, or just an openstates PR?

**Comment by jamesturk** [comment]
I like executive:became-law -- would that work for both?

**Comment by showerst** [comment]
That will work for the action -- it looks like it depends on the state whether the legal citation is in the same action where it became law; maybe that's better just put into the extras field anyway.
