### ISSUE TITLE
IA: Add committee positions to People scraper

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2043]
The Iowa People scraper currently doesn't capture committee membership. This should be an easy add; their legislator pages include a list of all committees they're a part of, eg:

- https://www.legis.iowa.gov/legislators/legislator?ga=87&personID=10738
- https://www.legis.iowa.gov/legislators/legislator?ga=87&personID=140

**Comment by narendra36** [comment]
@mileswwatkins I have few questions regarding this issue:
1. In which field of Person model will membership be added ? it would be great if there is any sample/example in any state data.
2. Should we include all type of committees? 
3. Only the name of committees is sufficient or I have add link also?

**Comment by mileswwatkins** [comment]
1. Here are the places where we've scraped `Organization`s from within `people.py` scrapers; some of these should be good models. Note that the committee memberships _are not_ a property of the `Person` object; rather, the person scraping module `yield`s _both_ `Person` _and_ `Organization` objects.
```
$ grep -nr openstates/*/people.py -e "Organization"
openstates/al/people.py:4:from pupa.scrape import Scraper, Person, Organization
openstates/al/people.py:189:                comm = Organization(
openstates/ct/people.py:2:from pupa.scrape import Person, Scraper, Organization
openstates/ct/people.py:126:                        com = Organization(comm_name, classification='committee', chamber=chamber)
openstates/hi/people.py:1:from pupa.scrape import Person, Scraper, Organization
openstates/hi/people.py:211:                    comm = Organization(name=ctty['name'], classification="committee",
openstates/oh/people.py:3:from pupa.scrape import Person, Scraper, Organization
openstates/oh/people.py:119:                org = Organization(
openstates/sc/people.py:3:from pupa.scrape import Person, Scraper, Organization
openstates/sc/people.py:135:                    com = Organization(name=committee, classification='committee',
openstates/sd/people.py:3:from pupa.scrape import Person, Scraper, Organization
openstates/sd/people.py:126:            self._committees[key] = Organization(name=name,
openstates/va/people.py:8:from pupa.scrape import Organization
openstates/va/people.py:68:                org = Organization(
```
2. We should capture whatever committees are exposed on the legislators' pages.
3. You should add as full information as you can regarding the committee `Organization` object. See the related, existing examples.
