### ISSUE TITLE
NH: inactive legislators marked as active

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2066]
NH is showing 5 extra active legislators.

```
'District upper 16 has 1 too many active legislators: Cavanaugh, McGilvray',
'District lower Sullivan 1 has 1 too many active legislators: Oxenham, Schmidt, Sullivan',
'District lower Strafford 13 has 1 too many active legislators: Epstein, Conley',
'District lower Rockingham 4 has 1 too many active legislators: Lerner, Edwards, Polewarczyk, Osborne, True, Hagan',
'District lower Hillsborough 15 has 1 too many active legislators: Connors, Katsiantonis, Vaillancourt',
'District lower Belknap 9 has 1 too many active legislators: Fisher, St. Clair',

```
The inactive legislators, in order, are

- McGilvray
- Schmidt
- Epstein
- Polewarczyk
- Vaillancourt
- Fisher

The scrape is not retrieving these now; the database needs to be tweaked, afaict.

(Background suggestion.) A good diagnostic for legislator issues is to check that each district has the correct number of active legislators.  VT has some issues right now that would be flagged by this; see #2024.  Where the current scrape is returning the correct number of legislators for a district, this can be used to inactivate the surplus legislators

**Comment by mileswwatkins** [comment]
I've manually cleaned up these legislators. Pupa/OCD fortunately have some nicer data quality tools, and @jamesturk and I are also looking into ways to further improve production too-many-legislators notifications in this area: https://github.com/opencivicdata/pupa/issues/306
