### ISSUE TITLE
NY: Committees missing, at least for upper chamber

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2067]
h/t John Ferrara

Committees appear to be present in the mid-2017 bulk downloads, but none are present in the API right now. Committee scraper appears to be activated, but probably has a bad LXML query.

**Comment by narendra36** [comment]
Hi @mileswwatkins I was working on this. I find out that committees for upper chamber is scraped correctly but I think problem is for lower chamber. What do you think?  Am I right?

**Comment by mileswwatkins** [comment]
@narendra36, yup, looks like upper-chamber committees are working now, and now it's just lower-chamber committees missing.

**Comment by narendra36** [comment]
link : http://assembly.state.ny.us/comm/
@mileswwatkins Should I scrape only standing committees or subcommittees also or any commissions etc. ?

**Comment by mileswwatkins** [comment]
For committee data, we need:

- member names
- chairperson name
- if subcommittee, which committee is the parent

It seems like _only_ the standing committees have this information, right? I can't see a way to determine the parent committee of the subcommittees, and many of the subcommittees, commissions, and task forces have no member information whatsoever.

**Comment by narendra36** [comment]
Yes! It's only available for standing committees so I just need to scrape only for standing committees, right?

**Comment by narendra36** [comment]
@mileswwatkins we should close this issue.

**Comment by mileswwatkins** [comment]
@narendra36, cool tip for the future: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by narendra36** [comment]
Great! I will use these tips from now on :)
