### ISSUE TITLE
AR: committee scraper needs work.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2068]
The scraper needs to get the committee list from http://www.arkleg.state.ar.us/assembly/2017/2018F/Pages/Committees.aspx, a Sharepoint page.  The problem is that the currently-selected “Joint/House/Senate/Task Force” tab isn’t reflected in the URL, and the entire page is reloaded when a tab is selected, with only the data for the selected tab sent to the browser.  

@showerst noted that the approach needed is similar to that for [bills in Alabama](https://github.com/openstates/openstates/blob/master/openstates/al/bills.py).  In Chrome DevTools or similar, see the form data on the POST to Committees.aspx for each reload.

The task-definition https://github.com/openstates/task-definitions/blob/master/tasks/ar.yml only scrapes bills.

**Comment by jamesturk** [comment]
we'll now handle committees via openstates/people
