### ISSUE TITLE
IL: Committee scraper IDs need updating, committee scraper deactivated

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2076]
I'm going to temporarily deactivate the IL committee scraping; their committee IDs all changed. Someone needs to go through https://github.com/openstates/openstates/blob/master/openstates/il/_committees.py and update that set of committees and their IDs (eg, House Aging at the top of [the house committee list](http://ilga.gov/house/committees/default.asp) used to be ID `103`, but now it's ID `2169`). Then they'll need to re-enable the committee scraper lines in the Illinois Task Definition file (https://github.com/openstates/task-definitions/blob/master/tasks/il.yml).

**Comment by narendra36** [comment]
@mileswwatkins Why this COMMITTEES dictionary is hard coded ? Can we add a script to scrape this form [here](http://ilga.gov/house/committees/default.asp) instead of hard coding values?

**Comment by mileswwatkins** [comment]
@narendra36, the long comment in `_committees.py` explains this a bit, regarding handling different names for the same committee. Does that approach make sense to you?

**Comment by jamesturk** [comment]
will now be handled in openstates/people
