### ISSUE TITLE
MD: Rewrite vote scraping

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2093]
Looks like Maryland has started serving its floor votes as PDFs, rather than HTML. For example:

- 2018 bill: http://mgaleg.maryland.gov/webmga/frmMain.aspx?pid=billpage&stab=02&id=hb0001&tab=subject3&ys=2018RS
- bill from earlier session: http://mgaleg.maryland.gov/webmga/frmMain.aspx?pid=billpage&stab=02&id=sb0001&tab=subject3&ys=2016rs

So, I've stripped out the vote scraping for now. It will need to be rewritten from scratch.

Note that while the source table _does_ provide vote result, vote counts, and date, this _cannot_ be used to build a `VoteEvent` in the meantime, since the date provided is the legislative day, not the calendar day.

**Comment by tabshaikh** [comment]
@mileswwatkins so in this issue we have to build a scrapper from scratch which picks up the details of a bill from a pdf

**Comment by In-vincible** [comment]
@mileswwatkins should I look into this?

**Comment by mileswwatkins** [comment]
Go for it! But it looks like it's going to be a messy PDF scrape, so get ready :|

Check out the `pupa.utils` PDF conversion utility; that has different modes/settings that can try parsing PDFs into somewhat-structured formats. No promises it'll work here, but it's a possibility.

And make sure that you don't try to scrape the _committee_ votes; those look like they're really bad, _hand-written_ scans, which would be an even bigger pain. This GitHub Issue should only cover floor votes, I think.
