### ISSUE TITLE
MT: Switch committee scraper to use structured HTML, rather than PDF scrape

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2098]
Montana now serves its committees in a clean way, on http://leg.mt.gov/css/Committees/default.asp

**Comment by sriks123** [comment]
@mileswwatkins can I work on this issue?

**Comment by mileswwatkins** [comment]
@sriks123, go for it; this is a good starter issue. Submit a pull request when you've got this working.

**Comment by sriks123** [comment]
@mileswwatkins can you explain how to get data from http://leg.mt.gov/css/Committees/default.asp? and should the extracted data be same as http://leg.mt.gov/content/Committees/Session/2017-house-committees.pdf format?

**Comment by sriks123** [comment]
@mileswwatkins would you review this and tell me if any changes should be done?

**Comment by jamesturk** [comment]
this will now be handled via openstates/people, there's still some stale data in billy but the postgres database is in much better shape so marking these as obsolete
