### ISSUE TITLE
MT: Re-enable joint subcommittees

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2099]
- The House has a standalone committee named Appropriations, with only House members
- The Senate has a standalone committee named Finance and Claims, with only Senate members
- But together they have _joint subcommittees_, that have both Senate and House members in them

> Joint Appropriations Subcommittees
> Meet during the first part of each session to consider budget bills that appropriate money and give state agencies authority to spend money. They are made up of members from the House Appropriations Committee and the Senate Finance and Claims Committee.

http://leg.mt.gov/content/Committees/Session/2017-house-committees.pdf
http://leg.mt.gov/content/Committees/Session/2017-senate-committees.pdf

Since there are multiple parents to these subcommittees, Pupa can't model them correctly right now. I'm turning off the subcommittee scraping in the meantime.

**Comment by jamesturk** [comment]
will now be handled in openstates/people repo
