### ISSUE TITLE
Add vulture script to Travis checks

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2132]
Add the Vulture dead-code-finding script (`scripts/vulture.sh`) to the `.travis.yml`. No-go right now, since Vulture picks up a handful of cases of bad code already in the project.

Know this was an aspirational item for you @jamesturk, wanted to get it down on our issue tracking.

**Comment by jamesturk** [comment]
see #1704

**Comment by mileswwatkins** [comment]
Ahh, knew this conversation had been had somewhere, but I couldn't find it.
