### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by Cyyy1998** [openstates/openstates#2137]

**Comment by mileswwatkins** [comment]
@Cyyy1998, thanks for reaching out. Can you clarify this issue? Is this for the Open States docs, the Open States website, or something else?

(@heyitsolivia, @jamesturk: maybe internationalization is something we should build into the new OS.org.)

**Comment by Cyyy1998** [comment]
For open state docs i want to translate it to my natuve language which is filipino

**Comment by jamesturk** [comment]
while we appreciate the offer to be honest I don't think there's a huge audience for that given the nature of the project and there might be better uses of your translation abilities.  that said, if you want to, our docs are here: https://github.com/openstates/documentation and you are more than welcome to submit a PR there 

going to close this one as the scrapers themselves don't have anything to translate
