### ISSUE TITLE
AR: Look into using structured data for Person and Committee scraping

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2138]
Currently scraped from LXML parsing of HTTP pages, much of the data is probably available in ftp://www.arkleg.state.ar.us/SessionInformation TXT files. Will take a bit of detective work, looking through the fields and READMEs.

**Comment by sriks123** [comment]
@mileswwatkins can I want to work on this issue?

**Comment by jamesturk** [comment]
this will now be handled via openstates/people, there's still some stale data in billy but the postgres database is in much better shape so marking these as obsolete
