### ISSUE TITLE
ME: Incorrectly handling deceased legislator and her replacement

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2154]
(Moving over @yocheved's issue from the docs repo: https://github.com/openstates/documentation/issues/48)

Gina Mason died in 2017, and has been replaced by Richard Mason. However, Open States is not capturing Richard as the active legislator for Maine's House of Representatives seat 56.

Here's where the state site shows Gina and Richard's information, including death date and special election information. This is the webpage that we scrape, so it looks like we need to make an adjustment to the People scraper so that it can handle deceased and replacements. http://legislature.maine.gov/house/dist_mem.htm

**Comment by sriks123** [comment]
@mileswwatkins do we have to store both Gina M as deceased and Richard M as active

**Comment by mileswwatkins** [comment]
No, Gina Mason is not active; only Richard Mason should be scraped.

**Comment by sriks123** [comment]
Yes I have implemented accordingly and made a PR can you review it?
