### ISSUE TITLE
WY: `get_session_list` can never "see" current session

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2156]
Wyoming's `jurisdiction.get_session_list` method looks at [the session-archive webpage](http://legisweb.state.wy.us/LSOWeb/SessionArchives.aspx); it never sees the current session's name, so it won't serve its purpose of throwing an error when that new session isn't scraped.

**Comment by shreyakupadhyay** [comment]
@mileswwatkins Do I need to use the "legislative_sessions" list and check with the current session listed on the legislature website?

**Comment by mileswwatkins** [comment]
Yeah, I'd grab the current session name from http://legisweb.state.wy.us/LSOWEB/Session/SessionHome.aspx, and then append it to the session-archive's list.

**Comment by jamesturk** [comment]
this one is obsolete since the page in question is gone
