### ISSUE TITLE
WY: Fix session naming

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2157]
Wyoming names its even-year sessions "Budget Sessions" (eg, `2016 Budget Session`); see their descriptive text about sessions here: http://legisweb.state.wy.us/LSOWeb/SessionArchives.aspx. Budget Sessions are `primary` sessions that are on similar footing to General Sessions, but just named differently (and are shorter, etc). [There is a note in `billy_metadata`](https://github.com/openstates/openstates/blob/master/billy_metadata/wy.py#L75-L78) that contradicts this (stating that Budget Sessions are just for HB 1, the appropriations bill), but it appears to be inaccurate; [2016 Budget Session's bills](http://legisweb.state.wy.us/2016/billreference/BillReference.aspx?type=ALL) are discrete from [2017 General Session's bills](http://legisweb.state.wy.us/2017/billreference/BillReference.aspx?type=ALL), which are discrete from [2018 Budget Session's bills](http://legisweb.state.wy.us/2018/billreference/BillReference.aspx?type=ALL).

Open States seems to have invented even-year "General Sessions" (eg, `2016 General Session`), which don't exist in practice. That is, the `_scraped_name` of `2016 General Session` does not exist anywhere on the state's website, but this session does exist in `__init__.py`:

```
{
   "_scraped_name": "2016 General Session",
    "classification": "primary",
    "identifier": "2016",
    "name": "2016 General Session"
}
```

and this session is in `ignored_scraped_sessions`:

`"2016 Budget Session"`

even through the 2016 "General Session" is really a "Budget Session."

No huge priority to fix since it doesn't break anything for Open States, just a freakin' pain that we're out of sync with the Wyoming legislature on session semantics.

**Comment by jamesturk** [comment]
looks like we match the site now
