### ISSUE TITLE
ME: Switch to using spreadsheet data, for lower-chamber People scraping

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2158]
Currently, we scrape HTML for Maine's House of Representatives. Scraping this HTML list has gotten a bit dicey as special cases pop up, such as a during-term special election to replace a deceased member:

<img width="536" alt="screen shot 2018-02-20 at 11 26 53" src="https://user-images.githubusercontent.com/4959135/36441813-fb712c2c-1630-11e8-8388-f58306b27b4d.png">

Fortunately, the House publishes an Excel spreadsheet of members, that is much cleaner and already handles the special cases. We should switch to scraping that spreadsheet instead of parsing the HTML. The spreadsheet is available here: http://legislature.maine.gov/house/128house.xlsx

cc https://github.com/openstates/openstates/pull/2155

**Comment by sriks123** [comment]
I am working on this.

**Comment by shreyakupadhyay** [comment]
@sriks123 as you are already working on this issue, I won't be working on this. I just wanted to know that, the link provided by @miles downloads the spreadsheet and that can be used directly for the data. Are you using something like Dataframe to parse it or is there any other way which you are using?

**Comment by mileswwatkins** [comment]
We prefer to use `xlrd` to open Excel files, or the Python-native `csv` to open CSV files. Using a "smarter" import, like those from Pandas or BeautifulSoup, can make incorrect assumptions about the structure or type of a column, and thus introduce data quality bugs.

**Comment by shreyakupadhyay** [comment]
Thanks @mileswwatkins that helps.
