### ISSUE TITLE
WY: Switch to scraping new website

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2163]
The Wyoming legislature has a new website going up. It's currently in beta, so we should probably not prioritize switching scrapers to it yet, but it's unclear what their timeline is or what "beta" entails in their context; it seems to be fairly stable already.

http://lso.wyoleg.gov/

(Old website was http://legisweb.state.wy.us/)

**Comment by sudhanshuchopra** [comment]
@mileswwatkins  are we considering to make a switch or its an issue for discussion?
And if yes I would like to do it.

**Comment by mileswwatkins** [comment]
@sudhanshuchopra and I talked on Slack, but noting here for others: this should be a lower priority than missing/broken vote scrapers.

**Comment by showerst** [comment]
It looks like this website is powered by some JSON endpoints, which is great. 

For those looking at writing a scraper: load the site, open chrome dev tools, and filter the network tab by XHR. I see some calls to http://wyoleg.gov/LsoService/api/<endpoint> that we can probably use. They seem to give JSON on the website, and XML if you just cut and paste the URLs into your browser, probably based on the 'Accept' request header.

**Comment by sudhanshuchopra** [comment]
Not a problem have scraped websites that use AJAX before

**Comment by mileswwatkins** [comment]
This is truly magical, _everything_ is structured, even roll call names and legislator photo URLs and primary-ness of sponsorships.

**Comment by showerst** [comment]
Does anyone have a WIP branch for this i could take? Otherwise i might get started on a new one from scratch soon.

**Comment by jamesturk** [comment]
@showerst OK to close?
