### ISSUE TITLE
Some VT reps not coming up correctly

### ISSUE THREAD

**Issue by yocheved** [openstates/openstates#2166]
1. Christopher Chris Mattos house VT shows up inactive instead of Ronald E. Hubert who is supposed to be inactive but is active

 2. David Soucy senate VT shows up inactive instead of Kevin Mullin who is supposed to be inactive but is active

3. James Jim Harrison house VT shows up inactive instead of Job Tate who is supposed to be inactive but is active

**Comment by estaub** [comment]
Miles, be aware of https://github.com/openstates/openstates/blob/master/openstates/vt/people.py#L27 - probably not relevant, but just in case.

**Comment by jamesturk** [comment]
this will now be handled via openstates/people, there's still some stale data in billy but the postgres database is in much better shape so marking these as obsolete
