### ISSUE TITLE
AR: API returning rep from wrong chamber

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#2169]
State: AR

This URL (with API key added):

https://openstates.org/api/v1/legislators/?state=ar&chamber=upper

Returns as its first result the record for ARL000026, which is a lower chamber rep.  Interestingly "chamber": "lower" is there in the data and the same record is returned from a request for chamber=lower.  This bug may have some variability over time - yesterday there was more than one but I can't reproduce them today.

**Comment by mileswwatkins** [comment]
@jamesturk, thoughts on this? The only thing weird with [this lower-chamber legislator in question](https://openstates.org/admin/object_json/legislators/ARL000026/) is that they (probably erroneously) have upper-chamber committee `roles`. My hunch, based on reading the Billy API handler, is that Billy looks for _any_ chamber=upper role in a legislator's `roles` list, without first filtering down `roles` to just non-committee positions. (If so, I can just manually strip the incorrect committee positions in the database.)

**Comment by jamesturk** [comment]
that sounds right to me, but I haven't had a chance to confirm- stripping the bad positions seems like the solution here

**Comment by jamesturk** [comment]
fixed in v1
