### ISSUE TITLE
CA scrape can't find mysql, README directions not working

### ISSUE THREAD

**Issue by earthmancash2** [openstates/openstates#2177]
State: CA 

When running the directions in the readme for CA, the scrape isn't able to find the mysql db, and won't ignore the mysql step with the --scrape flag.

```
docker-compose run --rm scrape ca events --scrape

...[downloads stub posts for senators/assemblymen]...

  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 410, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/opt/openstates/venv-pupa/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (2005, "Unknown MySQL server host 'mysql' (0)")
```

I saw the directions that @jmcarp [wrote up](https://github.com/jmcarp/openstates/blob/33db2e0847e28b58729829dd10da3185565996cb/openstates/ca/README.rst) for how to pull CA data, but I'm not sure it matches the current configurations. When following those directions, I get:

```
$ docker-compose run --entrypoint python openstates -m openstates.ca.download
ERROR: No such service: openstates
``` 

I saw in the [docker-compose.yaml](https://github.com/openstates/openstates/blob/master/docker-compose.yml#L18-L26) that the opensecrets service name is now "opensecrets.org" instead of "opensecrets". When I change that, I get a bunch of "Pull Complete", and a "Status: Downloaded newer image for openstates/openstates.org:latest", but then I get:

```
/usr/local/bin/python: No module named ca
```

I'm not sure why that's happening, as `opensecrets/ca/__init__()`  I *think* [looks ok](https://github.com/openstates/openstates/blob/master/openstates/ca/__init__.py)

Can someone help me out?

**Comment by jamesturk** [comment]
try using ``` [bash, -c, "mysqld_safe & sleep 10 && /opt/openstates/venv-pupa/bin/python /opt/openstates/openstates/openstates/ca/download.py && ./pupa-scrape.sh ca bills people committees"] ``` as your Docker entrypoint
