### ISSUE TITLE
Fixing Vote scraper of md for older sessions

### ISSUE THREAD

**Issue by In-vincible** [openstates/openstates#2188]
State: MD  (be sure to include in ticket title)

Fixing of Vote scraper for older sessions. I am fixing this one too in my PR for new Vote Scraper for MD.
##2186

**Comment by mileswwatkins** [comment]
We should avoid spending our limited resources on maintaining code to scrape past sessions. If it's a quick/painless change, then no worries, but don't spend much time on non-current-session scraping code for now.
