### ISSUE TITLE
mi: Contact link not Working for one or more senator 

### ISSUE THREAD

**Issue by In-vincible** [openstates/openstates#2189]
Main link is : http://www.senate.michigan.gov/senatorinfo_list.html
In this contact link of johnson is broken. we are only loosing email because of this. But we may want to look into this, if we want other source or do something about it, though looks low priority to me. The PR referencing this issue is not solving this issue.

**Comment by mileswwatkins** [comment]
@In-vincible, is Johnson supposed to be there, and is not present (eg, they're a new member to the legislature, and their page hasn't been created yet)? Or is Johnson an outgoing member, and they _shouldn't_ be present?

**Comment by In-vincible** [comment]
He resigned 3 days ago, but he is still present in the main list, but his contact link is broken.

**Comment by mileswwatkins** [comment]
Okay, then this'll go away soon, and he's no longer active/significant anyway. Going to close this issue, but good thinking regarding opening it up!
