### ISSUE TITLE
Several states: Assign seat count to multi-member Posts

### ISSUE THREAD

**Issue by mileswwatkins** [openstates/openstates#2208]
As I was building out the website, I realized that Open States doesn't populate the `Post.maximum_memberships` property, which would (for instance) let us know how many seats are vacant in a legislature. This is important, as we often confuse users (and get annoyed feedback) when our senator or representative counts don't line up with the number of seats in a chamber (and we don't say "x seats vacant" or similar).

[There are ten states](https://ballotpedia.org/State_legislative_chambers_that_use_multi-member_districts) that have multi-member districts, so it's not much of an edge case.

This may be a lack of support in Pupa itself. I've tried skimming Pupa's `Post` importer (and searching the full repo) for references to `maximum_memberships`, but no luck. And I notice that the Pupa JSON files don't include any property like that. All the `Post` JSONs that are imported receive the default seat count (of one).

@jamesturk, will this require a Pupa patch, or is this only an Open States issue and there's some way (via kwargs, etc) that Pupa already does support this Open Civic Data field?

cc @heyitsolivia

**Comment by mileswwatkins** [comment]
cc @showerst, since you've done some international OCD work, and may have insight on this too.

**Comment by jamesturk** [comment]
yeah I think we need to add this to Pupa, we have it in py-ocd though so it should be an easy fix

**Comment by jamesturk** [comment]
added a while back :)
