### ISSUE TITLE
CO Districts Wrong for Coordinates

### ISSUE THREAD

**Issue by putorti** [openstates/openstates#2273]
State: CO

User is reporting incorrect state districts for 39.44318286 -107.1668856

OpenStates returns:
57 Bob Rankin and 8 Randy Baumgardner

But https://leg.colorado.gov/find-my-legislator gives her:
26 Dylan Roberts and 5 Kerry Donovan

**Comment by putorti** [comment]
If this is the wrong place to file this sort of thing, my apologies.

**Comment by jamesturk** [comment]
sorry for the delay on this, do you know if CO was redistricted recently? I couldn't find anything about it, but our data is the latest provided by the Census' aggregated State Leg files, we can investigate the discrepancy but I wasn't seeing an court-mandated redraw or anything like that so I'm curious if you're aware of one

**Comment by putorti** [comment]
James, it looks like this has been fixed one way or another, searching for the user's address now returns the correct officials. Thank you.

**Comment by lisabeigel** [comment]
Webhook is not returning what openstates.org has:
https://rapidbot.io/webhooks/log/46708778/

![image](https://user-images.githubusercontent.com/29188059/42187137-9cb207aa-7e14-11e8-96c5-0a602ab00253.png)


User is:
https://rapidbot.io/contact/read/bae10a74-8368-4dc3-877a-01d750df3d34/


I think it's probably that her lat/long is incorrect.  But I don't know how to silently refresh her lat/long.
