### ISSUE TITLE
InsecureRequestWarning log spam

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2285]
Scrape logs for https sites are spammed with this INFO-level message on every HTTPS request:
```
/opt/openstates/venv-pupa/lib/python3.5/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
```

I'm looking for advice about what should be done.  My inclination is to quell the warnings altogether, because I _suspect_ that stale state certs are frequent enough to not want to bother with verification.  I believe (but have not tested) that this can be done in openstates with

```py
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```

If we want to  verify certs, it probably requires changes somewhere up the stack.

**Comment by jamesturk** [comment]
this makes sense, we explicitly disable verification in cases where it caused trouble so it reasons we don't need to reminded of it.
