### ISSUE TITLE
Encoding used in Legislature data structure

### ISSUE THREAD

**Issue by georgezoto** [openstates/openstates#2298]
Hello openstates team,

First off, amazing effort and great job on putting this platform together. I am a new user of your api and I only had a question or suggestion for improvement.

I am looking at the Legislature data structure and specifically the encoding for first, last and full name:
http://docs.openstates.org/en/latest/api/legislators.html#legislator-fields

I do not see any mention of encoding used in these fields. My challenge is with representatives that have accents in their names, for example: https://openstates.org/ca/legislators/CAL000057/kevin-de-leon
This could be the case for other fields too that I have not come across yet.

Instead of users trying to guess what encoding you are using, is it possible to:
1. Update the documentation with this missing piece of information
2. Suggest a clean way to remove accents from your output

Thank you,
George Zoto

**Comment by estaub** [comment]
It's utf-8, as one might guess, according to the response header.

![screen shot 2018-05-11 at 7 27 50 pm](https://user-images.githubusercontent.com/1131334/39950747-8f8226c8-5551-11e8-8d20-6205e618391a.png)

**Comment by georgezoto** [comment]
Thank you @estaub, the encoding seems to be utf-8.  It would be easier if this was explicitly mentioned in the open state api documentation.

Regarding my second question and just as a reference, a utf-8 to ascii conversion process (to remove accents in my case) that I was able to find online is through `unidecode`:

<img width="923" alt="utf-8 accents" src="https://user-images.githubusercontent.com/16548373/40005825-ed589acc-5766-11e8-83f2-36a2fff89966.png">

In the screenshot above, the full name uses `ó | LATIN SMALL LETTER O WITH ACUTE (U+00F3)` encoded as `c3b3` in utf-8. `unicode` transliterates any unicode string into the closest possible representation in ascii text.

References:
https://www.fileformat.info/info/charset/UTF-8/list.htm
https://stackoverflow.com/questions/517923/what-is-the-best-way-to-remove-accents-in-a-python-unicode-string

**Comment by seanthegeek** [comment]
@estaub Looks like this issue can be closed now. Again, I don't have that button in this repo for some reason, even though I have the member badge :(

**Comment by estaub** [comment]
@seanthegeek Don't look at me - I'm a proletarian too ;-)
