### ISSUE TITLE
Missing legislator data from python wrapper even if web service returns data

### ISSUE THREAD

**Issue by georgezoto** [openstates/openstates#2299]
Hello openstates team,

I appreciate your hard work. I recently ran into an issue that is at the intersection of your platform and pyonestates. Specifically my first issue is with:
`pyopenstates.locate_legislators(lat=lat_lng_dict['lat'], long=lat_lng_dict['lng'], fields=my_fields)`

For more context, I was trying to find the upper and lower chamber representatives for several public schools in Ohio. I realized that for many sites (using their lat/long) `pyopenstates.locate_locate_legislators` returned **no results**. 

One sample lat long (I can prove about 500 more) is:
`{'lat': 39.8748, 'lng': -83.185516}`

However, the **open states web service** at: https://openstates.org/oh/ is able to return results.

**Another issue** I noticed is that there are 2 results returned for a given chamber and in reality only one of them is currently its representative.

<img width="918" alt="missing data" src="https://user-images.githubusercontent.com/16548373/39945106-35ad428c-5537-11e8-95b0-572a0432921e.png">

Do you have any ideas of:
1. Why `pyopenstates.locate_legislators` is not able to return an expected result?
2. Why does the open states return 2 representatives for a given chamber?

I am more than happy to support troubleshooting this case together.

Thank you,
George Zoto

**Comment by estaub** [comment]
This is double-posted, both here and at https://github.com/openstates/pyopenstates/issues/7.  If you're going to double-post (usually frowned on), please at least cross-link, so that people don't waste time re-answering.  Also, you've two unrelated issues; please post separately.

Since the web service works right, the lat-long issue is obviously a pyopenstates issue.  You probably should pursue it there.

On the two results for Ohio House District 24, a little googling usually clears up questions like this.  Looking for `Ted Celeste Ohio 24` gets you to https://ballotpedia.org/Ted_Celeste, where you can see that he is a _former_ state rep from the district.  I don't know pyopenstates, but the web api had an `active` boolean which is probably also provided by pyopenstates.

**Comment by estaub** [comment]
> However, the open states web service at: https://openstates.org/oh/ is able to return results.

I'm unclear about whether you actually used the web service.  The URL is that of the web _site_, not the web _service_.  Can you clarify?

**Comment by georgezoto** [comment]
Hi @estaub, I closed the pyopenstate issue and referenced this one instead. The main reason I double posted was that I didn't see any responses there on another issue for a long time. There are no duplicate issues anyone, I followed your instructions and I want to make sure I follow the right protocol. I will respond to the other questions once I get in office on Monday, I appreciate your response.

**Comment by georgezoto** [comment]
Hi @estaub, you were right, the open states api does return a valid response as well as an `active` field for each representative. 

<img width="1170" alt="open states api" src="https://user-images.githubusercontent.com/16548373/40004141-115352ae-5763-11e8-8190-bf781a2b323e.png">

For some reason pyopenstates.locate_locate_legislators for {'lat': 39.8748, 'lng': -83.185516} returned no results and as you suggested I will pursue it there or stop using it overall and just use the open states api.

One last clarification I needed: Does the open states `website` use the open states `web service/api` in the backend for all related queries e.g: https://openstates.org/find_your_legislator/?abbr=oh&lat=39.8748&lon=-83.185516

Thank you,
George

**Comment by estaub** [comment]
@georgezoto Sorry, I've not worked on the website and have no insight.  If no one else answers, study of the source - even just a search for `find_your_legislator` - might provide an answer.  There are two projects, openstates.org and new-openstates.org; I've no idea which is the live site.

**Comment by estaub** [comment]
No, I'm not talking about the URL, I'm talking about the code behind it.  I don't know whether https://openstates.org/ runs off https://github.com/openstates/openstates.org or https://github.com/openstates/new-openstates.org.

**Comment by georgezoto** [comment]
I see, so open states api v1 versus v2 for the backend service. Not sure either, does someone else know here?

**Comment by seanthegeek** [comment]
@estaub `pyopenstates` does indeed return the full JSON objects, including the `active` flag. @georgezoto [The documentation](https://github.com/openstates/pyopenstates/blob/master/pyopenstates.py#L266) for `pyopenstates` mentions that the legislator lookup only returns active legislators (unless you set `active=false`) to avoid confusion.  

As for the lat/long issue, I'll take a look this weekend. `pyopenstates` is a hobby project, and I am the sole developer. I have not touched the code for nearly a year.  Closing an issue after three days actually makes it less likely that I will eventually see it, as I typically only look at open issues.

**Comment by georgezoto** [comment]
Appreciate it @seanthegeek, let me know if I can help, I have several lat/longs that are not returning any results. I can also open a new issue in pyopenstates for more information. Thank you again.

**Comment by seanthegeek** [comment]
@georgezoto I tested the exact coordinates you provided, and it works. Were you passing them as strings instead of floats? I went ahead and uploaded a new version on `pywhoxmlapi` (1.1.1) to avoid that problem anyway.

```python
from pprint import PrettyPrinter

import pyopenstates

pretty = PrettyPrinter(indent=2)

pretty.pprint(pyopenstates.locate_legislators(39.8748, -83.185516))
``` 

```python
[ { '+biography': 'Senator Stephanie Kunze is currently serving her first term '
                  'in the Ohio Senate representing the people of the 16th '
                  'Senate District on the western side of Franklin County '
                  'including the cities of Dublin, Galloway, Grove City, '
                  'Hilliard, Upper Arlington, Worthington and portions of '
                  'Clintonville and Columbus.',
    'active': True,
    'all_ids': ['OHL000327'],
    'boundary_id': 'ocd-division/country:us/state:oh/sldu:16',
    'chamber': 'upper',
    'created_at': datetime.datetime(2017, 1, 4, 5, 4, 11),
    'district': '16',
    'email': 'sd16@ohiosenate.gov',
    'first_name': 'Stephanie',
    'full_name': 'Stephanie Kunze',
    'id': 'OHL000327',
    'last_name': 'Kunze',
    'leg_id': 'OHL000327',
    'middle_name': '',
    'offices': [ { 'address': 'Senate Building\n'
                              '1 Capitol Square, 1st Floor\n'
                              'Columbus, OH 43215',
                   'email': 'sd16@ohiosenate.gov',
                   'fax': None,
                   'name': 'Capitol Office',
                   'phone': '614-466-5981',
                   'type': 'capitol'}],
    'party': 'Republican',
    'photo_url': 'http://www.ohiosenate.gov/Assets/Headshots/Small/16.jpg',
    'roles': [ { 'chamber': 'upper',
                 'district': '16',
                 'end_date': None,
                 'party': 'Republican',
                 'start_date': None,
                 'state': 'oh',
                 'term': '2017-2018',
                 'type': 'member'},
               { 'chamber': 'upper',
                 'committee': 'Insurance and Financial Institutions',
                 'committee_id': 'OHC000035',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'upper',
                 'committee': 'Health, Human Services and Medicaid',
                 'committee_id': 'OHC000034',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'upper',
                 'committee': 'Agriculture',
                 'committee_id': 'OHC000032',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'upper',
                 'committee': 'Rules and Reference',
                 'committee_id': 'OHC000004',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'upper',
                 'committee': 'Transportation, Commerce and Workforce',
                 'committee_id': 'OHC000037',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'}],
    'sources': [{'url': 'http://www.ohiosenate.gov/members/senate-directory'}],
    'state': 'oh',
    'suffixes': '',
    'updated_at': datetime.datetime(2018, 4, 16, 7, 54, 48),
    'url': 'http://www.ohiosenate.gov/kunze'},
  { 'active': False,
    'all_ids': ['OHL000057'],
    'boundary_id': 'ocd-division/country:us/state:oh/sldl:24',
    'chamber': 'lower',
    'country': 'us',
    'created_at': datetime.datetime(2011, 2, 22, 21, 25, 58),
    'district': '24',
    'first_name': 'Ted',
    'full_name': 'Ted Celeste',
    'id': 'OHL000057',
    'last_name': 'Celeste',
    'leg_id': 'OHL000057',
    'level': 'state',
    'middle_name': '',
    'offices': [ { 'address': '77 S. High St, 10th Floor, Columbus, OH '
                              '43215-6111',
                   'email': None,
                   'fax': '(614) 719-6963',
                   'name': 'Capitol Office',
                   'phone': '(614) 644-6005',
                   'type': 'capitol'}],
    'old_roles': { '2011-2012': [ { 'chamber': 'lower',
                                    'district': '24',
                                    'end_date': '2013-01-07 00:00:00',
                                    'party': 'Democratic',
                                    'start_date': None,
                                    'state': 'oh',
                                    'term': '2011-2012',
                                    'type': 'member'},
                                  { 'chamber': 'lower',
                                    'committee': 'Economic and Small Business '
                                                 'Development',
                                    'committee_id': 'OHC000048',
                                    'end_date': None,
                                    'position': 'Member',
                                    'start_date': None,
                                    'state': 'oh',
                                    'term': '2011-2012',
                                    'type': 'committee member'},
                                  { 'chamber': 'lower',
                                    'committee': 'Education',
                                    'committee_id': 'OHC000049',
                                    'end_date': None,
                                    'position': 'Member',
                                    'start_date': None,
                                    'state': 'oh',
                                    'term': '2011-2012',
                                    'type': 'committee member'},
                                  { 'chamber': 'lower',
                                    'committee': 'State Government and '
                                                 'Elections',
                                    'committee_id': 'OHC000063',
                                    'end_date': None,
                                    'position': 'Member',
                                    'start_date': None,
                                    'state': 'oh',
                                    'term': '2011-2012',
                                    'type': 'committee member'}]},
    'party': 'Democratic',
    'photo_url': 'http://www.house.state.oh.us/houseImages/129/headshots/h24.jpg',
    'roles': [],
    'sources': [ { 'url': 'http://www.house.state.oh.us/components/com_displaymembers/page.php?district=24'}],
    'state': 'oh',
    'suffixes': '',
    'transparencydata_id': '98c292e941f44d209ac33024baf057f5',
    'updated_at': datetime.datetime(2013, 1, 7, 20, 11, 11),
    'url': 'http://www.house.state.oh.us/components/com_displaymembers/page.php?district=24',
    'votesmart_id': '45715'},
  { '+biography': 'Representative Jim Hughes is serving his first term in the '
                  'Ohio House representing the 24th district, which '
                  'encompasses a portion of Franklin County, including Upper '
                  'Arlington, Hilliard, and Clintonville.',
    'active': True,
    'all_ids': ['OHL000334'],
    'boundary_id': 'ocd-division/country:us/state:oh/sldl:24',
    'chamber': 'lower',
    'created_at': datetime.datetime(2017, 1, 4, 5, 4, 11),
    'district': '24',
    'email': 'rep24@ohiohouse.gov',
    'first_name': 'Jim',
    'full_name': 'Jim Hughes',
    'id': 'OHL000334',
    'last_name': 'Hughes',
    'leg_id': 'OHL000334',
    'middle_name': '',
    'offices': [ { 'address': '77 S. High St\n13th Floor\nColumbus, OH 43215',
                   'email': 'rep24@ohiohouse.gov',
                   'fax': '614-719-0007',
                   'name': 'Capitol Office',
                   'phone': '614-466-8012',
                   'type': 'capitol'}],
    'party': 'Republican',
    'photo_url': 'http://www.ohiohouse.gov/Assets/Headshots/Small/24.jpg',
    'roles': [ { 'chamber': 'lower',
                 'district': '24',
                 'end_date': None,
                 'party': 'Republican',
                 'start_date': None,
                 'state': 'oh',
                 'term': '2017-2018',
                 'type': 'member'},
               { 'chamber': 'lower',
                 'committee': 'Transportation and Public Safety',
                 'committee_id': 'OHC000022',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'lower',
                 'committee': 'Criminal Justice',
                 'committee_id': 'OHC000021',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'},
               { 'chamber': 'lower',
                 'committee': 'Financial Institutions, Housing, and Urban '
                              'Development',
                 'committee_id': 'OHC000044',
                 'position': 'member',
                 'state': 'oh',
                 'subcommittee': None,
                 'term': '2017-2018',
                 'type': 'committee member'}],
    'sources': [{'url': 'http://www.ohiohouse.gov/members/member-directory'}],
    'state': 'oh',
    'suffixes': '',
    'updated_at': datetime.datetime(2018, 4, 16, 7, 54, 48),
    'url': 'http://www.ohiohouse.gov/jim-hughes'}]
```

**Comment by seanthegeek** [comment]
@estaub This issue can be closed now. I've addressed this in openstates/pyopenstates#7. For some reason I can't close issues here.

**Comment by seanthegeek** [comment]
@estaub @georgezoto FYSA - . I just committed `pyopenstates` 1.2.0 to Github and PyPI. It accounts for API rate limits when conducting large searches by pausing for one second between page requests. All unit tests are passing again :)

**Comment by estaub** [comment]
@seanthegeek Yeah, I think the rate limiter was tightened up sometime in the last few months.  I just ran into it too; I was running 120 RPM, backed off to 59, all good now.

**Comment by georgezoto** [comment]
Thank you @seanthegeek I will follow up in https://github.com/openstates/pyopenstates/issues/7
