### ISSUE TITLE
Old data being served from API for NY and MA state legislators

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#2307]
State: MA, NY, possibly others

Example in MA - Rep Kocot appears here with status set to active:

   https://openstates.org/api/v1/legislators/?state=ma&chamber=lower&apikey=APIKEY 1

He’s deceased and not in the JSON scraper output after a local run of the MA scraper.  I can produce a NY example if needed, but I wonder if the problem isn't systemic since the scrapers appear to be correct.

**Comment by jamesturk** [comment]
If you can let us know the NY ones too (this ticket is fine), we can
deactivate them.  Because sometimes people go missing on sites we don't
automatically retire people that are missing from a scrape.

**Comment by samtregar** [comment]
NY example is Senator Latimer.  Thanks for getting these for us!  I'm not sure it's everyone and I think I used to have a script to run to find them.  I'll see about doing a run across all states soon.

**Comment by jamesturk** [comment]
I've fixed these, a list of other inactives can be fixed just as quick. if
you have a link to a source for deaths/ resignation that's helpful to
expedite this

**Comment by samtregar** [comment]
Sadly no, I don't have a data-source.  I believe the last time I worked on this I ran a script to compare the scraper output to the API output and then googled each result to see if I could confirm retirement/death.  If I do that again and don't find any false positives maybe that will be a good argument for making this automatic - i.e. if you're not in the scraper output then active=false.

**Comment by jamesturk** [comment]
We'll stick to manual retirement for now, there are enough false positives
to warrant it, but some of the work that's on the agenda for Google summer
of code will likely help with this.

**Comment by jamesturk** [comment]
of course, any help doing a round up of people needed updates always
welcome :)
