### ISSUE TITLE
CA: Some sponsors missing

### ISSUE THREAD

**Issue by calnation** [openstates/openstates#2308]
[Official bill link](http://leginfo.legislature.ca.gov/faces/billStatusClient.xhtml?bill_id=201720180AB291) shows:
- 4 Lead Authors
- 1 Principal Coauthor
- 7 Coauthors

For the same bill, [OpenStates](https://openstates.org/ca/bills/20172018/AB291/) shows:
- 4 author(s)
- 6 coauthor(s)

Aside from the scraping issue above, I'm not sure if you have formed a standard policy in terms of naming sponsorship types for older bills. Some bills I queried use the naming convention mentioned in your documentation (`primary` or `cosponsor`) but others like this don't. CA's 3 types I'm sure don't help either.

Thanks!

**Comment by schneidy** [comment]
@jamesturk The sponsors are contained within the provided SQL and database. It looks like we're not adding in authors/co-authors from opposing chambers. With the example mentioned above, authors/coauthors from the Senate are not included while all those in the Assembly are included.

**Comment by jamesturk** [comment]
per @schneidy latest check of a local run included them, going to re-run and check again

**Comment by jamesturk** [comment]
fixed in latest run
