### ISSUE TITLE
CO: No votes scraped in 2018.

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2318]
It looks scrapable to me, but I didn't delve deeply.

**Comment by In-vincible** [comment]
@estaub can you give a reference to any particular example where you found it scrapable.

**Comment by estaub** [comment]
@In-vincible Take a look at 

https://leg.colorado.gov/bills/sb18-200
  ===> https://leg.colorado.gov/content/sb18-200vote5cc109

I've next to no experience writing scrapers, and didn't look deeply.

**Comment by In-vincible** [comment]
Yeah, checked it, the right now scraper is broken for the above bill, its little complex but seems scrapable.
