### ISSUE TITLE
NH: duplicate legislators in API V2

### ISSUE THREAD

**Issue by estaub** [openstates/openstates#2398]
State: NH

I am not at all confident that this is a scraper issue, or that it's limited to NH, or that it's not just my ignorance of how to handle this.

This is similar to the duplicate legislators that occur in API V1, but AFAICT there's no all_ids field or other feature to mitigate it.

Using API V2, one can ask for the votes on a bill:

```gql
{
  bill(id: "ocd-bill/8aab955f-6ad9-4f06-a8e2-64ed156940eb") {
    id
    identifier
    votes {
      edges {
        node {
          id
          votes {
            option
            voter {
              id
            }
            voterName
} } } } } }
```

The second individual vote reads: 

```json
{
    "option": "yes",
    "voter": {
        "id": "ocd-person/51dfef5c-362f-46ff-bfa5-3e58998cb2dd"
    },
    "voterName": "Chuck W Morse"
}
```
The problem is that AFAICT, this voter ID isn't listed anywhere one might get all the legislators from.  

If, for example, one asks for all the legislators who ever served in the NH Senate:

```gql
{
    people(first: 100, everMemberOf: "ocd-organization/c95932a0-2ac1-4f14-a0c4-ade8568daac6") {
        edges {
            node {
                id
                name
                identifiers {
                    identifier
                    scheme
} } } } }
```

... Chuck Morse is listed with a different id:

```json
{
            "id": "ocd-person/2d25d1fd-dfdb-44f0-86a9-874ec1dc3f81",
            "name": "Chuck W Morse",
            "identifiers": []
}

```
It is possible to do a single Person query for the `voter.id` `ocd-person/51dfef5c-362f-46ff-bfa5-3e58998cb2dd`, but then (AFAICT) the app must discover that it's a duplicate on its own, using something like pupa's pseudo-identifiers.

**Comment by jamesturk** [comment]
fixed via new openstates/people repo & process
