### ISSUE TITLE
SD Missing email addresses

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#2414]
State: SD

They removed them from their member detail pages entirely, but they're still on a "contact your legislator" page.  PR coming soon.

**Comment by showerst** [comment]
@samtregar Did this get fixed in https://github.com/openstates/openstates/commit/e6d23196fe7a2a15f0bb9d1376b26df46296391e ? If so i'll close this bug.

**Comment by samtregar** [comment]
Yup, all good now.
