### ISSUE TITLE
PR: Senators not being scraped & Representatives link outdated

### ISSUE THREAD

**Issue by csnardi** [openstates/openstates#2452]
State: Puerto Rico

Per https://openstates.org/pr/, no senators appear to have been scraped for this latest legislative session. This appears to be because the website for the Puerto Rican Senate has changed, as none of the links in https://github.com/openstates/openstates/blob/master/openstates/pr/people.py#L30-L40 will load -- I believe https://senado.pr.gov/Pages/Senadores.aspx should be the new link, and the scraper will need to be updated as well.

Additionally, it appears that the Puerto Rican House just changed its website, as the link at https://github.com/openstates/openstates/blob/master/openstates/pr/people.py#L102 now redirects to the homepage of their House. I believe it should be updated to http://www.tucamarapr.org/dnncamara/ComposiciondelaCamara/Biografia.aspx, with the scraper also updated accordingly.

**Comment by jamesturk** [comment]
see #1622 :)

**Comment by chris-erickson** [comment]
Is that the wrong linked issue?  I don't see the relation..

**Comment by csnardi** [comment]
I think #1611 was intended, somehow I missed that in my original search.
