### ISSUE TITLE
NY: Missing Roll Call Votes in 2017-2018

### ISSUE THREAD

**Issue by ilyagerner** [openstates/openstates#2465]
State: NY

For NYS, we appear to be missing votes that take place in the Assembly on Senate bills and missing votes taking place in the Senate on Assembly bills.

For example: [A2930](http://alpha.openstates.org/graphql?operationName=null&query=%7B%0A%20%20b1%3A%20bill(jurisdiction%3A%20%22New%20York%22%2C%20session%3A%20%222017-2018%22%2C%20identifier%3A%20%22A%202930%22)%20%7B%0A%20%20%20%20id%0A%20%20%20%20identifier%0A%20%20%20%20title%0A%20%20%20%20classification%0A%20%20%20%20updatedAt%0A%20%20%20%20createdAt%0A%20%20%20%20legislativeSession%20%7B%0A%20%20%20%20%20%20identifier%0A%20%20%20%20%20%20jurisdiction%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20votes%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20counts%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20option%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20votes%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20voterName%0A%20%20%20%20%20%20%20%20%20%20%20%20voter%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20contactDetails%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20value%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20note%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20type%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20option%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20sources%20%7B%0A%20%20%20%20%20%20url%0A%20%20%20%20%20%20note%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) has the correct Assembly roll call information, but is missing the [Senate roll call](https://www.nysenate.gov/legislation/bills/2017/A2930). Doesn't appear to be a problem before the 2017 term.

**Comment by jamesturk** [comment]
merging with #1384
