### ISSUE TITLE
CA: retired reps being returned for two districts

### ISSUE THREAD

**Issue by samtregar** [openstates/openstates#2472]
State: CA

The API is returning multiple legislators for CA Assembly District 39 and Senate District 29, which include legislators no longer serving (Bocanegra and Newman, respectively).

https://openstates.org/api/v1/legislators/?state=ca&chamber=lower&district=39
https://openstates.org/api/v1/legislators/?state=ca&chamber=upper&district=29

Previously this issue was resolved by running a “retirement sweep” which is a manual process. (Old data being served from API for NY and MA state legislators) Would it be possible to run this again?

**Comment by jamesturk** [comment]
looking at a v2->v1 option for these, but this is fixed in v2

**Comment by jamesturk** [comment]
fixed in v1 & v2 👍
