### ISSUE TITLE
TX: Missing vote data

### ISSUE THREAD

**Issue by jmillxyz** [openstates/openstates#2494]
Reference: https://github.com/open-austin/influence-texas/issues/86

State: TX

Here's a bill that passed, but there's no vote labeled as the Senate's vote for passage https://openstates.org/tx/bills/85/HB245/

Why?

@mscarey

**Comment by lazarus1331** [comment]
There's no votes for any resolutions or bills from the latest v2 API for items that have been voted on either.

**Comment by lazarus1331** [comment]
@showerst I'm still not seeing any votes showing up for bills or resolutions in TX.  Is there something else we can look at?
