### ISSUE TITLE
Wyoming Data Dupes / Out of date records

### ISSUE THREAD

**Issue by joearasin** [openstates/openstates#2538]
State: Wyoming

There are a handful of duplicate records in Wyoming Data and an extraneous out-of-date record as well.

[R.] Ray Peterson: WYL000025 / WYL000171
[James Lee / Jim] Anderson: WYL000093 / WYL000168
[Timothy / Tim] Hallinan: WYL000159 / WYL000170
[Michael / Mike] Madden: WYL000068 / WYL000167
[James / Jim] Byrd:  WYL000041 / WYL000169

Out of date Record:
Lars Lone (Resigned): WYL000138

**Comment by showerst** [comment]
Thanks @joearasin -- We're working on transitioning the member data to a [newer project](https://discourse.openstates.org/t/a-new-approach-to-legislator-data/143) right now to make ingest easier. 

I'll bug @jamesturk to resolve these, and we might also use them as a first test case for our retirement code in the new project.

**Comment by joearasin** [comment]
Cool! I'm new to this data, so if I'm repeating a point let me know. It would seem that having a cardinality check of some sort that calls for manual intervention when the number of people and holders of a given office don't match up (and in particular are more than expected).

**Comment by jamesturk** [comment]
The new process & repo is a lot better at doing that- if you check it out
there's clean WY data in there now, and we'll be importing that into the
API as early as possible, I'm aiming for next week still

**Comment by joearasin** [comment]
Great! Thanks! This looks great. Is the API going to change at all (in particular with regards to IDs)?

**Comment by jamesturk** [comment]
are you using API v2 or v1? 

v2 is now updated, IDs will be stable there from now on

i'm looking at backporting options for v1

**Comment by joearasin** [comment]
We're currently using the v1 API.

**Comment by jamesturk** [comment]
fixed in v1
