### ISSUE TITLE
2019 session planning

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#2681]
In past years we've turned off all the scrapers until we could quickly verify that things are looking normal on state sites.  We've seen enough weirdness where we were getting 2017 bills despite hitting the API with the 2016 slug or vice versa that this sort of became unofficial protocol.

I know a few states are in special session & a few have prefiles, but we can turn those back on really quick, or potentially even vet them before I make the big push to task-definitions to turn them off.

When turning back on we also want to give each state a quick once-over to make sure that there weren't any hard-coded year/session values (I think we got all of these, but they creep in from time to time)

I was thinking I'd flip this switch to turn things off next week, and we can use this ticket as a master list to get things turned back on after vetting. 

**How to help:** If you've run a states bill/votes scraper and verified it is getting 2019 data (or is in a special session) and taken a look at the code to look for hard-coded session/year values then leave a comment and we'll update the list below.  Next week I'll make a PR to turn off all non-checked states and then as states are checked we'll turn them back on.  (If a state needs work first, we'll discuss that in a separate ticket, like #2554)

- [ ] Alaska 
- [x] Louisiana
- [x] Alabama
- [x] Arizona
- [x] Arkansas
- [x] California 
- [x] Colorado 
- [x] Connecticut
- [x] Delaware
- [x] District of Columbia
- [x] Florida
- [x] Georgia 
- [x] Hawaii
- [x] Idaho
- [x] Illinois
- [x] Indiana
- [x] Iowa 
- [x] Kansas
- [x] Kentucky
- [x] Maine 
- [x] Maryland 
- [x] Massachusetts 
- [x] Michigan
- [x] Minnesota
- [x] Mississippi 
- [x] Missouri
- [x] Montana
- [x] Nebraska
- [x] Nevada 
- [x] New Hampshire
- [x] New Jersey
- [x] New Mexico
- [x] New York
- [x] North Carolina
- [x] North Dakota 
- [x] Ohio
- [x] Oklahoma 
- [x] Oregon
- [x] Pennsylvania
- [x] Puerto Rico
- [x] Rhode Island 
- [x] South Carolina
- [x] South Dakota
- [x] Tennessee 
- [x] Texas
- [x] Utah 
- [x] Vermont
- [x] Virginia
- [x] Washington 
- [x] West Virginia 
- [x] Wisconsin
- [x] Wyoming

cc @jmcarp @showerst

**Comment by showerst** [comment]
Sounds good to me. We've got a few states already running the 2019 prefiles that look fine; i'll note these in a comment. 

I've also got a patch incoming with a few states that have added empty 2019 sessions, so I added commented out session entries and added 'em to the ignore list, just to avoid bobsled errors. Sounds like i can hold off on doing any more of those if we're going to turn them off, so i'll push that commit later today.

@jamesturk once you turn stuff off; i'll start the vetting process from the bottom of the alphabet, and you can start from the top? @jmcarp if you have time to jump in maybe you can at like Maryland?

**Comment by showerst** [comment]
States that are prefiling and can be left up if you want:

OK, TX, VA, KY, FL, TN

**Comment by jamesturk** [comment]
All caught up adding these to task-definitions, I should be able to start adding more myself soon.

P.S. when checking a box mind posting a comment here so I can know which ones are new? I realize GitHub doesn't make it easy to tell

**Comment by showerst** [comment]
@jamesturk no problem.

**Comment by showerst** [comment]
I added the KY 2018 Special, which you only need to scrape as a one-off (it's over.)

**Comment by showerst** [comment]
- [ ] Added UT 2019.

**Comment by showerst** [comment]
- [ ] TX is verified working

**Comment by showerst** [comment]
- [ ] Added WY 2019

**Comment by showerst** [comment]
- [ ] Added CA 2019

**Comment by showerst** [comment]
- [ ] Added ND 2019

**Comment by showerst** [comment]
JMCarp Added

- [ ] PA 2019
- [ ] RI 2019

**Comment by showerst** [comment]
- [ ] Added NY 2019

**Comment by showerst** [comment]
- [ ] Added MA 2019

**Comment by csnardi** [comment]
I believe IN 2019 was added in #2733.

**Comment by showerst** [comment]
@csnardi thanks, forgot to comment that one.

@jamesturk : 

- [ ] Added IN 2019

**Comment by showerst** [comment]
- [ ] Added DC 2019

**Comment by showerst** [comment]
- [ ] Added ID 2019

**Comment by showerst** [comment]
- [ ] Added CO 2019

**Comment by showerst** [comment]
- [ ] Added KS 2019

**Comment by showerst** [comment]
- [ ] Added OH 2019

**Comment by showerst** [comment]
- [ ] Added MS 2019

**Comment by showerst** [comment]
- [ ] Added VT 2019

**Comment by showerst** [comment]
- [ ] WI is live

**Comment by showerst** [comment]
- [ ] Added MI 2019

**Comment by showerst** [comment]
- [ ] Added IL 2019

**Comment by showerst** [comment]
- [ ] Added MN 2019

**Comment by showerst** [comment]
- [ ] Restored NM 2019

**Comment by showerst** [comment]
- [ ] Added OR 2019

**Comment by showerst** [comment]
- [ ] Added AL 2019

**Comment by showerst** [comment]
- [ ] Added NE 2019

**Comment by showerst** [comment]
- [ ] Added WV 2019

**Comment by showerst** [comment]
Unchecked NC, code is in init but they'll need a new scraper.

**Comment by showerst** [comment]
- [ ] Added NC 2019

**Comment by showerst** [comment]
- [ ] Added IA 2019

**Comment by showerst** [comment]
- [ ] Added HI 2019

**Comment by showerst** [comment]
- [ ] PR is working with no changes (continuation of an older session)

**Comment by showerst** [comment]
- [ ] Added LA 2019, PR here - https://github.com/openstates/task-definitions/pull/6
