### ISSUE TITLE
AK: Legislator list in API v1 no longer worker

### ISSUE THREAD

**Issue by bshor** [openstates/openstates#2685]
State: __AK___  (be sure to include in ticket title)

I am using API v1 to return the list of active legislators using the following call:

`https://openstates.org/api/v1//legislators/?state=AK&active=true&apikey=xxxx
`

But just recently it started returning only

`[]
`

What should I do? I'm not sure how to get the equivalent view in v2.

**Comment by jamesturk** [comment]
I think this was a hiccup, it looks Amazon's RDS is having an issue right
now- it should show up now
