### ISSUE TITLE
MN: No legislator list returned

### ISSUE THREAD

**Issue by bshor** [openstates/openstates#2692]
State: _MN____  (be sure to include in ticket title)

[Earlier, I had problems with getting legislator data from the v1 API. The issue was closed, with the explanation that Amazon AWS was at fault.](https://github.com/openstates/openstates/issues/2685)

Now, I'm having the same problem again. Now I'm working with MN but the error is generic and happens for every state.

`https://openstates.org/api/v1//legislators/?state=MN&active=true&apikey=xxxx
`

Now just returns only

[]

What should I do?

**Comment by jamesturk** [comment]
Aha- this is a slight regression related to case, can you for now change MN
to mn if it isn't too big of an issue, I'll look at fixing this ASAP though

**Comment by bshor** [comment]
Thanks for looking into this. Still the same open/close brackets.

**Comment by jamesturk** [comment]
I'm wondering if that was a cache issue- is it still occurring?  If so can you try adding something like &cachebust to the query string and confirm it is resolved

**Comment by bshor** [comment]
Yes, it is still occurring. Adding cachebust doesn't resolve the problem.

**Comment by bshor** [comment]
No, it doesn't appear to be. I wrote before I saw your suggestion to use lower case (and just tried the cachebust suggestion which didn't work with upper case). Thanks!
