### ISSUE TITLE
Re-enabling events

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#2693]
@jamesturk i'm going to take a pass at fixing up the event scrapers, with an eye towards getting them back to quality by the new session starts. 

Looking at the task definitions we're specifically scraping bills / votes so it shouldn't cause any data pipeline problems if I re-include the working ones right?

**Comment by jamesturk** [comment]
Ah yeah that should be completely fine.

I wonder if there's a better way for us to handle turning off certain
scrapers system-wide, it'd be nice if people could run the person scraper
locally without uncommenting it, etc.
