### ISSUE TITLE
V1 API No Longer Showing Sponsors or Votes Person Data For Alabama

### ISSUE THREAD

**Issue by BamaStangGuy** [openstates/openstates#2696]
API Call: https://openstates.org/api/v1/bills/ALB00014381/?apikey=

Returns all votes with {"leg_id": null,

Same for sponsors. I know for a fact Sponsors used to work as I populated the leg_id for all bill sponsors in a previous api call for my project.

**Comment by jamesturk** [comment]
we're no longer matching sponsors/etc for v1
