### ISSUE TITLE
MN: People scraper return none

### ISSUE THREAD

**Issue by cultureclap** [openstates/openstates#2760]
State: _MN__  (be sure to include in ticket title)

when attempting to scrape MN people the following error is returned:

`
pupa.exceptions.ScrapeError: no objects returned from MNPersonScraper scrape
`

any advice ?

The CSV needed is still available. MN did recently update their site, and I was getting an assertion error that was fixed with I updated the links it was looking for. But now getting the "no objects returned" error :/

[dpaste](http://dpaste.com/1EKJ757)

**Comment by cultureclap** [comment]
Thank you!

**Comment by showerst** [comment]
I just merged @csnardi 's fix.
