### ISSUE TITLE
NE: Fix related bills, fiscal notes, and vote xpaths in February

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#2772]
State: NE

NE Updated their site for 2019, and probably broke our scraping of votes, fiscal notes, amendments, and other docs. 

As of Jan 11 there isn't enough data on the site to determine the correct XPATH expressions to fix this. So once more data comes in, fix these. The title, sponsor, and version xpath's could use a cleanup too to make them more readable, as I just cut and pasted the ones generated by Chrome which are pretty dirty.

**Comment by jamesturk** [comment]
looking good now from what I can tell after a run of 67a75ea
