### ISSUE TITLE
CA: v1/metadata/ca not updating

### ISSUE THREAD

**Issue by mhedblom** [openstates/openstates#2775]
The meta data for CA (v1/metadata/ca) has not updated since 03-Nov-2018

**Comment by jamesturk** [comment]
v1 metadata will no longer open, I'll update the docs to reflect this

**Comment by mhedblom** [comment]
OK. Is there another way in V1 to determine which sessions are available? Our system was depending on that list.

**Comment by jamesturk** [comment]
Are you depending on the sessions or the terms (or both?)
