### ISSUE TITLE
API V1: bill ids no longer assigned - all states

### ISSUE THREAD

**Issue by agelimson** [openstates/openstates#2783]
State: _All states_  (be sure to include in ticket title)

Hi, it seems like the API v1 no longer assigns any ids to bills, the ID fields are empty. This makes it impossible to pull up bill details

For example for this query
https://openstates.org/api/v1/bills/?state=tx&search_window=session

[{"title": "Relating to prohibited acts regarding abortion for a physician or applicant for a medical license.", "summary": "", "created_at": "2018-11-15 11:11:32", "updated_at": "2018-11-15 11:11:32", "id": "", "all_ids": [""], "chamber": "lower", "state": "tx", "session": "86", "type": ["bill"], "bill_id": "HB 47", "actions": [{"date": "2018-11-12 00:00:00", "action": "Filed", "type": ["bill:filed"], "related_entities": [], "actor": "lower"}], "sources": [{"url": "ftp://ftp.legis.state.tx.us/bills/86R/billhistory/house_bills/HB00001_HB00099/HB 47.xml"}], "sponsors": [{"leg_id": null, "type": "primary", "name": "Swanson"}], "versions": [{"mimetype": "text/html", "url": "ftp://ftp.legis.state.tx.us/bills/86R/billtext/html/house_bills/HB00001_HB00099/HB00047I.htm", "doc_id": "~not available~", "name": "Introduced"}], "documents": [], "alternate_titles": [], "votes": null, "action_dates": {"first": "2018-11-12 00:00:00", "last": "2018-11-12 00:00:00", "passed_upper": null, "passed_lower": null, "signed": null}, "scraped_subjects": ["Abortion (I0005)", "Health--General (I0385)", "Occupational Regulation--Health Occupations (I0540)", "PHYSICIANS (S1282)", "MEDICAL BOARD, TEXAS (V0644)"], "alternate_bill_ids": [], "subjects": [], "companions": []}, {"title": "Relating to the waiting period before a physician may perform an abortion.", "summary": "", "created_at": "2018-11-15 11:11:40", "updated_at": "2018-11-15 11:11:40", "id": "", "all_ids": [""], "chamber": "lower", "state": "tx", "session": "86", "type": ["bill"], "bill_id": "HB 249", "actions": [{"date": "2018-11-12 00:00:00", "action": "Filed", "type": ["bill:filed"], "related_entities": [], "actor": "lower"}], "sources": [{"url": "ftp://ftp.legis.state.tx.us/bills/86R/billhistory/house_bills/HB00200_HB00299/HB 249.xml"}], "sponsors": [{"leg_id": null, "type": "primary", "name": "Farrar"}], "versions": [{"mimetype": "text/html", "url": "ftp://ftp.legis.state.tx.us/bills/86R/billtext/html/house_bills/HB00200_HB00299/HB00249I.htm", "doc_id": "~not available~", "name": "Introduced"}], "documents": [], "alternate_titles": [], "votes": null, "action_dates": {"first": "2018-11-12 00:00:00", "last": "2018-11-12 00:00:00", "passed_upper": null, "passed_lower": null, "signed": null}, "scraped_subjects": ["Abortion (I0005)", "INFORMED CONSENT (S0057)", "PHYSICIANS (S1282)"], "alternate_bill_ids": [], "subjects": [], "companions": []}, {"title": "Relating to the medical accuracy of informational materials given to a woman seeking an abortion.", "summary": "", "created_at": "2018-11-15 11:11:37", "updated_at": "2018-11-15 11:11:37", "id": "", "all_ids": [""], "chamber": "lower", "state": "tx", "session": "86", "type": ["bill"], "bill_id": "HB 248", "actions": [{"date": "2018-11-12 00:00:00", "action": "Filed", "type": ["bill:filed"], "related_entities": [], "actor": "lower"}], "sources": [{"url": "ftp://ftp.legis.state.tx.us/bills/86R/billhistory/house_bills/HB00200_HB00299/HB 248.xml"}], "sponsors": [{"leg_id": null, "type": "primary", "name": "Farrar"}], "versions": [{"mimetype": "text/html", "url": "ftp://ftp.legis.state.tx.us/bills/86R/billtext/html/house_bills/HB00200_HB00299/HB00248I.htm", "doc_id": "~not available~", "name": "Introduced"}], "documents": [], "alternate_titles": [], "votes": null, "action_dates": {"first": "2018-11-12 00:00:00", "last": "2018-11-12 00:00:00", "passed_upper": null, "passed_lower": null, "signed": null}, "scraped_subjects": ["Abortion (I0005)", "Health--General (I0385)", "Women (I0925)", "STATE HEALTH SERVICES, DEPARTMENT OF (V0463)"], "alternate_bill_ids": [], "subjects": [], "companions": []}, {"title": "Proposing a constitutional amendment guaranteeing the right to life of unborn children and prohibiting abortion to the extent authorized under federal constitutional law.", "summary": "", "created_at": "2018-11-15 11:11:35", "updated_at": "2018-11-15 11:11:35", "id": "", "all_ids": [""], "chamber": "upper", "state": "tx", "session": "86", "type": ["joint resolution"], "bill_id": "SJR 3", "actions": [{"date": "2018-11-12 00:00:00", "action": "Received by the Secretary of the Senate", "type": ["bill:filed"], "related_entities": [], "actor": "upper"}, {"date": "2018-11-12 00:00:00", "action": "Filed", "type": ["bill:filed"], "related_entities": [], "actor": "upper"}], "sources": [{"url": "ftp://ftp.legis.state.tx.us/bills/86R/billhistory/senate_joint_resolutions/SJR00001_SJR00099/SJR 3.xml"}], "sponsors": [{"leg_id": null, "type": "primary", "name": "Hall"}], "versions": [], "documents": [], "alternate_titles": [], "votes": null, "action_dates": {"first": "2018-11-12 00:00:00", "last": "2018-11-12 00:00:00", "passed_upper": null, "passed_lower": null, "signed": null}, "scraped_subjects": ["Abortion (I0005)", "Resolutions--Constitutional Amendments (I0661)"], "alternate_bill_ids": [], "subjects": [], "companions": []}]

**Comment by jamesturk** [comment]
You should still be able to use the format
http://docs.openstates.org/en/latest/api/bills.html#bill-detail to look up
bill details.

For example https://openstates.org/api/v1/bills/tx/86/HB%2047

**Comment by jamesturk** [comment]
if there's a place that you found that this wasn't well documented let me know and I'll take a look at adding a note there, closing this for now
