### ISSUE TITLE
TX: No vote data for v2 API

### ISSUE THREAD

**Issue by lazarus1331** [openstates/openstates#2812]
State: TX

There is no vote data being returned for TX bills/resolutions for the 86 session in the v2 API.  I am opening this issue because it is specific to the latest API, and previous issues were specific to the v1 API.

I would like to have a conversation with someone from open-states who can explain your use of the scrapers for retrieving vote data, since it appears you need some help to update/fix these.  We have some people that can probably be mobilized to help with this from [Open Austin](https://www.open-austin.org/]

**Comment by lazarus1331** [comment]
Related: https://github.com/openstates/openstates/issues/2494

**Comment by showerst** [comment]
@jamesturk will need to re-enable the task definition here, https://github.com/openstates/task-definitions once you see that commit vote data should start flowing in overnight.

**Comment by lazarus1331** [comment]
@showerst Thank you!

**Comment by lazarus1331** [comment]
@showerst I'm still not seeing any votes showing up for bills or resolutions in TX. Is there something else we can look at?

**Comment by showerst** [comment]
Somebody on the infrastructure side (i just work on scrapers) needs to flip the vote scraping life.

@mileswwatkins @jamesturk one of y'all mind merging this?

https://github.com/openstates/task-definitions/pull/4
