### ISSUE TITLE
UT: bills wrongly showing as only numbered

### ISSUE THREAD

**Issue by Dani21** [openstates/openstates#2820]
State: Utah  (be sure to include in ticket title)

Data source: https://le.utah.gov/DynaBill/BillList?session=2019GS

As seen in the link above, you can access any of the bills and see their information. However the OpenStates site for the 2019 session only lists their numbers and descriptions, with links leading to 404 errors: https://openstates.org/ut/bills/?session=2019

**Comment by estaub** [comment]
Clarification: "only numbered" in the issue title refers to the status of the bill; no subsequent actions are being recorded, AFAICT.

**Comment by jamesturk** [comment]
the issue here is that we're putting actions in the wrong order, should be a simple fix

pupa should also check for this & at least warn

**Comment by jamesturk** [comment]
@schneidy can you reorder these?

**Comment by schneidy** [comment]
@jamesturk Sorting actions had no effect on removing "only numbered" from being displayed.

**Comment by jamesturk** [comment]
fixed in openstates.org
