### ISSUE TITLE
Willing to pay for help with CA

### ISSUE THREAD

**Issue by koryp123** [openstates/openstates#2860]
CA bills are not being updated in OS -- specifically, for ecample:

SB 200
ACA 3      both of these for the current legislative session (not last year's)

Can anyone offer insight as to why there is a delay w/ CA?

Thanks

**Comment by showerst** [comment]
@koryp123 http://bobsled.openstates.org/run-CA-2019-02-13.html -- this appears to be a configuration issue on the server.

@jamesturk @mileswwatkins are we just missing a package in requirements.txt here?

**Comment by koryp123** [comment]
Thanks Tim, I see that.

Kind of at a loss here on what to do.

**Comment by mileswwatkins** [comment]
Centralizing this conversation to the main CA ticket https://github.com/openstates/openstates/issues/2776
