### ISSUE TITLE
CO: Incorrect Officials in Senate Districts

### ISSUE THREAD

**Issue by putorti** [openstates/openstates#2881]
**District 17**
Colorado web site shows [Mike Foote](http://leg.colorado.gov/node/207671)
OpenStates data indicates Matt Jones

**Comment by putorti** [comment]
**District 9**
Colorado web site shows [Paul Lundeen](https://leg.colorado.gov/legislators/paul-lundeen)
OpenStates data indicates [Kent Lambert](https://openstates.org/person/kent-lambert-5uFSk222byreb9uQLfQfC/)

**Comment by putorti** [comment]
These are just the ones that users reported so I'm thinking there's potentially more, I'd double check any seats that changed hands.

**Comment by showerst** [comment]
Thanks for the report! Do you mind posting these to https://github.com/openstates/people ? That's where we've moved the person data to make it easier to contribute to.

**Comment by putorti** [comment]
Moved to: https://github.com/openstates/people/issues/134
