### ISSUE TITLE
CA: Not including senate committees

### ISSUE THREAD

**Issue by mhedblom** [openstates/openstates#2897]
The California data does not include Senate committees. This query should return all (first 100) committees in CA, but it only include the Assembly (73 records).

[query](https://openstates.org/graphql?operationName=null&query=%7B%0A%20%20jurisdiction(name%3A%20%22California%22)%20%7B%0A%20%20%20%20name%0A%20%20%20%20organizations(%0A%20%20%20%20%20%20classification%3A%20%5B%22committee%22%5D%2C%0A%09%09%09first%3A%20100)%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20classification%0A%20%20%20%20%20%20%20%20%20%20parent%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20updatedAt%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20%20totalCount%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&variables=null)

```{
  jurisdiction(name: "California") {
    name
    organizations(
      classification: ["committee"],
			first: 100) {
      edges {
        node {
          id
          name
          classification
          parent {
            name
           }
          updatedAt
        }
      } 
      totalCount
    }
  }
}
```

**Comment by jamesturk** [comment]
see openstates/people#143
