### ISSUE TITLE
CA: Missing Bills

### ISSUE THREAD

**Issue by rotimi-babalola** [openstates/openstates#2923]
For the `20192020` session in California, the following bill numbers are missing - `SJR1`, `SJR2`, `SJR3`, `SJR4`, `SJR5` and `SJR6`.

The bills are on the California legislative website but when I query for them on the Openstates GraphQL API, I get a `Bill matching query does not exist` message.

Please is there any reason for this?

**Comment by showerst** [comment]
Looks like the scraper isn't picking up SJR's -- i'll try to get this patched up in the next day or two.

**Comment by showerst** [comment]
These should be live in the API now; can you confirm @rotimi-babalola and i'll close this bug?

**Comment by rotimi-babalola** [comment]
Confirmed. It's working 👍
