### ISSUE TITLE
AL: Alabama bill count very low

### ISSUE THREAD

**Issue by jessemortenson** [openstates/openstates#2954]
State: AL - Alabama

The [bill results for AL](https://openstates.org/graphql?operationName=null&query=%7B%0A%20%20bills(jurisdiction%3A%22Alabama%22%2Csession%3A%222019rs%22%2Cfirst%3A10)%20%7B%0A%0A%20%20%20%20totalCount%0A%20%20%7D%0A%7D) indicate that 133 bills are available for session `2019rs`.

```
{
  "data": {
    "bills": {
      "totalCount": 133
    }
  }
}
```

However the AL website lists "849 Instruments" in the results for searching the 2019 regular session with bills from both houses that have had one reading in house of origin (this page is unlinkable, because AL site is a horror). So a lot more bills should be showing up.

Running the scraper locally, it seems to work fine:

`docker-compose run --rm scrape al bills --scrape session=2019rs`

```
al (scrape)
  bills: {'session': '2019rs'}
bills scrape:
  duration:  0:25:43.643260
  objects:
    bill: 1067
    vote_event: 458
jurisdiction scrape:
  duration:  0:00:00.019707
  objects:
    jurisdiction: 1
    organization: 3
```

Anything I can do to help?

**Comment by jamesturk** [comment]
By default we only scrape the latest session which is determined by the order in the __init__.py, I've moved the special session for now, the next scrape should fix this

https://github.com/openstates/openstates/commit/bf59a03ea074b81af166fd0a3771c0f3b7e4ccfb

**Comment by jessemortenson** [comment]
Ah, OK. Most recent session is always the last item in the legislative_sessions array.

**Comment by jessemortenson** [comment]
Today API still reports 133 bills, looks like bobsled reports a scraper failure last night, but I get 403 when I try to view it: http://bobsled.openstates.org/run-AL-2019-05-17.html

**Comment by showerst** [comment]
Looks like they slightly changed the markup which broke get_session_list(), i'm looking into it now.

PS @jamesturk I get an aws access denied error on that bobsled run log.
