### ISSUE TITLE
Illinois(IL) Bill SB 25 in the 101st Regular Session Missing Actions on Website

### ISSUE THREAD

**Issue by SupposedlySam** [openstates/openstates#2977]
State: IL

The last action shown on OpenStates is from 03/05. However, there have been 115 Actions between 03/05 and 06/04.

Comparing data from ilga.gov here:
http://ilga.gov/legislation/billstatus.asp?DocNum=0025&GAID=15&GA=101&DocTypeID=SB&LegID=114175&SessionID=108

with OpenStates.org data here:
https://openstates.org/il/bills/101st/SB25/

**Comment by showerst** [comment]
@jamesturk @mileswwatkins IL hasn't updated in days, but I can't see the bobsled error logs due to an S3 access denied error.
