### ISSUE TITLE
No bulk json downloads since 2018, service stopped?

### ISSUE THREAD

**Issue by dimiloxa** [openstates/openstates#3008]
Looks like legacy JSON files are not updated anymore (latest update was back in Nov, 2018), is this service still available or maybe moved anywhere?

https://docs.openstates.org/en/latest/data/legacy-json.html

> Latest Update: November 3, 2018
The latest legacy JSON files can be obtained from a URL in the format: https://data.openstates.org/legacy/json/ak.zip

**Comment by jamesturk** [comment]
Those files are indeed no longer being created, as they're from our legacy
database.

If you're looking for legislators, that data is in
https://github.com/openstates/people -- and we can give out SQL dumps of
the new data as well if you need more.

**Comment by dimiloxa** [comment]
@jamesturk Thank you, that makes sense now. Do you think we can have access to the following data in your new environment:
bill_ligislator_votes
bills
bill_votes

**Comment by jamesturk** [comment]
try out
https://openstates-backups.s3.amazonaws.com/public/2019-06-26-public.pgdump
<https://openstates-backups.s3.amazonaws.com/public/2019-06-26-public.pgdump>

**Comment by jamesturk** [comment]
If you need it in an ongoing way get in touch via email.
