### ISSUE TITLE
NY: scrape amendments as versions, not separate bills

### ISSUE THREAD

**Issue by jessemortenson** [openstates/openstates#3017]
State: NY - New York

My issue is a reprise of #302 which was addressed years ago. It looks like after refactors (new data source etc) the issue is back. 

New York appears to organize its bills according to a base print number ("basePrintNo" in the NY API), let's say A8019 as an example. The original bill has basePrintNo of A8019 and printNo of A8019. 

Subsequent revisions to the content of that bill are "amendments". They have the same basePrintNo (A8019) but the printNo changes (A8019A). In Open States data, these are treated as separate bills. I believe this is incorrect. To see this, search for:

* `bill(jurisdiction:"New York", session:"2019-2020", identifier:"A 8019")`
* `bill(jurisdiction:"New York", session:"2019-2020", identifier:"A 8019A")`

Instead I believe that A8019A should be treated as a new Version of the existing A8019 Bill. It looks like the code keys off of `printNo` when [identifying a bill number](https://github.com/openstates/openstates/blob/master/openstates/ny/bills.py#L37). I believe the NY API only returns one representation of the bill (A8019), but this will likely appear to be two bills to the OS because at one point it will find printNo:A8019 but at a later point (after amendment) it will find printNo:A8019A in the same representation of the bill. And hence yield a new bill.

**Comment by showerst** [comment]
thanks @jessemortenson  -- looks like this should be an easy fix code wise, assuming they also provide the info to differentiate the printed document versions.

I'm concerned that suddenly merging/orphaning hundreds of bills might cause a bunch workflow issues, both for openstates and for API consumers/other scraper users (like me =P) down the line.

Ideally we'd just do this in between sessions, but it looks like that won't be until the end of 2020 for NY. 

@jamesturk let me know what you think, if it won't cause OS problems, i'm happy to take a look at the api and update the scraper next week, otherwise we can defer.

**Comment by jessemortenson** [comment]
Yeah, I agree that using `basePrintNo` instead of `printNo` seems, at a glance, to be a solution (I haven't had a chance to test yet). But yeah, the concern with existing data seems like the bigger issue. 

If the above change is made, won't this mostly mean that *some* existing bills will acquire some new versions? So it'll go from:

* A8019 (1 version)
* A8019A (1 version)

to 

* A8019 (2 versions)
* A8019A (1 version)

If I'm right about that, it seems ... somewhat better than the status quo? Better that some bills have the correct number of versions (ie A8019 has the introduced and the first amendment versions) than none of the bills have the correct numbers? API consumers could then choose to either stick with the existing (somewhat incorrect) representation of bills, or just filter out/ignore any bills that end with a letter.

**Comment by jamesturk** [comment]
I do think that might be the right call, Tim any objections?

**Comment by jamesturk** [comment]
re-opening for myself: after scraping w/ new scraper write a script to clean up old NY bills
