### ISSUE TITLE
improve Docker image(s)

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#3034]
alpine has once again broken gdal, breaking all scrapes in bobsled. might be time to just switch to an ubuntu-lite or similar that has a better maintainer for these key packages

**Comment by showerst** [comment]
Does it make sense to just have a 'leaner' dockerfile for just scrapers (or even non-ca scrapers?) with no GDAL, awscli, or MariaDB stuff? Might make the docs/startup more complicated so i'm not sure.

**Comment by jamesturk** [comment]
I think to simplify debugging people's issues, I'd rather avoid having one
that can't do database imports (which AFAIK means GDAL is needed)

As for awscli and MariaDB, I'd be fine having one without those.
Especially MariaDB since it is quite large.

Regardless though, I just don't think the stability is there in the
packages we depend on in alpine.  So I'll probably start by switching the
base image to the ubuntu minimal, which are pretty competitive on
size/speed.  Adding a separate docker image for CA makes sense, and that
might be a second step to this.

**Comment by jamesturk** [comment]
a partial/temporary fix in place, I think there are a few options:

- stick w/ the new base image, accept the size increase
- we could create an intermediate image that is more stable & not affected by the whims of upstream breakages (i.e. we'd build an openstates/base image and then base the openstates/openstates image on known good versions of it). this would be a bit more manual work, but would work around the stability/size tradeoff 
- find more ways to shrink the python:3.7-slim based image further, look for unnecessary dependencies


separately, CA should probably be it's own Dockerfile, working on that in a branch

**Comment by jamesturk** [comment]
combined was 1.35GB
California now has its own Dockerfile that includes mysql dependencies

(@showerst not sure how this affects your infrastructure, but you might want to build CA from Dockerfile.california if you're using our dockerfiles)

dropped uncompressed size down to 1GB again
