### ISSUE TITLE
RFC: run black on codebase & enforce going forward?

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#3036]
[black](https://github.com/psf/black/) is pretty mature at this point, now adopted by the PSF.  given the messy nature of scrapers and the number of contributors it might be beneficial to run black against Open States and enforce this going forward

pros: 
- uniform style
- once set up, reduced burden on devs to conform to an exact style

cons:
- additional tooling needed
- will be an enormous commit, making git history (blame) a bit more complicated to traverse

**Comment by jamesturk** [comment]
@showerst will this make anything bad for you?

**Comment by showerst** [comment]
@jamesturk let me check w/ my team and get back to you in the next day or two. 

Offhand I don't think so, I try to keep our openstates in sync with yours, so as you said just one (or a few) monster diffs to check out.

I haven't used black before, will it add any major burden to new committers as opposed to flake8? I think a stricter formatter is generally a good thing.

**Comment by jamesturk** [comment]
Sounds good.

As for ease of use, black is an auto-formatter, which takes some getting
used to as it reformats code, but overall should be lower burden.  A commit
that comes in from a brand new contributor that isn't set up with it can be
fixed with a simple `black openstates` run.   I think that'll be easier in
the long run

**Comment by showerst** [comment]
I think this is a good idea, though we should coordinate so it launches with updated documentation, let me know if you'd like help on that.

**Comment by jamesturk** [comment]
I've just pushed up some new docs, in addition to no longer referencing
things that don't exist, they mention installing pre-commit, which I think
would be the preferred way for most contributors to interact with black &
flake8 going forward.

https://docs.openstates.org/en/latest/contributing/getting-started.html#installing-pre-commit

Let me know if you have any suggestions.  My goal is to build out pages in
a similar structure to
https://docs.openstates.org/en/latest/contributing/scrapers.html for the
other components (openstates.org, text-extraction, and people).
