### ISSUE TITLE
MD: Scrape new website

### ISSUE THREAD

**Issue by showerst** [openstates/openstates#3042]
State: MD

Maryland launched a new website: http://mgaleg.maryland.gov/mgawebsite
The old one appears to be up for now, http://mgaleg.maryland.gov/webmga/frmLegislation.aspx?pid=legisnpage&tab=subject3 but it's unclear if they're going to post new data to it going forward.

**Comment by showerst** [comment]
WIP branch on this, saves bills but not votes -- tim/2019/md-2020

**Comment by jamesturk** [comment]
combining with #3045
