### ISSUE TITLE
Florida 2020 Session

### ISSUE THREAD

**Issue by bgehres** [openstates/openstates#3106]
State: Florida

Open States scrapers don't seem to be working for Florida.  I opened a topic in Open States discourse and James said bills will start showing up soon and he asked what legislators were missing.  I replied with the names of missing legislators but haven't heard anything.  I'm not a developer but had a custom bill tracking system developed that uses Open States as the primary data source.  Our session started Tuesday and we still don't have any current data.

Thanks and please advise.

**Comment by jamesturk** [comment]
Looking at this now.
FL bills are in our data https://openstates.org/fl/bills/2020/SB1376/

I never heard back from you on the other discourse on which people need to
be updated: https://discourse.openstates.org/t/florida-2020-session/467

That'd help a lot though, but either way we'll be doing a sweep of special
elections/etc. for FL soon.

**Comment by bgehres** [comment]
Thanks James.  I think I tried to reply to the email because my discourse account was put on hold.

The missing legislators are:

Rep Dan Daley (District 97), Rep Randy Maggard (District 38) and Rep Jason Shoaf (District 7).

Thanks!

**Comment by jamesturk** [comment]
Ah, discourse got aggressive with the anti-spam measure, fixed that now.
These reps are there too-- looks like they were added quite a while ago,
back in November in fact.
