### ISSUE TITLE
CT-2020 legislative data missing

### ISSUE THREAD

**Issue by doughardy-ctnj** [openstates/openstates#3160]
State: CT

Hi - hopefully someone can take a look at [https://openstates.org/ct/bills/](https://openstates.org/ct/bills/). I believe we have about 40 bills filed so far in Hartford but nothing new is showing on OpenStates.org/ct

Thanks in advance!

**Comment by jamesturk** [comment]
48 2020 CT bills are showing up, https://openstates.org/ct/bills/?query=&session=2020

**Comment by jamesturk** [comment]
It does look like the top of the page is dominated by a few bills which don't have any actions, filing a site bug here: https://github.com/openstates/openstates.org/issues/277
