### ISSUE TITLE
CA: adjust downloads

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#3187]
right now CA downloads grab the latest year, then layer days on top, it looks like the daily downloads might be sufficient

we also want to add support to the download.py script to grab prior years

- [x] limit current-year download to one file (if possible)
- [x] add download.py support for prior years
- [x] test scraper on prior years (however far back we can go without major changes)

**Comment by schneidy** [comment]
Archive data can now go back to 1989 with bills, and 1999 with bills and votes.
