### ISSUE TITLE
VT: bills without valid identifiers in database

### ISSUE THREAD

**Issue by azban** [openstates/openstates#3203]
`ocd-bill/8662fd02-bfeb-44bf-9118-0a33c54b0e39` has an identifier of `SR`, with no version links. this bill also appears correctly as `ocd-bill/2731b14b-30e4-43fd-a79e-45b04f1ba4d2`.

seems like this issue is well contained. there is only one in VT and no others in the other states i've checked (most but not all). given the VT scraper, it looks like this was probably an issue with their website, that resolved eventually.

what are thoughts around adding a check for valid bill identifiers? and is there any process for cleaning up old data that was imported incorrectly?

**Comment by jamesturk** [comment]
thanks for catching this, not sure how that slipped through.  there is a check but I suppose it is a bit too loose

I can clean up the data and will do so shortly

**Comment by azban** [comment]
are you talking about this as a check? https://github.com/openstates/openstates/blob/a8808cfe1477f5eb03812dbed016973f565633eb/openstates/vt/bills.py#L89 or is it somewhere else?

`re.sub` does not fail if it doesn't match

**Comment by jamesturk** [comment]
actually I thought we had a regex to check it, but fix_bill_id that runs on
everything doesn't actually reject data

https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/schemas/bill.py#L33.
would probably be the right place to enforce this

**Comment by jamesturk** [comment]
the VT Bill is removed though, going to open a pupa issue to reference this and close this issue
