### ISSUE TITLE
WA: No scraping since 3/5/2020?

### ISSUE THREAD

**Issue by atlaspolicy** [openstates/openstates#3215]
State: WA 

It doesn't appear that scraping is working for Washington. SB5811 has been updated a number of times in the last week (including passing the Senate), but it's not showing up on openstates.org. 

https://openstates.org/wa/bills/2019-2020/SB5811/

**Comment by showerst** [comment]
@jamesturk I checked the latest bobsled log and scrapes are running, but i don't see any SB's in the logs (kinda looks like they might just be truncated though?) https://bobsled.openstates.org/run/b6bd79fb71154378b199a95d10ffa53d

FWIW i'm getting those bills fine when i run locally.

**Comment by jamesturk** [comment]
there's data there from the 9th - there is however an ordering but on the actions on the page, but that'll be fixed in the next deploy

**Comment by atlaspolicy** [comment]
Thank you for the quick help!
