### ISSUE TITLE
PA voters have letters appended

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#3239]
There are voters like "Y SANTARSIERO" and "N STEFANO" -- need to look at splitting these properly.

**Comment by csnardi** [comment]
This was supposed to be fixed in #3193 and #3194 -- are you looking at historical data?

**Comment by jamesturk** [comment]
possibly!  this came from a report and i just opened this as a reminder to look into it

**Comment by schneidy** [comment]
@jamesturk Was this noticed on any specific bill?
