### ISSUE TITLE
Hawaii is missing roll call votes

### ISSUE THREAD

**Issue by jamesturk** [openstates/openstates#43]
roll call votes are irregular, impossible to reliably parse and not included in our data

this is noted on  http://openstates.sunlightlabs.com/status/
## 

migrated over from Google Code -- http://code.google.com/p/openstates/issues/detail?id=216

**Comment by bshor** [comment]
Is this fixed in OR and HI?

**Comment by jamesturk** [comment]
Sorry, should have included a message.  It hasn't but the issue list was
woefully out of date as it had been split across two ticketing systems for
a while and a lot of stale 2012 issues were around from before the
migration to the Sunlight JIRA bugtracker, many of which were closed
there.  We're going to start fresh and will most likely be opening
state-specific issue trackers in coming weeks as we get things up and
running again.
